### ISSUE TITLE
java/net/Authenticator/B4769350.java failed intermittently 

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1008]
java/net/Authenticator/B4769350.java failed intermittently 

```
12:52:10  Server: listening on port: 55220
12:52:10  Doing Proxy tests
12:52:10  STDERR:
12:52:10  java.lang.RuntimeException: Authenticator was called 3 times. Should be: 2
12:52:10  	at B4769350.except(B4769350.java:471)
12:52:10  	at B4769350.doProxyTests(B4769350.java:437)
12:52:10  	at B4769350.runTest(B4769350.java:461)
12:52:10  	at B4769350.main(B4769350.java:446)
12:52:10  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:52:10  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:52:10  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:52:10  	at java.lang.reflect.Method.invoke(Method.java:498)
12:52:10  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
12:52:10  	at java.lang.Thread.run(Thread.java:813)
12:52:10  
12:52:10  JavaTest Message: Test threw exception: java.lang.RuntimeException: Authenticator was called 3 times. Should be: 2
12:52:10  JavaTest Message: shutting down test
```

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_macos/140/console

JBS report closed : https://bugs.openjdk.java.net/browse/JDK-8031661

**Comment by sophia-guo** [comment]
closed as listed in #1511
