### ISSUE TITLE
MulticastSocket tests failing on AIX

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1011]
Three MulticastSocket tests fail on Aix with same exception `The socket name is not available on this system. (Error setting socket option)`

```
Standard Error

java.net.SocketException: The socket name is not available on this system. (Error setting socket option)
	at java.net.PlainDatagramSocketImpl.socketSetOption0(Native Method)
	at java.net.PlainDatagramSocketImpl.socketSetOption(PlainDatagramSocketImpl.java:74)
	at java.net.AbstractPlainDatagramSocketImpl.setOption(AbstractPlainDatagramSocketImpl.java:309)
	at java.net.MulticastSocket.setNetworkInterface(MulticastSocket.java:554)
	at SetGetNetworkInterfaceTest.main(SetGetNetworkInterfaceTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: Test Fail
	at SetGetNetworkInterfaceTest.main(SetGetNetworkInterfaceTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)

JavaTest Message: Test threw exception: java.lang.RuntimeException
JavaTest Message: shutting down test

    
```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_ppc64_aix/42/console

java/net/MulticastSocket/SetGetNetworkInterfaceTest.java
java/net/MulticastSocket/SetLoopbackMode.java
java/net/MulticastSocket/Test.java

**Comment by groeges** [comment]
Similar errors were seen on JDK11 and were reported here: https://bugs.openjdk.java.net/browse/JDK-8207404. There were some fixes made in JDK12 but these were not back-ported to JDK8

**Comment by sophia-guo** [comment]
@groeges Thanks! Will the fix be back-ported to JDK8?

**Comment by groeges** [comment]
@sophia-guo I am not sure. The code in JDK8 is quite different from that in JDK12. They might have deemed it too much work to try and do it. I will take a look and see if we can Gert them to back port it or to see if we can do it ourselves.

**Comment by sophia-guo** [comment]
Closed as fixed do not back port to JDK8
