### ISSUE TITLE
java/net/MulticastSocket/SetGetNetworkInterfaceTest.java throws java.net.SocketException: Cannot assign requested address

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1048]
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_x86-64_linux/368/testReport/junit/java_net_MulticastSocket_SetGetNetworkInterfaceTest/java/SetGetNetworkInterfaceTest/

```
Standard Error

java.net.SocketException: Cannot assign requested address (Error setting socket option)
	at java.net.PlainDatagramSocketImpl.socketSetOption0(Native Method)
	at java.net.PlainDatagramSocketImpl.socketSetOption(PlainDatagramSocketImpl.java:74)
	at java.net.AbstractPlainDatagramSocketImpl.setOption(AbstractPlainDatagramSocketImpl.java:309)
	at java.net.MulticastSocket.setNetworkInterface(MulticastSocket.java:554)
	at SetGetNetworkInterfaceTest.main(SetGetNetworkInterfaceTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: Test Fail
	at SetGetNetworkInterfaceTest.main(SetGetNetworkInterfaceTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)

JavaTest Message: Test threw exception: java.lang.RuntimeException

```

JBS as resolved: https://bugs.openjdk.java.net/browse/JDK-8027903

**Comment by adam-thorpe** [comment]
Test seems to be passing now so this can be closed

**Comment by M-Davies** [comment]
Failing again with the same error https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_xl/155/
```
java.net.SocketException: Cannot assign requested address (Error setting socket option)
	at java.net.PlainDatagramSocketImpl.socketSetOption(PlainDatagramSocketImpl.java:74)
	at java.net.AbstractPlainDatagramSocketImpl.setOption(AbstractPlainDatagramSocketImpl.java:309)
	at java.net.MulticastSocket.setNetworkInterface(MulticastSocket.java:554)
	at SetGetNetworkInterfaceTest.main(SetGetNetworkInterfaceTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:821)
```

Kicked off a grinder to determine failure rate https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2641/console

**Comment by M-Davies** [comment]
Grinder passed 10/10 iterations. Rerunning with a higher count https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2643/
