### ISSUE TITLE
win32 jdk run jtreg testcase TestCapacityUntilGCWrapAround fail

### ISSUE THREAD

**Issue by yansendao** [AdoptOpenJDK/openjdk-tests#1162]
**Platform:**
windows 32bit

**Architecture:**
intel x86

Please describe the issue that you are having with our binaries and if possible how to recreate it.
**binary:**
```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)

$ java -Xinternalversion
OpenJDK Server VM (25.212-b03) for windows-x86 JRE (1.8.0_212-b03), built on Apr 17 2019 13:42:04 by "jenkins" with MS VC++ 12.0 (VS2013)

```

**test command:**

jtreg -va -w tmp -nr jdk8u/hotspot/test/gc/metaspace/TestCapacityUntilGCWrapAround.java

**actual result:**
```
java.lang.IllegalStateException: WB_IncMetaspaceCapacityUntilGC: could not increase capacity until GC due to contention with another thread
        at sun.hotspot.WhiteBox.incMetaspaceCapacityUntilGC(Native Method)
        at TestCapacityUntilGCWrapAround.main(TestCapacityUntilGCWrapAround.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:748)

```

**expetc result:**
run pass

**Comment by sophia-guo** [comment]
```
01:36:51  java.lang.IllegalStateException: WB_IncMetaspaceCapacityUntilGC: could not increase capacity until GC due to contention with another thread
01:36:51  	at sun.hotspot.WhiteBox.incMetaspaceCapacityUntilGC(Native Method)
01:36:51  	at TestCapacityUntilGCWrapAround.main(TestCapacityUntilGCWrapAround.java:51)
01:36:51  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:36:51  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:36:51  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:36:51  	at java.lang.reflect.Method.invoke(Method.java:498)
01:36:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:36:51  	at java.lang.Thread.run(Thread.java:748)
01:36:51  
01:36:51  JavaTest Message: Test threw exception: java.lang.IllegalStateException: WB_IncMetaspaceCapacityUntilGC: could not increase capacity until GC due to contention with another thread
01:36:51  JavaTest Message: shutting down test
01:36:51  
01:36:51  STATUS:Failed.`main' threw exception: java.lang.IllegalStateException: WB_IncMetaspaceCapacityUntilGC: could not increase capacity until GC due to contention with another thread

```
https://ci.adoptopenjdk.net/view/Test_weekly/job/openjdk8_hs_openjdktest_extended_x86-32_windows/2/consoleFull

**Comment by smlambert** [comment]
@karianna - This was shifted to the test repo as a test bug, the test in question comes from the openjdk project?  

Is there a win32 openjdk build not from AdoptOpenJDK that we can check this against, to confirm that this may be an upstream test bug, rather than an issue with the binary itself?

**Comment by karianna** [comment]
https://download.bell-sw.com/java/8u212/bellsoft-jre8u212-windows-i586.msi should be a good alternative

**Comment by yansendao** [comment]
> https://download.bell-sw.com/java/8u212/bellsoft-jre8u212-windows-i586.msi should be a good alternative

win32 BellSoft JDK also fail with the same reason.

```
$ java -version
openjdk version "1.8.0_212"
LibericaJDK Runtime Environment (build 1.8.0_212-BellSoft-b12)
LibericaJDK Client VM (build 25.212-b12, mixed mode)
```

**Comment by smlambert** [comment]
So this should get reported upstream to the OpenJDK project.  Has someone done this?

**Comment by karianna** [comment]
I've asked the adopt JBS team to file it, I'll post the link here when that's done.

**Comment by jerboaa** [comment]
Filed: https://bugs.openjdk.java.net/browse/JDK-8226236

**Comment by karianna** [comment]
Thanks - closing this downstream issue

@yansendao you can track the issue upstream - once fixed we'll pick it up.
