### ISSUE TITLE
jdk_core:javax/xml/ws/8172297/Main.java failed

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#119]
20:58:56 ACTION: testng -- Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
20:58:56 REASON: User specified action: run testng/othervm Main 
20:58:56 TIME:   4.861 seconds
20:58:56 messages:
20:58:56 command: testng Main
20:58:56 reason: User specified action: run testng/othervm Main 
20:58:56 Mode: othervm [/othervm specified]
20:58:56 elapsed time (seconds): 4.861
20:58:56 configuration:
20:58:56 STDOUT:
20:58:56 [TestNG] Running:
20:58:56   javax/xml/ws/8172297/Main.java
20:58:56 
20:58:56 Publishing WebService on 37904 port
20:58:56 Waiting for done signal from test client.
20:58:56 Launching WS client connection on 37904 port
20:58:56 Client input parameter: '#CR#CR#NL#CR#CR CarriageReturn and NewLine #CR#NL#NL Test #CR#CR#CR#CR'
20:58:56 Server-side parameter value: '#NL#NL#NL#NL CarriageReturn and NewLine #NL#NL Test #NL#NL#NL#NL'
20:58:56 Client response parameter: '#NL#NL#NL#NL CarriageReturn and NewLine #NL#NL Test #NL#NL#NL#NL'
20:58:56 Got done signal from the client. Stopping WS endpoint.
20:58:56 test Main.runTest(): failure
20:58:56 java.lang.AssertionError: WS parameter was modified during round trip. expected [false] but found [true]
20:58:56 	at org.testng.Assert.fail(Assert.java:94)
20:58:56 	at org.testng.Assert.failNotEquals(Assert.java:496)
20:58:56 	at org.testng.Assert.assertFalse(Assert.java:63)
20:58:56 	at Main.runTest(Main.java:65)
20:58:56 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:58:56 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:58:56 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:58:56 	at java.lang.reflect.Method.invoke(Method.java:498)
20:58:56 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
20:58:56 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
20:58:56 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
20:58:56 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
20:58:56 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
20:58:56 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
20:58:56 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
20:58:56 	at org.testng.TestRunner.run(TestRunner.java:623)
20:58:56 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
20:58:56 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
20:58:56 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
20:58:56 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
20:58:56 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
20:58:56 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
20:58:56 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
20:58:56 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
20:58:56 	at org.testng.TestNG.run(TestNG.java:1018)
20:58:56 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
20:58:56 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
20:58:56 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:58:56 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:58:56 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:58:56 	at java.lang.reflect.Method.invoke(Method.java:498)
20:58:56 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
20:58:56 	at java.lang.Thread.run(Thread.java:748)

**Comment by sophia-guo** [comment]
Duplicate of #127
