### ISSUE TITLE
OpenJDK Regression (jtreg) httpclient tests fail with "connection refused" on zLinux

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#1246]
- Summary:

"Connection refused" coming from http tests. 

No results while searching online, implies this issue is unique to us and our machine setup.

- Details:

These tests seem to be failing frequently on zLinux, for Hotspot and OpenJ9 builds.

java/net/httpclient/ConnectTimeoutNoProxyAsync.java
java/net/httpclient/ConnectTimeoutNoProxySync.java
java/net/httpclient/ConnectTimeoutWithProxyAsync.java
java/net/httpclient/ConnectTimeoutWithProxySync.java

Example: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux/13/consoleText

Example error message:

```
[2019-07-31T23:11:36.568Z] java.net.ConnectException: Connection refused
[2019-07-31T23:11:36.568Z] 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2019-07-31T23:11:36.568Z] 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
[2019-07-31T23:11:36.568Z] 	at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectEvent.handle(PlainHttpConnection.java:128)
[2019-07-31T23:11:36.568Z] 	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:957)
[2019-07-31T23:11:36.568Z] 	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:912)
[2019-07-31T23:11:36.568Z] 	at jdk.internal.net.http.HttpClientImpl$SelectorManager$$Lambda$109.00000000140066A0.accept(Unknown Source)
[2019-07-31T23:11:36.568Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
[2019-07-31T23:11:36.568Z] 	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:912)
[2019-07-31T23:11:36.568Z] test ConnectTimeoutNoProxyAsync.timeoutNoProxyAsync(HTTP_2, "https", "GET", null, PT1S): failure
[2019-07-31T23:11:36.569Z] java.lang.AssertionError: Expected HttpConnectTimeoutException, got:java.net.ConnectException: Connection refused
[2019-07-31T23:11:36.569Z] 	at org.testng.Assert.fail(Assert.java:94)
[2019-07-31T23:11:36.569Z] 	at AbstractConnectTimeout.assertExceptionTypeAndCause(AbstractConnectTimeout.java:237)
[2019-07-31T23:11:36.569Z] 	at AbstractConnectTimeout.timeoutAsync(AbstractConnectTimeout.java:202)
[2019-07-31T23:11:36.569Z] 	at AbstractConnectTimeout.timeoutNoProxyAsync(AbstractConnectTimeout.java:162)
[2019-07-31T23:11:36.569Z] 	at ConnectTimeoutNoProxyAsync.timeoutNoProxyAsync(ConnectTimeoutNoProxyAsync.java:45)
[2019-07-31T23:11:36.569Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-07-31T23:11:36.569Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-07-31T23:11:36.569Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-07-31T23:11:36.569Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2019-07-31T23:11:36.569Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2019-07-31T23:11:36.569Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2019-07-31T23:11:36.569Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2019-07-31T23:11:36.569Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2019-07-31T23:11:36.569Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2019-07-31T23:11:36.569Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2019-07-31T23:11:36.569Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2019-07-31T23:11:36.569Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2019-07-31T23:11:36.569Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2019-07-31T23:11:36.569Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2019-07-31T23:11:36.569Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2019-07-31T23:11:36.569Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2019-07-31T23:11:36.569Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2019-07-31T23:11:36.569Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2019-07-31T23:11:36.569Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2019-07-31T23:11:36.569Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2019-07-31T23:11:36.569Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2019-07-31T23:11:36.569Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2019-07-31T23:11:36.569Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2019-07-31T23:11:36.569Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-07-31T23:11:36.569Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-07-31T23:11:36.569Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-07-31T23:11:36.569Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2019-07-31T23:11:36.569Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2019-07-31T23:11:36.569Z] 	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by smlambert** [comment]
Please determine which machines this is specific to.  This likely needs to be raised as an openjdk-infrastructure issue, once you have triaged more thoroughly

**Comment by adamfarley** [comment]
Known to fail on test-marist-ubuntu1604-s390x-2-XJ. Currently trying to run the test on our other zLinux machines to see if the issue's seen there too.

Noticed that test-marist-sles12-s390x-1 is suffering ssh agent issues. Will raise an infra bug.

```hudson.AbortException: Failed to run ssh-agent

**Comment by adamfarley** [comment]
Issue occurs on both test-marist-ubuntu1604-s390x-1 and test-marist-ubuntu1604-s390x-2-XJ

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux/21/consoleFull
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux/22/consoleFull

The only other s390 test machine can't run the test due to some ssh agent issue, so I'm raising an infra issue to review to two affected machines.

**Comment by adamfarley** [comment]
Issue raised: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/880

Will close this for now and monitor that issue. I can re-open this later if diagnostics show no obvious problems with the machines themselves.

**Comment by adamfarley** [comment]
Machines were cleared out, but the issue remains on Hotspot and OpenJ9. Investigating.

**Comment by adamfarley** [comment]
Ok, this is taking time. I'm not seeing a defect on OpenJDK for this issue, so I'll leave this here until I or someone else finds time to investigate further.
