### ISSUE TITLE
Test failures with jdk11+ hotspot on windows

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1272]
Test category: openjdk
Test name(s):
com/sun/net/httpserver/bugs/B6361557.java

Product(s) tested:
21:19:14  openjdk version "11.0.5" 2019-10-15
21:19:14  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10-201908071815)
21:19:14  OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10-201908071815, mixed mode)

OS/architecture: windows
Platform specific: yes

Reproducibility: yes

```
Stacktrace

Execution failed: `main' threw exception: java.net.ConnectException: Connection refused: connect    

Standard Output

destaddr /127.0.0.1:52591
    

Standard Error

java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at java.base/java.nio.channels.SocketChannel.open(SocketChannel.java:194)
	at B6361557.main(B6361557.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)

JavaTest Message: Test threw exception: java.net.ConnectException: Connection refused: connect
```

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_x86-64_windows/22/console
JBS: https://bugs.openjdk.java.net/browse/JDK-8196070

**Comment by sophia-guo** [comment]
Test category: openjdk
Test name(s):
java/util/concurrent/tck/JSR166TestCase.java
Product(s) tested:
21:19:14 openjdk version "11.0.5" 2019-10-15
21:19:14 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10-201908071815)
21:19:14 OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10-201908071815, mixed mode)

OS/architecture: windows
Platform specific: yes

Reproducibility: yes

```
Stacktrace

Execution failed: `main' threw exception: java.lang.Exception: JUnit test failure    

Standard Output

    

Standard Error
```

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_x86-64_windows/22/console
JBS：https://bugs.openjdk.java.net/browse/JDK-8212899

**Comment by sophia-guo** [comment]
java/lang/String/StringRepeat.java test requests too much heap

JBS: https://bugs.openjdk.java.net/browse/JDK-8221400 Fixes in. However we could still see the failure with win86-32:

```
Stacktrace

Unexpected exit from test [exit code: 1]    

Standard Output

Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_x86-32_windows/29/testReport/java_lang_String_StringRepeat/java/StringRepeat/

**Comment by karianna** [comment]
> java/lang/String/StringRepeat.java test requests too much heap
> 
> JBS: https://bugs.openjdk.java.net/browse/JDK-8221400 Fixes in. However we could still see the failure with win86-32:
> 
> ```
> Stacktrace
> 
> Unexpected exit from test [exit code: 1]    
> 
> Standard Output
> 
> Error occurred during initialization of VM
> Could not reserve enough space for 2097152KB object heap
> ```
> 
> https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_x86-32_windows/29/testReport/java_lang_String_StringRepeat/java/StringRepeat/

Probably worth requested a patch in that case - easy to forget poor old 32-bit systems!

**Comment by sophia-guo** [comment]
@karianna https://bugs.openjdk.java.net/browse/JDK-8221400 was opened and fixed for win-32, but still looks like doesn't work

**Comment by karianna** [comment]
> @karianna https://bugs.openjdk.java.net/browse/JDK-8221400 was opened and fixed for win-32, but still looks like doesn't work

Aleksey Shipilev from Red Hat's test seems to pass with that patch.  Hmm, are you able to comment on the https://bugs.openjdk.java.net/browse/JDK-8221832 backport issue?  I don't have the rights...

**Comment by adam-thorpe** [comment]
com/sun/net/httpserver/bugs/B6361557.java fix was put in to https://bugs.openjdk.java.net/browse/JDK-8223145 on jdk13/head but not 11

**Comment by karianna** [comment]
> com/sun/net/httpserver/bugs/B6361557.java fix was put in to https://bugs.openjdk.java.net/browse/JDK-8223145 on jdk13/head but not 11

@sophia-guo - If I'm reading that bug properly we should exclude the test for Java 11 unless a 
backport is provided upstream.

**Comment by sophia-guo** [comment]
Yes @karianna , test has been excluded for JAVA 11.

**Comment by karianna** [comment]
> Yes @karianna , test has been excluded for JAVA 11.

@sophia-guo - so this should be closed or...?

**Comment by sophia-guo** [comment]
There are two other issues need to be addressed.

https://github.com/AdoptOpenJDK/openjdk-tests/issues/1272#issuecomment-520587976
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1272#issuecomment-522005142

**Comment by sophia-guo** [comment]
Issues on the above comments have jbs reported and with status 'resovled'. Though looks like it's not resolved by running our test build. Should we close this or someone need to report to JBS? @ShelleyLambert
