### ISSUE TITLE
JTReg Test Failure: java/lang/invoke/ArrayConstructorTest.java

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1288]
- Test: https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/965d0c0df359f3da224b865701bbcc044b7104c2/test/jdk/java/lang/invoke/ArrayConstructorTest.java#L1 for JDK11 and test https://github.ibm.com/runtimes/openj9-openjdk-jdk8/blob/514f6986c07ea2dbde7cf7264e9d7e66884cc26c/jdk/test/java/lang/invoke/ArrayConstructorTest.java#L1 for JDK8 are consistantly failing
- Category: openjdk
- OS/Architecture: OS/Architecture: x86-64_linux, x86-64_osx, x86-64_windows
- Jenkins Build:
```
Eclipse OpenJ9 VM AdoptOpenJDK (build master-1625c27d4, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190818_321 (JIT enabled, AOT enabled)
13:19:33  OpenJ9   - 1625c27d4
13:19:33  OMR      - 6e99760b
13:19:33  JCL      - 965d0c0df3 based on jdk-11.0.4+11)
```
Optional Info
-------------
- Part of the excluded jdk11 openj9 JTReg Tests: https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
- There are two issues with this file:
1) `testFindConstructorArray()` is failing for JDK8 and JDK11. This is an `AssertionError` and is due to a `null` return from a `getMessage()`
2) `testArrayConstructorNegative()` fails for JDK11 only and is also due to `AssertionError`. The expected and actual results are near identical, the test could be adjusted to compensate for the difference in grammar.

Failure Output
--------------
JDK8
-----
```
STDOUT:
13:37:06  [TestNG] Running:
13:37:06    java/lang/invoke/ArrayConstructorTest.java
13:37:06  
13:37:06  test test.java.lang.invoke.ArrayConstructorTest.testFindConstructorArray(): failure
13:37:06  java.lang.AssertionError: expected:<no constructor for array class: [Ljava.lang.Object;> but was:<null>
13:37:06  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
13:37:06  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
13:37:06  	at test.java.lang.invoke.ArrayConstructorTest.testFindConstructorArray(ArrayConstructorTest.java:52)
13:37:06  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:37:06  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:37:06  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:37:06  	at java.lang.reflect.Method.invoke(Method.java:498)
13:37:06  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
13:37:06  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
13:37:06  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
13:37:06  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
13:37:06  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
13:37:06  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
13:37:06  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
13:37:06  	at org.testng.TestRunner.run(TestRunner.java:623)
13:37:06  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
13:37:06  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
13:37:06  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
13:37:06  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
13:37:06  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
13:37:06  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
13:37:06  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
13:37:06  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
13:37:06  	at org.testng.TestNG.run(TestNG.java:1018)
13:37:06  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
13:37:06  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
13:37:06  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:37:06  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:37:06  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:37:06  	at java.lang.reflect.Method.invoke(Method.java:498)
13:37:06  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:37:06  	at java.lang.Thread.run(Thread.java:819)
13:37:06  
13:37:06  ===============================================
13:37:06  java/lang/invoke/ArrayConstructorTest.java
13:37:06  Total tests run: 1, Failures: 1, Skips: 0
13:37:06  ===============================================
13:37:06  
13:37:06  STDERR:
13:37:06  java.lang.Exception: failures: 1
13:37:06  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
13:37:06  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
13:37:06  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:37:06  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:37:06  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:37:06  	at java.lang.reflect.Method.invoke(Method.java:498)
13:37:06  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:37:06  	at java.lang.Thread.run(Thread.java:819)
13:37:06  
13:37:06  JavaTest Message: Test threw exception: java.lang.Exception: failures: 1
13:37:06  JavaTest Message: shutting down test
```
JDK11
------
```
STDOUT:
13:21:23  [TestNG] Running:
13:21:23    java/lang/invoke/ArrayConstructorTest.java
13:21:23  
13:21:23  test test.java.lang.invoke.ArrayConstructorTest.testArrayConstructor(): success
13:21:23  test test.java.lang.invoke.ArrayConstructorTest.testArrayConstructorNegative(class java.lang.String, java.lang.Class@a4a508b0, "not an array class: java.lang.String"): failure
13:21:23  java.lang.AssertionError: expected:<not an array class: java.lang.String> but was:<java.lang.String is not an array type.>
13:21:23  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
13:21:23  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
13:21:23  	at test.java.lang.invoke.ArrayConstructorTest.testArrayConstructorNegative(ArrayConstructorTest.java:76)
13:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:21:23  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:21:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:21:23  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
13:21:23  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
13:21:23  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
13:21:23  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
13:21:23  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
13:21:23  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
13:21:23  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
13:21:23  	at org.testng.TestRunner.run(TestRunner.java:623)
13:21:23  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
13:21:23  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
13:21:23  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
13:21:23  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
13:21:23  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
13:21:23  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
13:21:23  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
13:21:23  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
13:21:23  	at org.testng.TestNG.run(TestNG.java:1018)
13:21:23  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
13:21:23  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
13:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:21:23  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:21:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:21:23  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:21:23  	at java.base/java.lang.Thread.run(Thread.java:831)
13:21:23  test test.java.lang.invoke.ArrayConstructorTest.testArrayConstructorNegative(null, java.lang.Class@a06b9995, null): success
13:21:23  test test.java.lang.invoke.ArrayConstructorTest.testArrayConstructorNegativeIndex(): success
13:21:23  test test.java.lang.invoke.ArrayConstructorTest.testFindConstructorArray(): failure
13:21:23  java.lang.AssertionError: expected:<no constructor for array class: [Ljava.lang.Object;> but was:<null>
13:21:23  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
13:21:23  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
13:21:23  	at test.java.lang.invoke.ArrayConstructorTest.testFindConstructorArray(ArrayConstructorTest.java:52)
13:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:21:23  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:21:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:21:23  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
13:21:23  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
13:21:23  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
13:21:23  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
13:21:23  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
13:21:23  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
13:21:23  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
13:21:23  	at org.testng.TestRunner.run(TestRunner.java:623)
13:21:23  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
13:21:23  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
13:21:23  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
13:21:23  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
13:21:23  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
13:21:23  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
13:21:23  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
13:21:23  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
13:21:23  	at org.testng.TestNG.run(TestNG.java:1018)
13:21:23  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
13:21:23  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
13:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:21:23  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:21:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:21:23  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:21:23  	at java.base/java.lang.Thread.run(Thread.java:831)
13:21:23  
13:21:23  ===============================================
13:21:23  java/lang/invoke/ArrayConstructorTest.java
13:21:23  Total tests run: 5, Failures: 2, Skips: 0
13:21:23  ===============================================
13:21:23  
13:21:23  STDERR:
13:21:23  java.lang.Exception: failures: 2
13:21:23  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
13:21:23  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
13:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:21:23  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:21:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:21:23  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:21:23  	at java.base/java.lang.Thread.run(Thread.java:831)
13:21:23  
13:21:23  JavaTest Message: Test threw exception: java.lang.Exception: failures: 2
13:21:23  JavaTest Message: shutting down test
```

**Comment by M-Davies** [comment]
I suspect the `null` error in both JDK's is down to `Ljava.lang.Object` currently not being suitable for OpenJ9 (in which case this test can be safely excluded). Since both outcomes of the assertion error are so similar, I'm happy to just copy-pasta the actual output into the test and consider that specific case fixed

**Comment by M-Davies** [comment]
Discussions in OpenJDK led to the decision to perm exclude this test due to static error messages being designed for hotspot and subject to change.
