### ISSUE TITLE
Mac hotspot_jre: compiler/unsafe/TestRawAliasing.java failed with Execution failed: `main' threw exception: java.lang.RuntimeException: Unexpected magic value

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#131]
<pre>18:41:13 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Unexpected magic value
18:41:13 REASON: User specified action: run main/othervm -XX:CompileCommand=exclude,*.main -XX:-TieredCompilation -XX:-BackgroundCompilation compiler.unsafe.TestRawAliasing 
18:41:13 TIME:   0.822 seconds
18:41:13 messages:
18:41:13 command: main -XX:CompileCommand=exclude,*.main -XX:-TieredCompilation -XX:-BackgroundCompilation compiler.unsafe.TestRawAliasing
18:41:13 reason: User specified action: run main/othervm -XX:CompileCommand=exclude,*.main -XX:-TieredCompilation -XX:-BackgroundCompilation compiler.unsafe.TestRawAliasing 
18:41:13 Mode: othervm [/othervm specified]
18:41:13 elapsed time (seconds): 0.822
18:41:13 configuration:
18:41:13 STDOUT:
18:41:13 CompilerOracle: exclude *.main
18:41:13 STDERR:
18:41:13 java.lang.RuntimeException: Unexpected magic value
18:41:13 	at compiler.unsafe.TestRawAliasing.main(TestRawAliasing.java:66)
18:41:13 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:41:13 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:41:13 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:41:13 	at java.lang.reflect.Method.invoke(Method.java:498)
18:41:13 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
18:41:13 	at java.lang.Thread.run(Thread.java:748)
18:41:13 
18:41:13 JavaTest Message: Test threw exception: java.lang.RuntimeException: Unexpected magic value
18:41:13 JavaTest Message: shutting down test
18:41:13 
18:41:13 STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Unexpected magic value
18:41:13 rerun:
18:41:13 HOME=/Users/jenkins \
18:41:13 PATH=/bin:/usr/bin \
18:41:13 CLASSPATH=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/compiler/unsafe/TestRawAliasing.d:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/compiler/unsafe:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
18:41:13     /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
18:41:13         -Dtest.class.path.prefix=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/compiler/unsafe/TestRawAliasing.d:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/compiler/unsafe \
18:41:13         -Dtest.src=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/compiler/unsafe \
18:41:13         -Dtest.src.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/compiler/unsafe \
18:41:13         -Dtest.classes=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/compiler/unsafe/TestRawAliasing.d \
18:41:13         -Dtest.class.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/compiler/unsafe/TestRawAliasing.d \
18:41:13         -Dtest.vm.opts='-ea -esa -Xmx512m' \
18:41:13         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
18:41:13         -Dtest.compiler.opts= \
18:41:13         -Dtest.java.opts= \
18:41:13         -Dtest.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:41:13         -Dcompile.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:41:13         -Dtest.timeout.factor=4.0 \
18:41:13         -ea \
18:41:13         -esa \
18:41:13         -Xmx512m \
18:41:13         -XX:CompileCommand=exclude,*.main \
18:41:13         -XX:-TieredCompilation \
18:41:13         -XX:-BackgroundCompilation \
18:41:13         com.sun.javatest.regtest.agent.MainWrapper /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/compiler/unsafe/TestRawAliasing.d/main.0.jta
18:41:13 
18:41:13 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Unexpected magic value
</pre>

**Comment by sophia-guo** [comment]
rerun on linux and mac, works fine.
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_x86-64_personal/133/ https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_x86-64_personal/132/

Will re-enable later.
