### ISSUE TITLE
JTReg Test Failure:  java/lang/invoke/RevealDirectTest.java

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1344]
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/6716544a3e1aab5520e36418b4378172e358fd2f/test/jdk/java/lang/invoke/RevealDirectTest.java#L1 consistantly fails for JDK11-openj9 & JDK8-hotspot (all other hotspot implementations are unaffected).
- Category, openjdk
- OS's, x86_linux/windows/osx
```
11:43:58  Eclipse OpenJ9 VM AdoptOpenJDK (build master-d65742671, JRE 11 Linux amd64-64-Bit Compressed References 20190911_331 (JIT enabled, AOT enabled)
11:43:58  OpenJ9   - d65742671
11:43:58  OMR      - 7e9584ea
11:43:58  JCL      - 8057a0754d based on jdk-11.0.5+6)
```
```
11:46:04  STDOUT:
11:46:04  @Test testSimple executed 107 positive tests in 79 ms
11:46:04  @Test testPublicLookup/1 executed 56 positive tests in 22 ms
11:46:04  @Test testPublicLookup/2 executed 80 positive tests in 38 ms
11:46:04  @Test testPublicLookup/3 executed 56 positive tests in 46 ms
11:46:04  *** FAIL: protected java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException => java.lang.AssertionError: unexpected lookup for negative test
11:46:04  *** FAIL: protected void java.lang.Object.finalize() throws java.lang.Throwable => java.lang.AssertionError: unexpected lookup for negative test
11:46:04  @Test testPublicLookupNegative/1 executed 19/0/0 negative tests in 14 ms
11:46:04  @Test testJavaLangClass executed 60 positive tests in 21 ms
11:46:04  @Test testCallerSensitive executed 30 positive tests in 19 ms
11:46:04  @Test testCallerSensitiveNegative/1 executed 15/0/0 negative tests in 0 ms
11:46:04  @Test testCallerSensitiveNegative/2 executed 0/15/0 negative tests in 2 ms
11:46:04  @Test testCallerSensitiveNegative/3 executed 0/15/0 negative tests in 1 ms
11:46:04  @Test testMethodHandleNatives executed 4 positive tests in 2 ms
11:46:04  *** FAIL: public final native java.lang.invoke.MethodHandle.invoke(Object[])Object => java.lang.AssertionError: expected:<4369> but was:<401>
11:46:04  @Test testMethodHandleInvokes/1 executed 639 positive tests in 109 ms
11:46:04  STDERR:
11:46:04  JavaTest Message: JUnit Failure: testPublicLookupNegative(test.java.lang.invoke.RevealDirectTest): unexpected lookup for negative test
11:46:04  java.lang.AssertionError: unexpected lookup for negative test
11:46:04  	at test.java.lang.invoke.RevealDirectTest.testWithMember(RevealDirectTest.java:701)
11:46:04  	at test.java.lang.invoke.RevealDirectTest.testOnMembersImpl(RevealDirectTest.java:385)
11:46:04  	at test.java.lang.invoke.RevealDirectTest.testOnMembersNoLookup(RevealDirectTest.java:362)
11:46:04  	at test.java.lang.invoke.RevealDirectTest.testPublicLookupNegative(RevealDirectTest.java:130)
11:46:04  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:46:04  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:46:04  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:46:04  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:46:04  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
11:46:04  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
11:46:04  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
11:46:04  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
11:46:04  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
11:46:04  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
11:46:04  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
11:46:04  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
11:46:04  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
11:46:04  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
11:46:04  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
11:46:04  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
11:46:04  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
11:46:04  	at org.junit.runners.Suite.runChild(Suite.java:128)
11:46:04  	at org.junit.runners.Suite.runChild(Suite.java:24)
11:46:04  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
11:46:04  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
11:46:04  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
11:46:04  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
11:46:04  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
11:46:04  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
11:46:04  	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
11:46:04  	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
11:46:04  	at org.junit.runner.JUnitCore.run(JUnitCore.java:127)
11:46:04  	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:76)
11:46:04  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:76)
11:46:04  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
11:46:04  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:46:04  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:46:04  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:46:04  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:46:04  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
11:46:04  	at java.base/java.lang.Thread.run(Thread.java:831)
11:46:04  
11:46:04  JavaTest Message: JUnit Failure: testMethodHandleInvokes(test.java.lang.invoke.RevealDirectTest): expected:<4369> but was:<401>
11:46:04  java.lang.AssertionError: expected:<4369> but was:<401>
11:46:04  	at org.junit.Assert.fail(Assert.java:93)
11:46:04  	at org.junit.Assert.failNotEquals(Assert.java:647)
11:46:04  	at org.junit.Assert.assertEquals(Assert.java:128)
11:46:04  	at org.junit.Assert.assertEquals(Assert.java:472)
11:46:04  	at org.junit.Assert.assertEquals(Assert.java:456)
11:46:04  	at test.java.lang.invoke.RevealDirectTest.consistent(RevealDirectTest.java:640)
11:46:04  	at test.java.lang.invoke.RevealDirectTest.testWithMember(RevealDirectTest.java:719)
11:46:04  	at test.java.lang.invoke.RevealDirectTest.testOnMembersImpl(RevealDirectTest.java:385)
11:46:04  	at test.java.lang.invoke.RevealDirectTest.testOnMembers(RevealDirectTest.java:358)
11:46:04  	at test.java.lang.invoke.RevealDirectTest.testMethodHandleInvokes(RevealDirectTest.java:185)
11:46:04  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:46:04  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:46:04  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:46:04  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:46:04  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
11:46:04  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
11:46:04  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
11:46:04  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
11:46:04  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
11:46:04  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
11:46:04  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
11:46:04  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
11:46:04  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
11:46:04  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
11:46:04  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
11:46:04  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
11:46:04  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
11:46:04  	at org.junit.runners.Suite.runChild(Suite.java:128)
11:46:04  	at org.junit.runners.Suite.runChild(Suite.java:24)
11:46:04  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
11:46:04  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
11:46:04  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
11:46:04  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
11:46:04  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
11:46:04  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
11:46:04  	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
11:46:04  	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
11:46:04  	at org.junit.runner.JUnitCore.run(JUnitCore.java:127)
11:46:04  	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:76)
11:46:04  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:76)
11:46:04  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
11:46:04  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:46:04  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:46:04  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:46:04  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:46:04  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
11:46:04  	at java.base/java.lang.Thread.run(Thread.java:831)
11:46:04  
11:46:04  java.lang.Exception: JUnit test failure
11:46:04  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:92)
11:46:04  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
11:46:04  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:46:04  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:46:04  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:46:04  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:46:04  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
11:46:04  	at java.base/java.lang.Thread.run(Thread.java:831)
11:46:04  
11:46:04  JavaTest Message: Test threw exception: java.lang.Exception: JUnit test failure
11:46:04  JavaTest Message: shutting down test
11:46:04  
```

**Comment by smlambert** [comment]
@M-Davies - please go through all of the recent issues you have raised in this repo.  For any of them that are implementation specific, please raise the issue in the correct upstream repo and close the issue in openjdk-tests.  We want to raise the issues in the correct repos when possible, and not carry duplicate issues in multiple repos.

Please also refer to the https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/doc/Triage.md for extra guidance.

**Comment by M-Davies** [comment]
Will do! The only reason I raised this one here was because it also fails for JDK8-hotspot which wouldn't have been appropriate to raise in the openj9 upstream repo.

**Comment by smlambert** [comment]
Ok, thanks.  It was not clear about the JDK8-hotspot, as the first sentence stated:
_"consistantly fails for JDK11-openj9 (JDK8-openj9 and all hotspot implementations are unaffected)."_

**Comment by M-Davies** [comment]
Ah. A typo that must have slipped in. Thanks for pointing it out!

**Comment by M-Davies** [comment]
This test is now passing on hotspot. Will move to openj9
