### ISSUE TITLE
JTReg Test Failure:  java/util/logging/TestLoggerWeakRefLeak.java

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-tests#1352]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/514/
Platform: all
Version: 8, 11, 13

Test should be permanently excluded on openj9 since it uses hotspot specific methods.
Fails this line:
```
HotSpotVirtualMachine vm = (HotSpotVirtualMachine) VirtualMachine
                .attach(Long.toString(ProcessTools.getProcessId()));
```

```
11:10:38  java.lang.ClassCastException: com.ibm.tools.attach.attacher.OpenJ9VirtualMachine incompatible with sun.tools.attach.HotSpotVirtualMachine
11:10:38  	at java.base/java.lang.ClassCastException.<init>(ClassCastException.java:71)
11:10:38  	at TestLoggerWeakRefLeak.getInstanceCountFromHeapHisto(TestLoggerWeakRefLeak.java:132)
11:10:38  	at TestLoggerWeakRefLeak.testIfLeaking(TestLoggerWeakRefLeak.java:82)
11:10:38  	at TestLoggerWeakRefLeak.main(TestLoggerWeakRefLeak.java:59)
11:10:38  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:10:38  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:10:38  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:10:38  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:10:38  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
11:10:38  	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by smlambert** [comment]
If this is not applicable test, it should be added to list in https://github.com/AdoptOpenJDK/openjdk-tests/issues/1297 and this issue closed.

**Comment by adam-thorpe** [comment]
Done
