### ISSUE TITLE
jdk-13+33 mac jvm_net B8185898 test failure

### ISSUE THREAD

**Issue by johnoliver** [AdoptOpenJDK/openjdk-tests#1354]
https://ci.adoptopenjdk.net/job/Test_openjdk13_hs_sanity.openjdk_x86-64_mac/53/console

Machine: test-macincloud-macos1014-x64-1
Version: 13+33

```
13:57:22  java.lang.AssertionError: FAILED: expected: This /is/a/fake/status/line HTTP/2.0
13:57:22  X-header1: This test value should appear
13:57:22  X-header2: This test value should appear
13:57:22  This is not a request line for HTTP/1.1:
13:57:22  
13:57:22  
13:57:22  Received: This /is/a/fake/status/line HTTP/2.0
13:57:22  X-header1: This test value should appear
13:57:22  X-header2: This test value should appear
13:57:22  This is not a request line for HTTP/1.1
13:57:22  
13:57:22  
13:57:22  	at B8185898.testMessageHeader(B8185898.java:133)
13:57:22  	at B8185898.main(B8185898.java:104)
13:57:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:57:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:57:22  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:57:22  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
13:57:22  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:57:22  	at java.base/java.lang.Thread.run(Thread.java:830)
13:57:22  
13:57:22  JavaTest Message: Test threw exception: java.lang.AssertionError: FAILED: expected: This /is/a/fake/status/line HTTP/2.0
13:57:22  X-header1: This test value should appear
13:57:22  X-header2: This test value should appear
13:57:22  This is not a request line for HTTP/1.1:
13:57:22  
13:57:22  
13:57:22  Received: This /is/a/fake/status/line HTTP/2.0
13:57:22  X-header1: This test value should appear
13:57:22  X-header2: This test value should appear
13:57:22  This is not a request line for HTTP/1.1
```

**Comment by johnoliver** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1357
