### ISSUE TITLE
Test failures in jdk/nio/zipfs/UpdateEntryTest.java

### ISSUE THREAD

**Issue by johnoliver** [AdoptOpenJDK/openjdk-tests#1355]
Version: 13+33
Machine: test-macincloud-macos1014-x64-1
Suit: hs sanity

https://ci.adoptopenjdk.net/job/Test_openjdk13_hs_sanity.openjdk_x86-64_mac/53/console

```
14:05:28  STDOUT:
14:05:28  [TestNG] Running:
14:05:28    jdk/nio/zipfs/UpdateEntryTest.java
14:05:28  
14:05:28  test UpdateEntryTest.test1(): failure
14:05:28  java.util.zip.ZipException: invalid END header (bad central directory offset)
14:05:28  	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1470)
14:05:28  	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1393)
14:05:28  	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1209)
14:05:28  	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1172)
14:05:28  	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719)
14:05:28  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:239)
14:05:28  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:169)
14:05:28  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:183)
14:05:28  	at UpdateEntryTest.verify(UpdateEntryTest.java:178)
14:05:28  	at UpdateEntryTest.test(UpdateEntryTest.java:168)
14:05:28  	at UpdateEntryTest.test1(UpdateEntryTest.java:136)
14:05:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:05:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:05:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:05:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
14:05:28  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
14:05:28  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
14:05:28  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
14:05:28  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
14:05:28  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
14:05:28  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
14:05:28  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
14:05:28  	at org.testng.TestRunner.run(TestRunner.java:623)
14:05:28  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
14:05:28  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
14:05:28  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
14:05:28  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
14:05:28  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
14:05:28  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
14:05:28  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
14:05:28  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
14:05:28  	at org.testng.TestNG.run(TestNG.java:1018)
14:05:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
14:05:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:05:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:05:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:05:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
14:05:28  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
14:05:28  	at java.base/java.lang.Thread.run(Thread.java:830)
14:05:28  test UpdateEntryTest.test2(): success
14:05:28  adding: storedFile.txt(in = 6) (out= 6)(stored 0%)
14:05:28  test UpdateEntryTest.testReplaceStoredEntry(): failure
14:05:28  java.util.zip.ZipException: invalid END header (bad central directory offset)
14:05:28  	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1470)
14:05:28  	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1393)
14:05:28  	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1209)
14:05:28  	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1172)
14:05:28  	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719)
14:05:28  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:239)
14:05:28  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:169)
14:05:28  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:183)
14:05:28  	at UpdateEntryTest.verify(UpdateEntryTest.java:178)
14:05:28  	at UpdateEntryTest.testReplaceStoredEntry(UpdateEntryTest.java:127)
14:05:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:05:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:05:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:05:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
14:05:28  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
14:05:28  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
14:05:28  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
14:05:28  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
14:05:28  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
14:05:28  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
14:05:28  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
14:05:28  	at org.testng.TestRunner.run(TestRunner.java:623)
14:05:28  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
14:05:28  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
14:05:28  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
14:05:28  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
14:05:28  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
14:05:28  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
14:05:28  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
14:05:28  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
14:05:28  	at org.testng.TestNG.run(TestNG.java:1018)
14:05:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
14:05:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:05:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:05:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:05:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
14:05:28  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
14:05:28  	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by johnoliver** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1357
