### ISSUE TITLE
JTReg Fail: java/net/httpclient/whitebox/ConnectionPoolTestDriver.java

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1438]
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/3cc03bc6fbbab6bbd54eecb860e007f44e14656e/test/jdk/java/net/httpclient/whitebox/ConnectionPoolTestDriver.java#L1 fails on JDK11 for openj9 and hotspot (on all generic OS's). JDK13 appears unaffected.
- Category, openjdk
- Non intermittent
- Discovered on the newly restarted JDK11 nightly builds for plinux and s390x but it appears to be a generic-all failure when ran locally and in grinders. Test has not yet been excluded.

- The test is running 3 other tests from https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/3cc03bc6fbbab6bbd54eecb860e007f44e14656e/test/jdk/java/net/httpclient/whitebox/java.net.http/jdk/internal/net/http/ConnectionPoolTest.java#L1 with the failure itself being on [LN240](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/3cc03bc6fbbab6bbd54eecb860e007f44e14656e/test/jdk/java/net/httpclient/whitebox/java.net.http/jdk/internal/net/http/ConnectionPoolTest.java#L240)

```
13:38:12  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10-201911111927)
13:38:12  Eclipse OpenJ9 VM AdoptOpenJDK (build master-e92c0cb7e, JRE 11 Linux amd64-64-Bit Compressed References 20191111_361 (JIT enabled, AOT enabled)
13:38:12  OpenJ9   - e92c0cb7e
13:38:12  OMR      - fa59bff71
13:38:12  JCL      - 5961cb4f17 based on jdk-11.0.5+10)

13:42:26  STDOUT:
13:42:26  Found connection in the pool: HttpConnectionStub: foo1:80 proxy: bar:80
13:42:26  closed: HttpConnectionStub: foo1:80 proxy: bar:80
13:42:26  EOF connection successfully closed when returned to pool
13:42:26  Keep alive connection successfully returned to pool
13:42:26  closed: HttpConnectionStub: foo1:80 proxy: bar:80
13:42:26  Close connection successfully closed when returned to pool
13:42:26  STDERR:
13:42:26  Nov 12, 2019 6:42:25 AM jdk.internal.net.http.HttpClientImpl$SelectorManager run
13:42:26  INFO: CHANNEL: HttpClient-1-SelectorManager: starting
13:42:26  Nov 12, 2019 6:42:25 AM jdk.internal.net.http.HttpConnection closeOrReturnToCache
13:42:26  INFO: MISC: Returning connection to the pool: HttpConnectionStub: foo1:80 proxy: bar:80
13:42:26  Nov 12, 2019 6:42:25 AM jdk.internal.net.http.HttpConnection closeOrReturnToCache
13:42:26  INFO: MISC: Returning connection to the pool: HttpConnectionStub: foo1:80 proxy: bar:80
13:42:26  java.lang.RuntimeException: conn1 not closed!
13:42:26  	at java.net.http/jdk.internal.net.http.ConnectionPoolTest.testCloseOrReturnToPool(ConnectionPoolTest.java:322)
13:42:26  	at java.net.http/jdk.internal.net.http.ConnectionPoolTest.main(ConnectionPoolTest.java:91)
13:42:26  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:42:26  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:42:26  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:42:26  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:42:26  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:42:26  	at java.base/java.lang.Thread.run(Thread.java:832)
```
Rerun job on x86_64 linux (JDK11-openj9): https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/java/net/httpclient/whitebox/ConnectionPoolTestDriver.java&TARGET=jdk_custom_0

**Comment by M-Davies** [comment]
Closing as per https://github.com/AdoptOpenJDK/openjdk-tests/issues/1440#issuecomment-553338131
