### ISSUE TITLE
External functional-tests can't find the testng.xml

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1487]
All testng.xml can't find after Clone TKG from it own repo when running the external functional-tests 

```
{ itercnt=1; \
17:33:47  mkdir -p "/openj9/test/TKG/../TKG/test_output_15754770608931/jit_ra_0"; \
17:33:47  cd "/openj9/test/TKG/../TKG/test_output_15754770608931/jit_ra_0"; \
17:33:47  "/opt/java/openjdk/bin/java" -Xcompressedrefs -Xmn1M -Xjit:'{*powerOfTenBI*}(count=7),disableasynccompilation,tryToInline={java/lang/String.<init>([C)V|java/lang/String.<init>([CII)V|java/lang/Object.<init>()V|java/math/BigInteger.<init>(Ljava/lang/String;)V|java/math/BigInteger.<init>(Ljava/lang/String;I)V|java/lang/Object.<init>()V|java/lang/String.length()I|java/lang/String.lengthInternal()I},dontInline={java/util/Arrays.fill([CC)V}'  \
17:33:47  		-cp "/openj9/test/TKG/../../jvmtest/TestConfig/resources:/openj9/test/TKG/../TestConfig/lib/testng.jar:/openj9/test/TKG/../TestConfig/lib/jcommander.jar:/openj9/test/TKG/../../jvmtest/functional/JIT_Test/jitt.jar" \
17:33:47  		org.testng.TestNG -d "/openj9/test/TKG/../TKG/test_output_15754770608931/jit_ra_0" "/openj9/test/TKG/../../jvmtest/functional/JIT_Test/testng.xml" \
17:33:47  		-testnames \
17:33:47  		raTest \
17:33:47  		-groups level.sanity \
17:33:47  		-excludegroups d.*.linux_x86-64_cmprssptrs,d.*.arch.x86,d.*.os.linux,d.*.bits.64,d.*.generic-all; \
17:33:47  		if [ $? -eq 0 ] ; then echo ""; echo "jit_ra_0""_PASSED"; echo ""; cd /openj9/test/TKG/..;  else echo ""; echo "jit_ra_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/openj9/test/TKG/../TKG/test_output_15754770608931/TestTargetResult";
17:33:48  java.io.FileNotFoundException: /openj9/jvmtest/functional/JIT_Test/testng.xml (No such file or directory)
17:33:48  	at java.io.FileInputStream.open(FileInputStream.java:195)
17:33:48  	at java.io.FileInputStream.<init>(FileInputStream.java:138)
17:33:48  	at org.testng.xml.Parser.parse(Parser.java:148)
17:33:48  	at org.testng.xml.Parser.parse(Parser.java:233)
17:33:48  	at org.testng.TestNG.parseSuite(TestNG.java:295)
17:33:48  	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:348)
17:33:48  	at org.testng.TestNG.initializeEverything(TestNG.java:995)
17:33:48  	at org.testng.TestNG.run(TestNG.java:1009)
17:33:48  	at org.testng.TestNG.privateMain(TestNG.java:1354)
17:33:48  	at org.testng.TestNG.main(TestNG.java:1323)
17:33:48  [TestNG] [ERROR] No test suite found. Nothing to run
17:33:48  Usage: <main class> [options] The XML suite files to run
```

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/959/console

**Comment by sophia-guo** [comment]
Close by #1565
