### ISSUE TITLE
jdk_nio: java/nio/Buffer/Chars.java failed with rror on line 132 of document  : An invalid XML character (Unicode: 0x1) was found in the CDATA section

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#150]
Failed to read test report file /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/java/nio/Buffer/Chars.testng-results.xml
org.dom4j.DocumentException: Error on line 132 of document  : An invalid XML character (Unicode: 0x1) was found in the CDATA section. Nested exception: An invalid XML character (Unicode: 0x1) was found in the CDATA section.
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.dom4j.io.SAXReader.read(SAXReader.java:343)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:132)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:302)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:244)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:175)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:154)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:126)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:132)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:107)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2750)
	at hudson.remoting.UserRequest.perform(UserRequest.java:181)
	at hudson.remoting.UserRequest.perform(UserRequest.java:52)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; lineNumber: 132; columnNumber: 121; An invalid XML character (Unicode: 0x1) was found in the CDATA section.

this doesn't seem as a test failure. Suspect is caused when junit plugin reading this xml. Exclude for now

**Comment by akolarkunnu** [comment]
@smlambert : Can you please confirm this issue is only in mac?
According to me it should be reproducible in linux also. If it is only in mac why this entry added with "generic-all" in ProblemList  :https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk_regression/ProblemList_openjdk8.txt

**Comment by akolarkunnu** [comment]
We are getting this exception while parsing /java/nio/Buffer/Chars.testng-results.xml for report generation by jenkins. This file contains some invalid characters. Same time, this particular test /java/nio/Buffer/Chars.java should have passed, see corresponding .jtr or .jtr.xlm file.

So do jenkins really want to parse this Chars.testng-results.xml file? or is it enough to parse Chars.jtr.xml file for report generation?
Please check the configuration in file https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/Jenkinsfile . Mostly if we replace **/work/**/*.xml with **/work/**/*jtr.xml, will resolve the issue.

**Comment by sophia-guo** [comment]
Yes, this is a all platforms issue. Limit *.xml to *.jtr.xml will exclude to parse Chars.testng-results.xml, works fine:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_x86-64_personal/133/

According to http://openjdk.java.net/jtreg/jtreg-hudson.html, we should collect *.jtr.xml instead of *.xml. Will update and re-enable this test.
