### ISSUE TITLE
jdk14 MBCS_Tests_datetime_formatter test failure

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#1616]
**Describe the bug**
Test MBCS_Tests_datetime_formatter fails in openj9-openjdk-jdk14 m1 build.

Failing job link: https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_special.functional_x86-64_linux/4

Output text around test failure:
```
11:41:49  ===============================================
11:41:49  Running test MBCS_Tests_datetime_formatter_0 ...
11:41:49  ===============================================
11:41:49  MBCS_Tests_datetime_formatter_0 Start Time: Thu Feb 13 04:41:48 2020 Epoch Time (ms): 1581594108805
11:41:49  "/home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
11:41:49  JVMSHRC005I No shared class caches available
11:41:49  JVMSHRC005I No shared class caches available
11:41:49  cache cleanup done
11:41:49  variation: NoOptions
11:41:49  JVM_OPTIONS: -Xcompressedrefs 
11:41:49  { itercnt=1; \
11:41:49  mkdir -p "/home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_15815938218024/MBCS_Tests_datetime_formatter_0"; \
11:41:49  cd "/home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_15815938218024/MBCS_Tests_datetime_formatter_0"; \
11:41:49  "/home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xcompressedrefs  \
11:41:49  -cp "/home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/lib/junit4.jar:/home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/datetime/datetime.jar" \
11:41:49  org.testng.TestNG -d "/home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_15815938218024/MBCS_Tests_datetime_formatter_0" "/home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/datetime/testng11.xml" \
11:41:49  -groups level.special -junit \
11:41:49  -excludegroups d.*.linux_x86-64_cmprssptrs,d.*.arch.x86,d.*.os.linux,d.*.bits.64,d.*.generic-all; \
11:41:49  if [ $? -eq 0 ] ; then echo ""; echo "MBCS_Tests_datetime_formatter_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdk-tests/TKG/..;  else echo ""; echo "MBCS_Tests_datetime_formatter_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk14_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_15815938218024/TestTargetResult";
11:41:49  ...
11:41:49  ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
11:41:49  ...
11:41:49  
11:41:50  PASSED: startOfDayTest on startOfDayTest(LocalDateTest)
11:41:50  PASSED: atTimeTest on atTimeTest(LocalDateTest)
11:41:50  PASSED: CompareToTest on CompareToTest(LocalDateTest)
11:41:50  PASSED: EqualsTest on EqualsTest(LocalDateTest)
11:41:50  PASSED: getTest on getTest(LocalDateTest)
11:41:50  PASSED: isAfterTest on isAfterTest(LocalDateTest)
11:41:50  PASSED: adjustTest on adjustTest(LocalDateTest)
11:41:50  PASSED: ofTest on ofTest(LocalTimeTest)
11:41:50  PASSED: parseTest on parseTest(LocalTimeTest)
11:41:50  PASSED: getMethodsTest on getMethodsTest(LocalTimeTest)
11:41:50  PASSED: invalidTimeTest on invalidTimeTest(LocalTimeTest)
11:41:50  PASSED: isSupportedTest on isSupportedTest(LocalTimeTest)
11:41:50  PASSED: rangeTest on rangeTest(LocalTimeTest)
11:41:50  PASSED: withTest on withTest(LocalTimeTest)
11:41:50  PASSED: trancatedToTest on trancatedToTest(LocalTimeTest)
11:41:50  PASSED: plusTest on plusTest(LocalTimeTest)
11:41:50  PASSED: minusTest on minusTest(LocalTimeTest)
11:41:50  PASSED: untilTest on untilTest(LocalTimeTest)
11:41:50  PASSED: isAfterTest on isAfterTest(LocalTimeTest)
11:41:50  PASSED: ofTest on ofTest(LocalDateTimeTest)
11:41:50  PASSED: parseTest on parseTest(LocalDateTimeTest)
11:41:50  PASSED: invalidDateTimeTest on invalidDateTimeTest(LocalDateTimeTest)
11:41:50  PASSED: getMethodsTest on getMethodsTest(LocalDateTimeTest)
11:41:50  PASSED: isSupportedTest on isSupportedTest(LocalDateTimeTest)
11:41:50  PASSED: rangeTest on rangeTest(LocalDateTimeTest)
11:41:50  PASSED: withTest on withTest(LocalDateTimeTest)
11:41:50  PASSED: trancatedToTest on trancatedToTest(LocalDateTimeTest)
11:41:50  PASSED: plusTest on plusTest(LocalDateTimeTest)
11:41:50  PASSED: minusTest on minusTest(LocalDateTimeTest)
11:41:50  PASSED: untilTest on untilTest(LocalDateTimeTest)
11:41:50  PASSED: isAfterTest on isAfterTest(LocalDateTimeTest)
11:41:50  PASSED: getAvailableChronologiesTest on getAvailableChronologiesTest(ChronoTest)
11:41:50  PASSED: ofLocaleTest on ofLocaleTest(ChronoTest)
11:41:50  PASSED: ofTest on ofTest(ZonedDateTimeTest)
11:41:50  PASSED: withZoneSameInstantTest on withZoneSameInstantTest(ZonedDateTimeTest)
11:41:50  PASSED: invalidTest on invalidTest(ZonedDateTimeTest)
11:41:50  PASSED: withZoneSameLocalTest on withZoneSameLocalTest(ZonedDateTimeTest)
11:41:50  PASSED: withLaterOffsetAtOverlapTest on withLaterOffsetAtOverlapTest(ZonedDateTimeTest)
11:41:50  PASSED: untilTest on untilTest(ZonedDateTimeTest)
11:41:50  PASSED: parseTest on parseTest(ZonedDateTimeTest)
11:41:50  PASSED: WeekOfDayTest on WeekOfDayTest(FormatTest)
11:41:50  PASSED: AlignedWeekOfDayTest on AlignedWeekOfDayTest(FormatTest)
11:41:50  PASSED: QuarterTest on QuarterTest(FormatTest)
11:41:50  PASSED: MonthTest on MonthTest(FormatTest)
11:41:50  PASSED: yearTest on yearTest(FormatterBuilderTest)
11:41:50  PASSED: DecimalStyleTest on DecimalStyleTest(FormatterBuilderTest)
11:41:50  PASSED: check on check(FileTest)
11:41:50  PASSED: modifyTest on modifyTest(FileTest)
11:41:50  PASSED: InstantTest on InstantTest(FileTest)
11:41:50  PASSED: ofTest on ofTest(JapaneseDateTest)
11:41:50  PASSED: ofInvalidTest on ofInvalidTest(JapaneseDateTest)
11:41:50  PASSED: getTest on getTest(JapaneseDateTest)
11:41:50  PASSED: getMethodsTest on getMethodsTest(JapaneseDateTest)
11:41:50  PASSED: lengthOfMonthTest on lengthOfMonthTest(JapaneseDateTest)
11:41:50  PASSED: adjustTest on adjustTest(JapaneseDateTest)
11:41:50  PASSED: untilTest on untilTest(JapaneseDateTest)
11:41:50  PASSED: periodTest on periodTest(JapaneseDateTest)
11:41:50  PASSED: minusTest on minusTest(JapaneseDateTest)
11:41:50  PASSED: minusTest2 on minusTest2(JapaneseDateTest)
11:41:50  PASSED: plusTest on plusTest(JapaneseDateTest)
11:41:50  PASSED: plusTest2 on plusTest2(JapaneseDateTest)
11:41:50  PASSED: formatterTest on formatterTest(JapaneseDateTest)
11:41:50  PASSED: formatterTest2 on formatterTest2(JapaneseDateTest)
11:41:50  PASSED: atTimeTest on atTimeTest(JapaneseDateTest)
11:41:50  PASSED: isAfterTest on isAfterTest(JapaneseDateTest)
11:41:50  PASSED: isLeapYearTest on isLeapYearTest(JapaneseDateTest)
11:41:50  PASSED: MinguoTest on MinguoTest(MinguoChronoTest)
11:41:50  PASSED: ofTest on ofTest(MinguoDateTest)
11:41:50  
11:41:50  ===============================================
11:41:50      dateTest
11:41:50      Tests run: 68, Failures: 0, Skips: 0
11:41:50  ===============================================
11:41:50  
11:41:51  PASSED: japaneseEraTest on japaneseEraTest(JapaneseChronoTest)
11:41:51  PASSED: dateTest1 on dateTest1(JapaneseChronoTest)
11:41:51  PASSED: dateInvalidTest on dateInvalidTest(JapaneseChronoTest)
11:41:51  PASSED: dateYearDayTest1 on dateYearDayTest1(JapaneseChronoTest)
11:41:51  PASSED: dateYearDayTest2 on dateYearDayTest2(JapaneseChronoTest)
11:41:51  PASSED: eraOfTest on eraOfTest(JapaneseChronoTest)
11:41:51  PASSED: erasTest on erasTest(JapaneseChronoTest)
11:41:51  PASSED: isLeapYearTest on isLeapYearTest(JapaneseChronoTest)
11:41:51  PASSED: leapTest on leapTest(JapaneseChronoTest)
11:41:51  PASSED: prolepticYearTest on prolepticYearTest(JapaneseChronoTest)
11:41:51  PASSED: rangeTest on rangeTest(JapaneseChronoTest)
11:41:51  PASSED: WeekOfDayTest on WeekOfDayTest(FormatTest_ja_jp)
11:41:51  PASSED: AlignedWeekOfDayTest on AlignedWeekOfDayTest(FormatTest_ja_jp)
11:41:51  PASSED: QuarterTest on QuarterTest(FormatTest_ja_jp)
11:41:51  PASSED: MonthTest on MonthTest(FormatTest_ja_jp)
11:41:51  PASSED: WeekOfDayTest on WeekOfDayTest(FormatTest_ko_kr)
11:41:51  PASSED: AlignedWeekOfDayTest on AlignedWeekOfDayTest(FormatTest_ko_kr)
11:41:51  PASSED: QuarterTest on QuarterTest(FormatTest_ko_kr)
11:41:51  PASSED: MonthTest on MonthTest(FormatTest_ko_kr)
11:41:51  PASSED: WeekOfDayTest on WeekOfDayTest(FormatTest_zh_tw)
11:41:51  PASSED: AlignedWeekOfDayTest on AlignedWeekOfDayTest(FormatTest_zh_tw)
11:41:51  PASSED: MonthTest on MonthTest(FormatTest_zh_tw)
11:41:51  PASSED: WeekOfDayTest on WeekOfDayTest(FormatTest_zh_cn)
11:41:51  PASSED: AlignedWeekOfDayTest on AlignedWeekOfDayTest(FormatTest_zh_cn)
11:41:51  PASSED: QuarterTest on QuarterTest(FormatTest_zh_cn)
11:41:51  PASSED: MonthTest on MonthTest(FormatTest_zh_cn)
11:41:51  PASSED: yearTest on yearTest(FormatterBuilderTest_ja_jp)
11:41:51  FAILED: QuarterTest on QuarterTest(FormatTest_zh_tw)
11:41:51  org.junit.ComparisonFailure: expected:<1 01 [1] ?1? 1> but was:<1 01 [?1?] ?1? 1>
11:41:51  	at org.junit.Assert.assertEquals(Assert.java:125)
11:41:51  	at org.junit.Assert.assertEquals(Assert.java:147)
11:41:51  	at FormatTest_zh_tw.QuarterTest(FormatTest_zh_tw.java:113)
11:41:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:41:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:41:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:41:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
11:41:51  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
11:41:51  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
11:41:51  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
11:41:51  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
11:41:51  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
11:41:51  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
11:41:51  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
11:41:51  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
11:41:51  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
11:41:51  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
11:41:51  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
11:41:51  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
11:41:51  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
11:41:51  	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
11:41:51  	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
11:41:51  	at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:82)
11:41:51  	at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:70)
11:41:51  	at org.testng.TestRunner$1.run(TestRunner.java:570)
11:41:51  	at org.testng.TestRunner.runJUnitWorkers(TestRunner.java:717)
11:41:51  	at org.testng.TestRunner.privateRunJUnit(TestRunner.java:601)
11:41:51  	at org.testng.TestRunner.run(TestRunner.java:502)
11:41:51  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
11:41:51  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
11:41:51  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
11:41:51  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
11:41:51  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
11:41:51  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
11:41:51  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
11:41:51  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
11:41:51  	at org.testng.TestNG.runSuites(TestNG.java:1049)
11:41:51  	at org.testng.TestNG.run(TestNG.java:1017)
11:41:51  	at org.testng.TestNG.privateMain(TestNG.java:1354)
11:41:51  	at org.testng.TestNG.main(TestNG.java:1323)
11:41:51  
11:41:51  
11:41:51  ===============================================
11:41:51      dateTest11
11:41:51      Tests run: 28, Failures: 1, Skips: 0
11:41:51  ===============================================
```

**To Reproduce**
Submit job https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=14&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=x86-64_linux&TARGET=MBCS_Tests_datetime_formatter_0

**Expected behavior**
Test should pass (at least it passes on jdk11).

**Screenshots**

**Additional context**
There are not yet any results from jdk14 hotspot build tests to say whether the issue is A clear and concise description of what you expected to happen.

**Comment by lumpfish** [comment]
Confirmed that the test also fails with jdk14 hotspot builds.

**Comment by smlambert** [comment]
FYI @KKES335
