### ISSUE TITLE
jdk14 MBCS_Tests_datetime test failure

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#1622]
**Describe the bug**
Describe the bug
Test MBCS_Tests_datetime fails o=in jdk14 builds.

Failing job link: https://ci.adoptopenjdk.net/job/Test_openjdk14_hs_special.functional_x86-64_linux/2/consoleFull

Output text around test failure:
```
19:31:39  ===============================================
19:31:39  Running test MBCS_Tests_datetime_0 ...
19:31:39  ===============================================
19:31:39  MBCS_Tests_datetime_0 Start Time: Thu Feb 13 19:31:38 2020 Epoch Time (ms): 1581622298685
19:31:39  Nothing to be done for setup.
19:31:39  variation: NoOptions
19:31:39  JVM_OPTIONS:  
19:31:39  { itercnt=1; \
19:31:39  mkdir -p "/home/jenkins/workspace/Test_openjdk14_hs_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_15816219649353/MBCS_Tests_datetime_0"; \
19:31:39  cd "/home/jenkins/workspace/Test_openjdk14_hs_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_15816219649353/MBCS_Tests_datetime_0"; \
19:31:39  "/home/jenkins/workspace/Test_openjdk14_hs_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java"   \
19:31:39  -cp "/home/jenkins/workspace/Test_openjdk14_hs_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk14_hs_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk14_hs_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk14_hs_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/lib/junit4.jar:/home/jenkins/workspace/Test_openjdk14_hs_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/datetime/datetime.jar" \
19:31:39  org.testng.TestNG -d "/home/jenkins/workspace/Test_openjdk14_hs_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_15816219649353/MBCS_Tests_datetime_0" "/home/jenkins/workspace/Test_openjdk14_hs_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/datetime/testng.xml" \
19:31:39  -groups level.special -junit \
19:31:39  -excludegroups d.*.linux_x86-64_cmprssptrs,d.*.arch.x86,d.*.os.linux,d.*.bits.64,d.*.generic-all; \
19:31:39  if [ $? -eq 0 ] ; then echo ""; echo "MBCS_Tests_datetime_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk14_hs_special.functional_x86-64_linux/openjdk-tests/TKG/..;  else echo ""; echo "MBCS_Tests_datetime_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk14_hs_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_15816219649353/TestTargetResult";
19:31:39  ...
19:31:39  ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
19:31:39  ...
19:31:39  
19:31:40  PASSED: getTest on getTest(LocalDateTest)
19:31:40  PASSED: EqualsTest on EqualsTest(LocalDateTest)
19:31:40  PASSED: isAfterTest on isAfterTest(LocalDateTest)
19:31:40  PASSED: adjustTest on adjustTest(LocalDateTest)
19:31:40  PASSED: startOfDayTest on startOfDayTest(LocalDateTest)
19:31:40  PASSED: atTimeTest on atTimeTest(LocalDateTest)
19:31:40  PASSED: CompareToTest on CompareToTest(LocalDateTest)
19:31:40  PASSED: ofTest on ofTest(LocalTimeTest)
19:31:40  PASSED: parseTest on parseTest(LocalTimeTest)
19:31:40  PASSED: getMethodsTest on getMethodsTest(LocalTimeTest)
19:31:40  PASSED: invalidTimeTest on invalidTimeTest(LocalTimeTest)
19:31:40  PASSED: isSupportedTest on isSupportedTest(LocalTimeTest)
19:31:40  PASSED: rangeTest on rangeTest(LocalTimeTest)
19:31:40  PASSED: withTest on withTest(LocalTimeTest)
19:31:40  PASSED: trancatedToTest on trancatedToTest(LocalTimeTest)
19:31:40  PASSED: plusTest on plusTest(LocalTimeTest)
19:31:40  PASSED: minusTest on minusTest(LocalTimeTest)
19:31:40  PASSED: untilTest on untilTest(LocalTimeTest)
19:31:40  PASSED: isAfterTest on isAfterTest(LocalTimeTest)
19:31:40  PASSED: ofTest on ofTest(LocalDateTimeTest)
19:31:40  PASSED: parseTest on parseTest(LocalDateTimeTest)
19:31:40  PASSED: getMethodsTest on getMethodsTest(LocalDateTimeTest)
19:31:40  PASSED: isSupportedTest on isSupportedTest(LocalDateTimeTest)
19:31:40  PASSED: rangeTest on rangeTest(LocalDateTimeTest)
19:31:40  PASSED: withTest on withTest(LocalDateTimeTest)
19:31:40  PASSED: trancatedToTest on trancatedToTest(LocalDateTimeTest)
19:31:40  PASSED: plusTest on plusTest(LocalDateTimeTest)
19:31:40  PASSED: minusTest on minusTest(LocalDateTimeTest)
19:31:40  PASSED: untilTest on untilTest(LocalDateTimeTest)
19:31:40  PASSED: invalidDateTimeTest on invalidDateTimeTest(LocalDateTimeTest)
19:31:40  PASSED: isAfterTest on isAfterTest(LocalDateTimeTest)
19:31:40  PASSED: getAvailableChronologiesTest on getAvailableChronologiesTest(ChronoTest)
19:31:40  PASSED: ofLocaleTest on ofLocaleTest(ChronoTest)
19:31:40  PASSED: ofTest on ofTest(ZonedDateTimeTest)
19:31:40  PASSED: parseTest on parseTest(ZonedDateTimeTest)
19:31:40  PASSED: untilTest on untilTest(ZonedDateTimeTest)
19:31:40  PASSED: withZoneSameInstantTest on withZoneSameInstantTest(ZonedDateTimeTest)
19:31:40  PASSED: invalidTest on invalidTest(ZonedDateTimeTest)
19:31:40  PASSED: withZoneSameLocalTest on withZoneSameLocalTest(ZonedDateTimeTest)
19:31:40  PASSED: withLaterOffsetAtOverlapTest on withLaterOffsetAtOverlapTest(ZonedDateTimeTest)
19:31:40  PASSED: WeekOfDayTest on WeekOfDayTest(FormatTest)
19:31:40  PASSED: AlignedWeekOfDayTest on AlignedWeekOfDayTest(FormatTest)
19:31:40  PASSED: QuarterTest on QuarterTest(FormatTest)
19:31:40  PASSED: MonthTest on MonthTest(FormatTest)
19:31:40  PASSED: yearTest on yearTest(FormatterBuilderTest)
19:31:40  PASSED: DecimalStyleTest on DecimalStyleTest(FormatterBuilderTest)
19:31:40  PASSED: check on check(FileTest)
19:31:40  PASSED: InstantTest on InstantTest(FileTest)
19:31:40  PASSED: getTest on getTest(JapaneseDateTest)
19:31:40  PASSED: ofTest on ofTest(JapaneseDateTest)
19:31:40  PASSED: getMethodsTest on getMethodsTest(JapaneseDateTest)
19:31:40  PASSED: plusTest on plusTest(JapaneseDateTest)
19:31:40  PASSED: minusTest on minusTest(JapaneseDateTest)
19:31:40  PASSED: untilTest on untilTest(JapaneseDateTest)
19:31:40  PASSED: isAfterTest on isAfterTest(JapaneseDateTest)
19:31:40  PASSED: adjustTest on adjustTest(JapaneseDateTest)
19:31:40  PASSED: atTimeTest on atTimeTest(JapaneseDateTest)
19:31:40  PASSED: ofInvalidTest on ofInvalidTest(JapaneseDateTest)
19:31:40  PASSED: lengthOfMonthTest on lengthOfMonthTest(JapaneseDateTest)
19:31:40  PASSED: periodTest on periodTest(JapaneseDateTest)
19:31:40  PASSED: minusTest2 on minusTest2(JapaneseDateTest)
19:31:40  PASSED: plusTest2 on plusTest2(JapaneseDateTest)
19:31:40  PASSED: formatterTest on formatterTest(JapaneseDateTest)
19:31:40  PASSED: formatterTest2 on formatterTest2(JapaneseDateTest)
19:31:40  PASSED: isLeapYearTest on isLeapYearTest(JapaneseDateTest)
19:31:40  PASSED: MinguoTest on MinguoTest(MinguoChronoTest)
19:31:40  PASSED: ofTest on ofTest(MinguoDateTest)
19:31:40  FAILED: modifyTest on modifyTest(FileTest)
19:31:40  java.lang.AssertionError
19:31:40  	at org.junit.Assert.fail(Assert.java:92)
19:31:40  	at org.junit.Assert.assertTrue(Assert.java:43)
19:31:40  	at org.junit.Assert.assertFalse(Assert.java:68)
19:31:40  	at org.junit.Assert.assertFalse(Assert.java:79)
19:31:40  	at FileTest.modifyTest(FileTest.java:99)
19:31:40  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:31:40  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:31:40  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:31:40  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
19:31:40  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
19:31:40  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
19:31:40  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
19:31:40  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
19:31:40  	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
19:31:40  	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
19:31:40  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
19:31:40  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
19:31:40  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
19:31:40  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
19:31:40  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
19:31:40  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
19:31:40  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
19:31:40  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
19:31:40  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
19:31:40  	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
19:31:40  	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
19:31:40  	at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:82)
19:31:40  	at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:70)
19:31:40  	at org.testng.TestRunner$1.run(TestRunner.java:570)
19:31:40  	at org.testng.TestRunner.runJUnitWorkers(TestRunner.java:717)
19:31:40  	at org.testng.TestRunner.privateRunJUnit(TestRunner.java:601)
19:31:40  	at org.testng.TestRunner.run(TestRunner.java:502)
19:31:40  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
19:31:40  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
19:31:40  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
19:31:40  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
19:31:40  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
19:31:40  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
19:31:40  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
19:31:40  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
19:31:40  	at org.testng.TestNG.runSuites(TestNG.java:1049)
19:31:40  	at org.testng.TestNG.run(TestNG.java:1017)
19:31:40  	at org.testng.TestNG.privateMain(TestNG.java:1354)
19:31:40  	at org.testng.TestNG.main(TestNG.java:1323)
19:31:40  
19:31:40  
19:31:40  ===============================================
19:31:40      dateTest
19:31:40      Tests run: 68, Failures: 1, Skips: 0
19:31:40  ===============================================
19:31:40  
19:31:40  
19:31:40  ===============================================
19:31:40  DateTime
19:31:40  Total tests run: 68, Failures: 1, Skips: 0
19:31:40  ===============================================
19:31:40  
19:31:40  
19:31:40  MBCS_Tests_datetime_0_FAILED
```

**To Reproduce**
Submit job https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=14&JDK_IMPL=hotspot&BUILD_LIST=functional&PLATFORM=x86-64_linux&TARGET=MBCS_Tests_datetime_0

**Expected behavior**
Test should pass (at least it passes on jdk11).

**Screenshots**

**Additional context**
Fails on both hotspot and openj9 jdk14 builds.

**Comment by smlambert** [comment]
FYI @KKES335

**Comment by smlambert** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-tests/pull/1624
