### ISSUE TITLE
JTReg Timeout on arm32: java/security/KeyPairGenerator/SolarisShortDSA.java

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1630]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1548

- test category, sanity.openjdk.jdk_security1_0 
- OS/architecture, aarch32_linux
- public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced: 
```
11:41:14  openjdk version "1.8.0_232"
11:41:14  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
11:41:14  OpenJDK Zero VM (AdoptOpenJDK)(build 25.232-b09, interpreted mode)
```
- Created via non-JIT VM for the JDK8-hotspot-arm32 GA release (see linked issue)
- Known to cause timeouts on zlinux #1051 

```
12:17:26  Full thread dump OpenJDK Zero VM (25.232-b09 interpreted mode):
12:17:26  
12:17:26  "Attach Listener" #66 daemon prio=9 os_prio=0 tid=0x92e2eb10 nid=0x7eda runnable [0x00000000]
12:17:26     java.lang.Thread.State: RUNNABLE
12:17:26  
12:17:26  "AgentVMThread" #65 prio=5 os_prio=0 tid=0x90932058 nid=0x7b2b runnable [0x905fe000]
12:17:26     java.lang.Thread.State: RUNNABLE
12:17:26  	at java.math.BigInteger.implMulAdd(BigInteger.java:3047)
12:17:26  	at java.math.BigInteger.mulAdd(BigInteger.java:3018)
12:17:26  	at java.math.BigInteger.montReduce(BigInteger.java:2967)
12:17:26  	at java.math.BigInteger.implMontgomerySquare(BigInteger.java:2714)
12:17:26  	at java.math.BigInteger.montgomerySquare(BigInteger.java:2672)
12:17:26  	at java.math.BigInteger.oddModPow(BigInteger.java:2940)
12:17:26  	at java.math.BigInteger.modPow(BigInteger.java:2603)
12:17:26  	at sun.security.provider.DSAKeyPairGenerator.generateY(DSAKeyPairGenerator.java:209)
12:17:26  	at sun.security.provider.DSAKeyPairGenerator.generateKeyPair(DSAKeyPairGenerator.java:162)
12:17:26  	at sun.security.provider.DSAKeyPairGenerator.generateKeyPair(DSAKeyPairGenerator.java:155)
12:17:26  	at sun.security.provider.DSAKeyPairGenerator$Current.generateKeyPair(DSAKeyPairGenerator.java:213)
12:17:26  	at SolarisShortDSA.main(SolarisShortDSA.java:40)
12:17:26  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:17:26  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:17:26  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:17:26  	at java.lang.reflect.Method.invoke(Method.java:498)
12:17:26  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
12:17:26  	at java.lang.Thread.run(Thread.java:748)
12:17:26  
12:17:26  "pool-1-thread-1" #6 daemon prio=5 os_prio=0 tid=0x9290ba40 nid=0x7630 waiting on condition [0x90bfd000]
12:17:26     java.lang.Thread.State: TIMED_WAITING (parking)
12:17:26  	at sun.misc.Unsafe.park(Native Method)
12:17:26  	- parking to wait for  <0x9ef1c068> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
12:17:26  	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
12:17:26  	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
12:17:26  	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
12:17:26  	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
12:17:26  	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
12:17:26  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
12:17:26  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:17:26  	at java.lang.Thread.run(Thread.java:748)
12:17:26  
12:17:26  "Service Thread" #5 daemon prio=9 os_prio=0 tid=0xb6680118 nid=0x7625 runnable [0x00000000]
12:17:26     java.lang.Thread.State: RUNNABLE
12:17:26  
12:17:26  "Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0xb667efc8 nid=0x7624 runnable [0x00000000]
12:17:26     java.lang.Thread.State: RUNNABLE
12:17:26  
12:17:26  "Finalizer" #3 daemon prio=8 os_prio=0 tid=0xb66639f0 nid=0x7623 in Object.wait() [0x937fe000]
12:17:26     java.lang.Thread.State: WAITING (on object monitor)
12:17:26  	at java.lang.Object.wait(Native Method)
12:17:26  	- waiting on <0x9ef1c5b0> (a java.lang.ref.ReferenceQueue$Lock)
12:17:26  	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
12:17:26  	- locked <0x9ef1c5b0> (a java.lang.ref.ReferenceQueue$Lock)
12:17:26  	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
12:17:26  	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)
12:17:26  
12:17:26  "Reference Handler" #2 daemon prio=10 os_prio=0 tid=0xb6662170 nid=0x7622 in Object.wait() [0x93afe000]
12:17:26     java.lang.Thread.State: WAITING (on object monitor)
12:17:26  	at java.lang.Object.wait(Native Method)
12:17:26  	- waiting on <0x9ef1c750> (a java.lang.ref.Reference$Lock)
12:17:26  	at java.lang.Object.wait(Object.java:502)
12:17:26  	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
12:17:26  	- locked <0x9ef1c750> (a java.lang.ref.Reference$Lock)
12:17:26  	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
12:17:26  
12:17:26  "main" #1 prio=5 os_prio=0 tid=0xb6607410 nid=0x761e in Object.wait() [0xb694a000]
12:17:26     java.lang.Thread.State: WAITING (on object monitor)
12:17:26  	at java.lang.Object.wait(Native Method)
12:17:26  	- waiting on <0x9f8bebe0> (a java.lang.Thread)
12:17:26  	at java.lang.Thread.join(Thread.java:1252)
12:17:26  	- locked <0x9f8bebe0> (a java.lang.Thread)
12:17:26  	at java.lang.Thread.join(Thread.java:1326)
12:17:26  	at com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:184)
12:17:26  	at com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:257)
12:17:26  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:193)
12:17:26  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:65)
12:17:26  
12:17:26  "VM Thread" os_prio=0 tid=0xb665c900 nid=0x7621 runnable 
12:17:26  
12:17:26  "VM Periodic Task Thread" os_prio=0 tid=0xb6681818 nid=0x7626 waiting on condition 
12:17:26  
12:17:26  JNI global references: 197
12:17:26  
12:17:26  --- Timeout information end.
```

**Comment by smlambert** [comment]
Not seeing this failure reproduce in Grinders (example: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4265) so will close. If it does reproduce on a particular machine, it should be raised as an infra issue (and machine should have ci.role.test tag removed until it can be corrected).

These tests were not excluded using the correct OS-ARCH name (used linux-aarch32 instead of linux-arm), entries in problem lists will be removed as part of #2018.
