### ISSUE TITLE
JTReg Timeout on arm32: java/security/MessageDigest/TestDigestIOStream.java

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1632]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1548

- test category, sanity.openjdk.jdk_security1_0 
- OS/architecture, aarch32_linux
- public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced: 
```
11:41:14  openjdk version "1.8.0_232"
11:41:14  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
11:41:14  OpenJDK Zero VM (AdoptOpenJDK)(build 25.232-b09, interpreted mode)
```
- Created via non-JIT VM for the JDK8-hotspot-arm32 GA release (see linked issue)
- Known to cause timeouts on zlinux #1051 

```
13:37:32  Full thread dump OpenJDK Zero VM (25.232-b09 interpreted mode):
13:37:32  
13:37:32  "Attach Listener" #12 daemon prio=9 os_prio=0 tid=0x92d00880 nid=0x148a waiting on condition [0x00000000]
13:37:32     java.lang.Thread.State: RUNNABLE
13:37:32  
13:37:32  "AgentVMThread" #11 prio=5 os_prio=0 tid=0x92918260 nid=0x10dd runnable [0x905fe000]
13:37:32     java.lang.Thread.State: RUNNABLE
13:37:32  	at sun.security.provider.MD2.implCompress(MD2.java:104)
13:37:32  	at sun.security.provider.DigestBase.implCompressMultiBlock0(DigestBase.java:147)
13:37:32  	at sun.security.provider.DigestBase.implCompressMultiBlock(DigestBase.java:142)
13:37:32  	at sun.security.provider.DigestBase.engineUpdate(DigestBase.java:129)
13:37:32  	at java.security.MessageDigest$Delegate.engineUpdate(MessageDigest.java:584)
13:37:32  	at java.security.MessageDigest.update(MessageDigest.java:335)
13:37:32  	at java.security.MessageDigest.digest(MessageDigest.java:410)
13:37:32  	at TestDigestIOStream.testDigestOnOff(TestDigestIOStream.java:208)
13:37:32  	at TestDigestIOStream.run(TestDigestIOStream.java:89)
13:37:32  	at TestDigestIOStream.main(TestDigestIOStream.java:60)
13:37:32  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:37:32  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:37:32  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:37:32  	at java.lang.reflect.Method.invoke(Method.java:498)
13:37:32  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
13:37:32  	at java.lang.Thread.run(Thread.java:748)
13:37:32  
13:37:32  "pool-1-thread-1" #6 daemon prio=5 os_prio=0 tid=0x9290ba40 nid=0xdc9 waiting on condition [0x90bfd000]
13:37:32     java.lang.Thread.State: TIMED_WAITING (parking)
13:37:32  	at sun.misc.Unsafe.park(Native Method)
13:37:32  	- parking to wait for  <0x9ef1c660> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
13:37:32  	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
13:37:32  	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
13:37:32  	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
13:37:32  	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
13:37:32  	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
13:37:32  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
13:37:32  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13:37:32  	at java.lang.Thread.run(Thread.java:748)
13:37:32  
13:37:32  "Service Thread" #5 daemon prio=9 os_prio=0 tid=0xb6680118 nid=0xdc7 runnable [0x00000000]
13:37:32     java.lang.Thread.State: RUNNABLE
13:37:32  
13:37:32  "Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0xb667efc8 nid=0xdc6 runnable [0x00000000]
13:37:32     java.lang.Thread.State: RUNNABLE
13:37:32  
13:37:32  "Finalizer" #3 daemon prio=8 os_prio=0 tid=0xb66639f0 nid=0xdc5 in Object.wait() [0x936fe000]
13:37:32     java.lang.Thread.State: WAITING (on object monitor)
13:37:32  	at java.lang.Object.wait(Native Method)
13:37:32  	- waiting on <0x9ef1cba8> (a java.lang.ref.ReferenceQueue$Lock)
13:37:32  	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
13:37:32  	- locked <0x9ef1cba8> (a java.lang.ref.ReferenceQueue$Lock)
13:37:32  	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
13:37:32  	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)
13:37:32  
13:37:32  "Reference Handler" #2 daemon prio=10 os_prio=0 tid=0xb6662170 nid=0xdc4 in Object.wait() [0x939fe000]
13:37:32     java.lang.Thread.State: WAITING (on object monitor)
13:37:32  	at java.lang.Object.wait(Native Method)
13:37:32  	- waiting on <0x9ef1cd48> (a java.lang.ref.Reference$Lock)
13:37:32  	at java.lang.Object.wait(Object.java:502)
13:37:32  	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
13:37:32  	- locked <0x9ef1cd48> (a java.lang.ref.Reference$Lock)
13:37:32  	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
13:37:32  
13:37:32  "main" #1 prio=5 os_prio=0 tid=0xb6607410 nid=0xdc2 in Object.wait() [0xb688f000]
13:37:32     java.lang.Thread.State: WAITING (on object monitor)
13:37:32  	at java.lang.Object.wait(Native Method)
13:37:32  	- waiting on <0x9f4b0268> (a java.lang.Thread)
13:37:32  	at java.lang.Thread.join(Thread.java:1252)
13:37:32  	- locked <0x9f4b0268> (a java.lang.Thread)
13:37:32  	at java.lang.Thread.join(Thread.java:1326)
13:37:32  	at com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:184)
13:37:32  	at com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:257)
13:37:32  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:193)
13:37:32  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:65)
13:37:32  
13:37:32  "VM Thread" os_prio=0 tid=0xb665c900 nid=0xdc3 runnable 
13:37:32  
13:37:32  "VM Periodic Task Thread" os_prio=0 tid=0xb6681818 nid=0xdc8 waiting on condition 
13:37:32  
13:37:32  JNI global references: 221
13:37:32  
13:37:32  --- Timeout information end.
```

**Comment by smlambert** [comment]
Not seeing this failure reproduce in Grinders (example: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4265) so will close. If it does reproduce on a particular machine, it should be raised as an infra issue (and machine should have ci.role.test tag removed until it can be corrected).

These tests were not excluded using the correct OS-ARCH name (used linux-aarch32 instead of linux-arm), entries in problem lists will be removed as part of #2018.
