### ISSUE TITLE
JTReg Timeout on arm32: java/security/MessageDigest/TestSameLength.java

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1633]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1548

- test category, sanity.openjdk.jdk_security1_0 
- OS/architecture, aarch32_linux
- public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced: 
```
11:41:14  openjdk version "1.8.0_232"
11:41:14  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
11:41:14  OpenJDK Zero VM (AdoptOpenJDK)(build 25.232-b09, interpreted mode)
```
- Created via non-JIT VM for the JDK8-hotspot-arm32 GA release (see linked issue)

```
13:53:34  Full thread dump OpenJDK Zero VM (25.232-b09 interpreted mode):
13:53:34  
13:53:34  "Attach Listener" #8 daemon prio=9 os_prio=0 tid=0x92e00720 nid=0x184c waiting on condition [0x00000000]
13:53:34     java.lang.Thread.State: RUNNABLE
13:53:34  
13:53:34  "AgentVMThread" #7 prio=5 os_prio=0 tid=0x90839a48 nid=0x149c runnable [0x904fe000]
13:53:34     java.lang.Thread.State: RUNNABLE
13:53:34  	at sun.security.provider.SHA2.lf_S(SHA2.java:155)
13:53:34  	at sun.security.provider.SHA2.lf_sigma1(SHA2.java:173)
13:53:34  	at sun.security.provider.SHA2.implCompress0(SHA2.java:235)
13:53:34  	at sun.security.provider.SHA2.implCompress(SHA2.java:199)
13:53:34  	at sun.security.provider.DigestBase.implCompressMultiBlock0(DigestBase.java:147)
13:53:34  	at sun.security.provider.DigestBase.implCompressMultiBlock(DigestBase.java:142)
13:53:34  	at sun.security.provider.DigestBase.engineUpdate(DigestBase.java:129)
13:53:34  	at java.security.MessageDigest$Delegate.engineUpdate(MessageDigest.java:584)
13:53:34  	at java.security.MessageDigest.update(MessageDigest.java:335)
13:53:34  	at TestSameLength$UpdateMethod$2.updateDigest(TestSameLength.java:116)
13:53:34  	at TestSameLength.runTest(TestSameLength.java:84)
13:53:34  	at TestSameLength.run(TestSameLength.java:60)
13:53:34  	at TestSameLength.main(TestSameLength.java:42)
13:53:34  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:53:34  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:53:34  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:53:34  	at java.lang.reflect.Method.invoke(Method.java:498)
13:53:34  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
13:53:34  	at java.lang.Thread.run(Thread.java:748)
13:53:34  
13:53:34  "pool-1-thread-1" #6 daemon prio=5 os_prio=0 tid=0x90b0ba40 nid=0x1497 waiting on condition [0x90afe000]
13:53:34     java.lang.Thread.State: TIMED_WAITING (parking)
13:53:34  	at sun.misc.Unsafe.park(Native Method)
13:53:34  	- parking to wait for  <0x9efb8a78> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
13:53:34  	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
13:53:34  	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
13:53:34  	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
13:53:34  	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
13:53:34  	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
13:53:34  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
13:53:34  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13:53:34  	at java.lang.Thread.run(Thread.java:748)
13:53:34  
13:53:34  "Service Thread" #5 daemon prio=9 os_prio=0 tid=0xb6680118 nid=0x1493 runnable [0x00000000]
13:53:34     java.lang.Thread.State: RUNNABLE
13:53:34  
13:53:34  "Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0xb667efc8 nid=0x1492 runnable [0x00000000]
13:53:34     java.lang.Thread.State: RUNNABLE
13:53:34  
13:53:34  "Finalizer" #3 daemon prio=8 os_prio=0 tid=0xb66639f0 nid=0x1491 in Object.wait() [0x937fe000]
13:53:34     java.lang.Thread.State: WAITING (on object monitor)
13:53:34  	at java.lang.Object.wait(Native Method)
13:53:34  	- waiting on <0x9efb8fe0> (a java.lang.ref.ReferenceQueue$Lock)
13:53:34  	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
13:53:34  	- locked <0x9efb8fe0> (a java.lang.ref.ReferenceQueue$Lock)
13:53:34  	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
13:53:34  	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)
13:53:34  
13:53:34  "Reference Handler" #2 daemon prio=10 os_prio=0 tid=0xb6662170 nid=0x1490 in Object.wait() [0x93afe000]
13:53:34     java.lang.Thread.State: WAITING (on object monitor)
13:53:34  	at java.lang.Object.wait(Native Method)
13:53:34  	- waiting on <0x9efb9180> (a java.lang.ref.Reference$Lock)
13:53:34  	at java.lang.Object.wait(Object.java:502)
13:53:34  	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
13:53:34  	- locked <0x9efb9180> (a java.lang.ref.Reference$Lock)
13:53:34  	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
13:53:34  
13:53:34  "main" #1 prio=5 os_prio=0 tid=0xb6607410 nid=0x148e in Object.wait() [0xb691e000]
13:53:34     java.lang.Thread.State: WAITING (on object monitor)
13:53:34  	at java.lang.Object.wait(Native Method)
13:53:34  	- waiting on <0x9f50f390> (a java.lang.Thread)
13:53:34  	at java.lang.Thread.join(Thread.java:1252)
13:53:34  	- locked <0x9f50f390> (a java.lang.Thread)
13:53:34  	at java.lang.Thread.join(Thread.java:1326)
13:53:34  	at com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:184)
13:53:34  	at com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:257)
13:53:34  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:193)
13:53:34  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:65)
13:53:34  
13:53:34  "VM Thread" os_prio=0 tid=0xb665c900 nid=0x148f runnable 
13:53:34  
13:53:34  "VM Periodic Task Thread" os_prio=0 tid=0xb6681818 nid=0x1494 waiting on condition 
13:53:34  
13:53:34  JNI global references: 11
13:53:34  
13:53:34  --- Timeout information end.
```

**Comment by smlambert** [comment]
Not seeing this failure reproduce in Grinders (example: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4265) so will close. If it does reproduce on a particular machine, it should be raised as an infra issue (and machine should have ci.role.test tag removed until it can be corrected).

These tests were not excluded using the correct OS-ARCH name (used linux-aarch32 instead of linux-arm), entries in problem lists will be removed as part of #2018.
