### ISSUE TITLE
JTReg Timeout on arm32: java/security/SignedObject/Chain.java

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1634]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1548

- test category, sanity.openjdk.jdk_security1_0 
- OS/architecture, aarch32_linux
- public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced: 
```
11:41:14  openjdk version "1.8.0_232"
11:41:14  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
11:41:14  OpenJDK Zero VM (AdoptOpenJDK)(build 25.232-b09, interpreted mode)
```
- Created via non-JIT VM for the JDK8-hotspot-arm32 GA release (see linked issue)

```
14:18:37  Full thread dump OpenJDK Zero VM (25.232-b09 interpreted mode):
14:18:37  
14:18:37  "Attach Listener" #18 daemon prio=9 os_prio=0 tid=0x92d08578 nid=0x20f9 runnable [0x00000000]
14:18:37     java.lang.Thread.State: RUNNABLE
14:18:37  
14:18:37  "AgentVMThread" #17 prio=5 os_prio=0 tid=0x90aa1148 nid=0x1d44 runnable [0x903fd000]
14:18:37     java.lang.Thread.State: RUNNABLE
14:18:37  	at java.math.BigInteger.implMulAdd(BigInteger.java:3047)
14:18:37  	at java.math.BigInteger.mulAdd(BigInteger.java:3018)
14:18:37  	at java.math.BigInteger.montReduce(BigInteger.java:2967)
14:18:37  	at java.math.BigInteger.implMontgomerySquare(BigInteger.java:2714)
14:18:37  	at java.math.BigInteger.montgomerySquare(BigInteger.java:2672)
14:18:37  	at java.math.BigInteger.oddModPow(BigInteger.java:2940)
14:18:37  	at java.math.BigInteger.modPow(BigInteger.java:2603)
14:18:37  	at java.math.BigInteger.passesMillerRabin(BigInteger.java:1036)
14:18:37  	at java.math.BigInteger.primeToCertainty(BigInteger.java:892)
14:18:37  	at java.math.BitSieve.retrieve(BitSieve.java:203)
14:18:37  	at java.math.BigInteger.largePrime(BigInteger.java:761)
14:18:37  	at java.math.BigInteger.probablePrime(BigInteger.java:699)
14:18:37  	at sun.security.rsa.RSAKeyPairGenerator.generateKeyPair(RSAKeyPairGenerator.java:133)
14:18:37  	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:703)
14:18:37  	at java.security.KeyPairGenerator.genKeyPair(KeyPairGenerator.java:470)
14:18:37  	at Chain.runTest(Chain.java:161)
14:18:37  	at Chain.lambda$main$0(Chain.java:128)
14:18:37  	at Chain$$Lambda$2/17868469.test(Unknown Source)
14:18:37  	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
14:18:37  	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
14:18:37  	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
14:18:37  	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
14:18:37  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
14:18:37  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
14:18:37  	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
14:18:37  	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
14:18:37  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
14:18:37  	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:521)
14:18:37  	at Chain.main(Chain.java:128)
14:18:37  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:18:37  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:18:37  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:18:37  	at java.lang.reflect.Method.invoke(Method.java:498)
14:18:37  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
14:18:37  	at java.lang.Thread.run(Thread.java:748)
14:18:37  
14:18:37  "pool-1-thread-1" #6 daemon prio=5 os_prio=0 tid=0x90a0ba40 nid=0x1c74 waiting on condition [0x909fe000]
14:18:37     java.lang.Thread.State: TIMED_WAITING (parking)
14:18:37  	at sun.misc.Unsafe.park(Native Method)
14:18:37  	- parking to wait for  <0x9ef1c860> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
14:18:37  	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
14:18:37  	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
14:18:37  	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
14:18:37  	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
14:18:37  	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
14:18:37  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
14:18:37  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:18:37  	at java.lang.Thread.run(Thread.java:748)
14:18:37  
14:18:37  "Service Thread" #5 daemon prio=9 os_prio=0 tid=0xb6580118 nid=0x1c70 runnable [0x00000000]
14:18:37     java.lang.Thread.State: RUNNABLE
14:18:37  
14:18:37  "Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0xb657efc8 nid=0x1c6f runnable [0x00000000]
14:18:37     java.lang.Thread.State: RUNNABLE
14:18:37  
14:18:37  "Finalizer" #3 daemon prio=8 os_prio=0 tid=0xb65639f0 nid=0x1c6e in Object.wait() [0x936fe000]
14:18:37     java.lang.Thread.State: WAITING (on object monitor)
14:18:37  	at java.lang.Object.wait(Native Method)
14:18:37  	- waiting on <0x9ef1cda8> (a java.lang.ref.ReferenceQueue$Lock)
14:18:37  	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
14:18:37  	- locked <0x9ef1cda8> (a java.lang.ref.ReferenceQueue$Lock)
14:18:37  	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
14:18:37  	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)
14:18:37  
14:18:37  "Reference Handler" #2 daemon prio=10 os_prio=0 tid=0xb6562170 nid=0x1c6d in Object.wait() [0x939fe000]
14:18:37     java.lang.Thread.State: WAITING (on object monitor)
14:18:37  	at java.lang.Object.wait(Native Method)
14:18:37  	- waiting on <0x9ef1cf48> (a java.lang.ref.Reference$Lock)
14:18:37  	at java.lang.Object.wait(Object.java:502)
14:18:37  	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
14:18:37  	- locked <0x9ef1cf48> (a java.lang.ref.Reference$Lock)
14:18:37  	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
14:18:37  
14:18:37  "main" #1 prio=5 os_prio=0 tid=0xb6507410 nid=0x1c6b in Object.wait() [0xb6854000]
14:18:37     java.lang.Thread.State: WAITING (on object monitor)
14:18:37  	at java.lang.Object.wait(Native Method)
14:18:37  	- waiting on <0x9f4cfd48> (a java.lang.Thread)
14:18:37  	at java.lang.Thread.join(Thread.java:1252)
14:18:37  	- locked <0x9f4cfd48> (a java.lang.Thread)
14:18:37  	at java.lang.Thread.join(Thread.java:1326)
14:18:37  	at com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:184)
14:18:37  	at com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:257)
14:18:37  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:193)
14:18:37  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:65)
14:18:37  
14:18:37  "VM Thread" os_prio=0 tid=0xb655c900 nid=0x1c6c runnable 
14:18:37  
14:18:37  "VM Periodic Task Thread" os_prio=0 tid=0xb6581818 nid=0x1c71 waiting on condition 
14:18:37  
14:18:37  JNI global references: 198
14:18:37  
14:18:37  --- Timeout information end.
```

**Comment by smlambert** [comment]
Not seeing this failure reproduce in Grinders (example: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4265) so will close. If it does reproduce on a particular machine, it should be raised as an infra issue (and machine should have ci.role.test tag removed until it can be corrected).

These tests were not excluded using the correct OS-ARCH name (used linux-aarch32 instead of linux-arm), entries in problem lists will be removed as part of #2018.
