### ISSUE TITLE
JTReg Failures: well known file exceptions 

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1725]
**Describe the bug**
On mac machines for jdk8,11 and 14 hotspot the following tests are failing due to pretty much the same error 
```
com/sun/jdi/ProcessAttachTest.java
jdk/jfr/jcmd/TestJcmdStartStopDefault.java
```

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):
1. Go to https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder
2. Kick off a grinder with these parameters 
- JDK8: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=hotspot&BUILD_LIST=openjdk&PLATFORM=x86-64_mac&TARGET=jdk_svc_sanity_0
- JDK11: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=hotspot&BUILD_LIST=openjdk&PLATFORM=x86-64_mac&TARGET=jdk_svc_sanity_0
- JDK14: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=14&JDK_IMPL=hotspot&BUILD_LIST=openjdk&PLATFORM=x86-64_mac&TARGET=jdk_svc_sanity_0
3. See error in console log

**Expected behavior**
Tests pass

**Screenshots**
```
Standard Output: 

Running DCMD 'JFR.start' through 'PidJcmdExecutor'
Executing command '[/Users/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/../bin/jcmd, 18106, JFR.start]'
Command returned with exit code 1
---------------- stdout ----------------
18106:

---------------- stderr ----------------
java.io.IOException: well-known file /var/folders/rt/8_by_h8n5g9d5jhp66cf_7d80000gr/T/.java_pid18106 is not secure: file's group should be the current group (which is -1) but the group is 0
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.checkPermissions(Native Method)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:108)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at jdk.jcmd/sun.tools.jcmd.JCmd.executeCommandForPid(JCmd.java:114)
	at jdk.jcmd/sun.tools.jcmd.JCmd.main(JCmd.java:98)

----------------------------------------
    
Standard Error:

 stdout: [18106:
];
 stderr: [java.io.IOException: well-known file /var/folders/rt/8_by_h8n5g9d5jhp66cf_7d80000gr/T/.java_pid18106 is not secure: file's group should be the current group (which is -1) but the group is 0
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.checkPermissions(Native Method)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:108)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at jdk.jcmd/sun.tools.jcmd.JCmd.executeCommandForPid(JCmd.java:114)
	at jdk.jcmd/sun.tools.jcmd.JCmd.main(JCmd.java:98)
]
 exitValue = 1

java.lang.RuntimeException: Expected to get exit value of [0]

	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:396)
	at jdk.jfr.jcmd.JcmdHelper.jcmd(JcmdHelper.java:111)
	at jdk.jfr.jcmd.JcmdHelper.jcmd(JcmdHelper.java:116)
	at jdk.jfr.jcmd.TestJcmdStartStopDefault.main(TestJcmdStartStopDefault.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Additional context**
It appears to be a perm issue on the surface. The test is creating items in the `/var/`directory which is a sensitive directory to be creating files in. Its possible that this is likely caused by the the debugger that the test creates [not having the same perms as the java_pid file](https://stackoverflow.com/questions/9100149/jstack-well-known-file-is-not-secure).

**Comment by M-Davies** [comment]
Recent builds of [11](https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_x86-64_mac/197/) are intermittently passing. A result of this test failing on all machines except for `test-macincloud-macos1010-x64-1/2`

**Comment by M-Davies** [comment]
@smlambert can you transfer this issue to infrastructure?
