### ISSUE TITLE
dacapo-lusearch-fix_0 fails intermittently

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#1888]
https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_sanity.perf_x86-64_windows/134/console
```
23:19:22  Using scaled threading model. 2 processors detected, 2 threads used to drive the workload, in a possible range of [1,64]
23:19:22  ===== DaCapo 9.12-MR1 lusearch-fix starting =====
23:19:23  4 query batches completed
23:19:23  8 query batches completed
23:19:23  12 query batches completed
23:19:23  16 query batches completed
23:19:23  20 query batches completed
23:19:23  24 query batches completed
23:19:23  28 query batches completed
23:19:23  32 query batches completed
23:19:24  36 query batches completed
23:19:24  40 query batches completed
23:19:24  org.apache.lucene.store.AlreadyClosedException: this Directory is closed
23:19:24  	at org.apache.lucene.store.Directory.ensureOpen(Directory.java:220)
23:19:24  	at org.apache.lucene.store.FSDirectory.list(FSDirectory.java:320)
23:19:24  	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:533)
23:19:24  	at org.apache.lucene.index.DirectoryIndexReader.open(DirectoryIndexReader.java:115)
23:19:24  	at org.apache.lucene.index.IndexReader.open(IndexReader.java:316)
23:19:24  	at org.apache.lucene.index.IndexReader.open(IndexReader.java:206)
23:19:24  	at org.dacapo.lusearchFix.Search$QueryProcessor.<init>(Search.java:207)
23:19:24  	at org.dacapo.lusearchFix.Search$QueryThread.run(Search.java:179)
23:19:24  java.lang.NullPointerException
23:19:24  	at org.dacapo.lusearchFix.Search$QueryProcessor.run(Search.java:226)
23:19:24  	at org.dacapo.lusearchFix.Search$QueryThread.run(Search.java:179)
23:19:24  44 query batches completed
23:19:24  48 query batches completed
23:19:24  52 query batches completed
Cancelling nested steps due to timeout
09:16:30  Sending interrupt signal to process
```

**Comment by smlambert** [comment]
In past, we have seen similar issues on Windows machines where directories are no longer accessible to the jenkins user id 

I suspect the more telling console output is what shows up before the AlreadyClosedException:

```
18:19:21  Attempting to destroy all caches in cacheDir C:\Users\jenkins.TEST-WIN2012-2\AppData\Local\javasharedresources\
18:19:21  
18:19:21  JVMSHRC241E Error: unable to delete shared class cache file
18:19:21  JVMSHRC336E Port layer error code = -100
18:19:21  JVMSHRC337E Platform error message: (32) The process cannot access the file because it is being used by another process.
18:19:21  JVMSHRC430I Failed to remove current generation of shared class cache "sharedcc_jenkins"
18:19:21  
18:19:21  Attempting to destroy all caches in cacheDir C:\Users\jenkins.TEST-WIN2012-2\AppData\Local\javasharedresources\
18:19:21  
18:19:21  JVMSHRC241E Error: unable to delete shared class cache file
18:19:21  JVMSHRC336E Port layer error code = -100
18:19:21  JVMSHRC337E Platform error message: (32) The process cannot access the file because it is being used by another process.
18:19:21  JVMSHRC430I Failed to remove current generation of shared class cache "sharedcc_jenkins"
18:19:21  cache cleanup done
```

We will likely need to shift this to an infra issue to understand what other process is lingering that makes it not possible to remove the scc.  

Related: https://github.com/AdoptOpenJDK/TKG/issues/45 (if there are processes laying around we should report them and abort, rather than try and run testing on a machine that has leftovers remaining on it).

**Comment by andrew-m-leonard** [comment]
Hung again on zLinux this time: https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.perf_s390x_linux_xl/3/console

**Comment by andrew-m-leonard** [comment]
Hung again: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.perf_x86-64_windows_xl/103/console

**Comment by smlambert** [comment]
https://issues.apache.org/jira/browse/LUCENE-5732
https://stackoverflow.com/questions/6568302/lucene-2-9-2-alreadyclosedexception-at-instantiation-of-indexsearcher

**Comment by smlambert** [comment]
auto exclude test dacapo-lusearch-fix
