### ISSUE TITLE
renaissance-naive-bayes_0 perf tests fail on jdk15 with NPE

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#1932]
**Describe the bug**
renaissance-naive-bayes_0 perf tests fail on jdk15 with NPE

**To Reproduce**
https://trss.adoptopenjdk.net/output/test?id=5f28a1350bec7975ae08ae21

Just one example. Seems consistent across the board, all VMs and platforms.

Only occurs on JDK15.

**Expected behavior**
Expected no NPE here.

**Comment by smlambert** [comment]
https://github.com/renaissance-benchmarks/renaissance/blob/v0.9.0/benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/NaiveBayes.scala#L93

But since there is a v0.11.0 of the renaissance suite, I suggest we first upgrade to it, the latest stable version, and see how the suite behaves across jdk8/jdk11/jdk15, as it is likely been updated, definitely that NaiveBayes.scala file is changed.

**Comment by smlambert** [comment]
Updated to v0.11.0 in my branch and still get NPE (for both hotspot and openj9 on jdk15, earlier JDK_VERSIONs are fine)

Hotspot [output](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3751/tapResults/):
GC before operation: completed in 33.588 ms, heap usage 104.344 MB -> 20.284 MB.
Benchmark 'naive-bayes' failed with exception:
java.lang.NullPointerException: Cannot invoke "org.apache.spark.mllib.classification.NaiveBayesModel.labels()" because the return value of "org.renaissance.apache.spark.NaiveBayes.bayesModel()" is null
	at org.renaissance.apache.spark.NaiveBayes.tearDownAfterAll(NaiveBayes.scala:93)
	at org.renaissance.harness.ExecutionDriver.executeBenchmark(ExecutionDriver.java:72)

OpenJ9 output:
GC before operation: completed in 69.052 ms, heap usage 23.157 MB -> 19.402 MB.
Benchmark 'naive-bayes' failed with exception:
java.lang.NullPointerException
	at org.renaissance.apache.spark.NaiveBayes.tearDownAfterAll(NaiveBayes.scala:93)
	at org.renaissance.harness.ExecutionDriver.executeBenchmark(ExecutionDriver.java:72)

**Comment by smlambert** [comment]
Occurs on both hotspot ([Grinder_Perf/5](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Perf/5)) and openj9 ([Grinder_Perf/8](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Perf/8)) builds from AdoptOpenJDK, but not on openj9 builds from the OpenJ9 project ([Grinder_Perf/7](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Perf/7)).  

[NaiveBayes.scala:93](https://github.com/renaissance-benchmarks/renaissance/blob/master/benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/NaiveBayes.scala#L93)

**Comment by smlambert** [comment]
auto exclude test renaissance-naive-bayes

**Comment by smlambert** [comment]
Exclude while investigating so we can 'run green'

**Comment by smlambert** [comment]
@norbline - we can try to rerun this disabled test target against a JDK_VERSION=17 build in a Grinder to see how it behaves

**Comment by norbline** [comment]
test passed https://ci.adoptopenjdk.net/job/Grinder/2817/

**Comment by smlambert** [comment]
Rerun of the 2817 with TARGET=disabled.renaissance-naive-bayes (so that the disabled test target is not skipped):
https://ci.adoptopenjdk.net/job/Grinder/2819/tapResults/

**Comment by Amrutha-Kanhirathingal** [comment]
ALL Platform : https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/51134/

**Comment by sophia-guo** [comment]
Didn't see the issue for  a long time. Close it.
