### ISSUE TITLE
More than half of jdk_jdi tests failed with Dragonwell jdk on packet boxes

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1969]
More than half of jdk_jdi tests failed with Dragonwell jdk8 on packet boxes. Tests passed on other boxes. Also test build took 4 hours compared 40 mins on other boxes. Test builds with hotspot|openj9 on packet boxes also take three times longer than on other boxes without behaviour difference. That is test results are consistent running on packet or other boxes.

<img width="1247" alt="Screen Shot 2020-09-17 at 11 05 22 AM" src="https://user-images.githubusercontent.com/18030625/93489704-c11f5500-f8d5-11ea-9705-492ab2416b30.png">

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/14/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/12/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/10/

Not sure what's the difference between packet boxes with other except for performance?

**Comment by smlambert** [comment]
So I think this needs to get transferred to [openjdk-infrastructure repo](https://github.com/AdoptOpenJDK/openjdk-infrastructure), do you agree @sxa ?

**Comment by smlambert** [comment]
@sophia-guo - I am going to start closing issues that only contain stale Jenkins links... (since we only keep a small number of builds in history, they disappear before anyone can look at the issue). 

For now I will grab some more information out of TRSS using its "create new issue" output, so this issue has enough info to give a trail to follow...

[2020-09-15T18:02:29.682Z] STDERR:
[2020-09-15T18:02:29.682Z] com.sun.jdi.connect.TransportTimeoutException: timeout waiting for connection
[2020-09-15T18:02:29.682Z] 	at com.sun.tools.jdi.SocketTransportService.accept(SocketTransportService.java:350)
[2020-09-15T18:02:29.682Z] 	at SimpleLaunchingConnector.launch(SimpleLaunchingConnector.java:152)
[2020-09-15T18:02:29.682Z] 	at DebugUsingCustomConnector.main(DebugUsingCustomConnector.java:73)
[2020-09-15T18:02:29.682Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-09-15T18:02:29.682Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-09-15T18:02:29.682Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-09-15T18:02:29.682Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2020-09-15T18:02:29.682Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2020-09-15T18:02:29.682Z] 	at java.lang.Thread.run(Thread.java:853)


**Test Info**
Test Name: jdk_jdi_0
Test Duration: 4 hr 5 min 27 sec
Machine: test-scaleway-ubuntu1604-x64-1
TRSS link for the test output: https://trss.adoptopenjdk.net/output/test?id=5f613c3611d26031c17b1fe9


**Build Info**
Build Name: Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux
Jenkins Build start time: Sep 15 2020, 01:31 pm
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/10/
TRSS link for the build: https://trss.adoptopenjdk.net/allTestsInfo?buildId=5f613bb611d26031c17b1fd4


**Java Version**
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.4.4) (build 1.8.0_262-202009151720-b10)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.4.4) (build 25.262-b10, mixed mode)


**This test has been failed 8 times since Sep 08 2020, 01:29 pm**
**Java Version when the issue first seen**
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.4.4) (build 1.8.0_262-202009081718-b10)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.4.4) (build 25.262-b10, mixed mode)
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/2/

The test failed on machine test-scaleway-ubuntu1604-x64-1 1 times 
The test failed on machine test-aws-rhel8-x64-1 1 times 
The test failed on machine test-godaddy-centos7-x64-4 2 times 
The test failed on machine test-godaddy-ubuntu1604-x64-3 1 times 
The test failed on machine test-godaddy-ubuntu1604-x64-1 1 times 
The test failed on machine test-godaddy-centos7-x64-1 1 times 
The test failed on machine test-godaddy-centos7-x64-3 1 times 

[Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?TARGET=jdk_jdi_0&amp;CUSTOM_TARGET=&amp;SDK_RESOURCE=upstream&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=master&amp;TEST_FLAG=&amp;VENDOR_TEST_DIRS=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;PLATFORM=x86-64_linux&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https://github.com/AdoptOpenJDK/openjdk-tests.git&amp;JDK_IMPL=hotspot&amp;LABEL=&amp;TKG_BRANCH=master&amp;EXTRA_OPTIONS=&amp;SSH_AGENT_CREDENTIAL=&amp;IS_PARALLEL=false&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;AUTO_DETECT=true&amp;ADOPTOPENJDK_BRANCH=master&amp;TKG_SHA=&amp;ARTIFACTORY_SERVER=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&amp;OPENJDK_SHA=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=8&amp;BUILD_LIST=openjdk&amp;USER_CREDENTIALS_ID=&amp;UPSTREAM_JOB_NUMBER=9&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https://github.com/alibaba/dragonwell8&amp;TIME_LIMIT=10&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts/jobs/jdk8u/jdk8u-linux-x64-dragonwell&amp;OPENJ9_REPO=https://github.com/eclipse/openj9.git&amp;JVM_OPTIONS=&amp;TKG_REPO=https://github.com/AdoptOpenJDK/TKG.git)

**Comment by sxa** [comment]
> 
> 
> So I think this needs to get transferred to [openjdk-infrastructure repo](https://github.com/AdoptOpenJDK/openjdk-infrastructure), do you agree @sxa ?

Seems reasonable for now :-)
