### ISSUE TITLE
dacapo-lusearch-fix_0 testcase hung on Windows

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#1980]
**Describe the bug**
The dacapo-lusearch-fix_0 "hung", what normally takes 3 seconds has been stuck for 8 hours!

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):
Run Test_openjdk11_hs_sanity.perf_x86-64_windows testcase dacapo-lusearch-fix_0

**Expected behavior**
The testcase should complete and not hang

**Screenshots**
```
03:43:42  ===============================================
03:43:42  Running test dacapo-lusearch-fix_0 ...
03:43:42  ===============================================
03:43:42  dacapo-lusearch-fix_0 Start Time: Tue Sep 29 03:42:57 2020 Epoch Time (ms): 1601368977360
03:43:42  Nothing to be done for setup.
03:43:42  variation: NoOptions
03:43:42  JVM_OPTIONS:  
03:43:42  { itercnt=1; \
03:43:42  mkdir -p "C:/Users/jenkins/workspace/Test_openjdk11_hs_sanity.perf_x86-64_windows/openjdk-tests/\\TKG\\test_output_16013689601040\\dacapo-lusearch-fix_0"; \
03:43:42  cd "C:/Users/jenkins/workspace/Test_openjdk11_hs_sanity.perf_x86-64_windows/openjdk-tests/\\TKG\\test_output_16013689601040\\dacapo-lusearch-fix_0"; \
03:43:42  "C:/Users/jenkins/workspace/Test_openjdk11_hs_sanity.perf_x86-64_windows/openjdkbinary/j2sdk-image\\bin\\java" -jar "C:/Users/jenkins/workspace/Test_openjdk11_hs_sanity.perf_x86-64_windows/openjdk-tests///..//jvmtest\\perf\\dacapo\\dacapo.jar" lusearch-fix; \
03:43:42  	if [ $? -eq 0 ] ; then echo ""; echo "dacapo-lusearch-fix_0""_PASSED"; echo ""; cd C:/Users/jenkins/workspace/Test_openjdk11_hs_sanity.perf_x86-64_windows/openjdk-tests/;  else echo ""; echo "dacapo-lusearch-fix_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "C:/Users/jenkins/workspace/Test_openjdk11_hs_sanity.perf_x86-64_windows/openjdk-tests/\\TKG\\test_output_16013689601040\\TestTargetResult";
03:43:42  Using scaled threading model. 2 processors detected, 2 threads used to drive the workload, in a possible range of [1,64]
03:43:43  ===== DaCapo 9.12-MR1 lusearch-fix starting =====
03:43:44  4 query batches completed
03:43:44  8 query batches completed
03:43:44  org.apache.lucene.store.AlreadyClosedException: this Directory is closed
03:43:44  	at org.apache.lucene.store.Directory.ensureOpen(Directory.java:220)
03:43:44  	at org.apache.lucene.store.FSDirectory.list(FSDirectory.java:320)
03:43:44  	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:533)
03:43:44  	at org.apache.lucene.index.DirectoryIndexReader.open(DirectoryIndexReader.java:115)
03:43:44  	at org.apache.lucene.index.IndexReader.open(IndexReader.java:316)
03:43:44  	at org.apache.lucene.index.IndexReader.open(IndexReader.java:206)
03:43:44  	at org.dacapo.lusearchFix.Search$QueryProcessor.<init>(Search.java:207)
03:43:44  	at org.dacapo.lusearchFix.Search$QueryThread.run(Search.java:179)
03:43:44  java.lang.NullPointerException
03:43:44  	at org.dacapo.lusearchFix.Search$QueryProcessor.run(Search.java:226)
03:43:44  	at org.dacapo.lusearchFix.Search$QueryThread.run(Search.java:179)
03:43:44  12 query batches completed
03:43:44  16 query batches completed
03:43:44  20 query batches completed
03:43:44  24 query batches completed
03:43:45  28 query batches completed
03:43:45  32 query batches completed
```
https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_x86-64_windows/294/console

![image](https://user-images.githubusercontent.com/31470007/94535642-b6e84980-0239-11eb-8a1d-8acb8129b7ee.png)

**Comment by smlambert** [comment]
Dup of https://github.com/AdoptOpenJDK/openjdk-tests/issues/1888
which itself is likely an infra issue but I will add a note in 1888
