### ISSUE TITLE
Test_openjdk15_hs_sanity.perf_x86-32_windows frequently hung/hitting 10Hr timeout

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#1994]
**Describe the bug**
renaissance-akka-uct_0 testcase is either hung or just very very slow...
See: https://ci.adoptopenjdk.net/job/Test_openjdk15_hs_sanity.perf_x86-32_windows/

```
23:07:06  final height= 9
23:07:08  [ERROR] [10/02/2020 17:07:08.697] [UCT-akka.actor.default-dispatcher-2] [ActorSystem(UCT)] Failed to run termination callback, due to [Futures timed out after [5000 milliseconds]]
23:07:08  java.util.concurrent.TimeoutException: Futures timed out after [5000 milliseconds]
23:07:08  	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
23:07:08  	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
23:07:08  	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
23:07:08  	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169)
23:07:08  	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
23:07:08  	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167)
23:07:08  	at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:106)
23:07:08  	at scala.concurrent.Await$.result(package.scala:190)
23:07:08  	at akka.actor.LightArrayRevolverScheduler.close(Scheduler.scala:280)
23:07:08  	at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:689)
23:07:08  	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply$mcV$sp(ActorSystem.scala:618)
23:07:08  	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:618)
23:07:08  	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:618)
23:07:08  	at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:642)
23:07:08  	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.runNext$1(ActorSystem.scala:809)
23:07:08  	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply$mcV$sp(ActorSystem.scala:812)
23:07:08  	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:805)
23:07:08  	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:805)
23:07:08  	at akka.util.ReentrantGuard.withGuard(LockUtil.scala:15)
23:07:08  	at akka.actor.ActorSystemImpl$TerminationCallbacks.run(ActorSystem.scala:805)
23:07:08  	at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:639)
23:07:08  	at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:639)
23:07:08  	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
23:07:08  	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
23:07:08  	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
23:07:08  	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
23:07:08  	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
23:07:08  	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
23:07:08  	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
23:07:08  	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
23:07:08  	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
23:07:08  	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
23:07:08  	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
23:07:08  	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
23:07:08  	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
23:07:08  
23:07:12  final size= 199991
23:07:12  final height= 9
```

```
23:34:00  final size= 199991
23:34:00  final height= 9
23:34:07  final size= 199991
23:34:07  final height= 9
23:34:14  final size= 199991
23:34:14  final height= 9
23:34:16  ====== akka-uct (actors), final iteration completed (66736.84 ms) ======
Cancelling nested steps due to timeout
09:03:32  Sending interrupt signal to process
09:03:46  
09:03:46  renaissance-akka-uct_0_FAILED
```

**Comment by smlambert** [comment]
Notes:

This test case has failed in this way on windows 2 out of 40 times looking at: 
[Deep History for openj9](https://trss.adoptopenjdk.net/deepHistory?testId=5f7bdce711d26031c1de40ec) (fails 1/20)
[Deep History for hotspot](https://trss.adoptopenjdk.net/deepHistory?testId=5f7bbc9b11d26031c1dd1ac7) (fails 1/20) 
For both cases they failed on [test-softlayer-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/test-softlayer-win2012r2-x64-1/) machine. 

Failing [Hotspot console output](https://trss.adoptopenjdk.net/output/test?id=5f799ef311d26031c1d584bf):
[2020-10-04T09:54:28.801Z] ====== akka-uct (actors), iteration 0 started ======
[2020-10-04T09:54:33.503Z] final size= 199991
[2020-10-04T09:54:33.503Z] final height= 9
[2020-10-04T09:54:39.502Z] After 20s process did not stop
[Pipeline] sh
[2020-10-04T09:54:46.515Z] ++ uname
[2020-10-04T09:54:46.516Z] + '[' CYGWIN_NT-6.3 = AIX ']'
[2020-10-04T09:54:46.516Z] ++ uname
[2020-10-04T09:54:46.516Z] + '[' CYGWIN_NT-6.3 = SunOS ']'
[2020-10-04T09:54:46.516Z] + MAKE=make
[2020-10-04T09:54:46.516Z] + make -f ./openjdk-tests/TKG/testEnv.mk testEnvTeardown
[2020-10-04T09:54:46.516Z] make: Nothing to be done for 'testEnvTeardown'.

Failing [OpenJ9 console output](https://trss.adoptopenjdk.net/output/test?id=5f6c5f9e11d26031c1a679b0):
[2020-09-24T08:43:36.437Z] ====== akka-uct (actors), iteration 0 started ======
[2020-09-24T08:43:43.807Z] final size= 199991
[2020-09-24T08:43:43.807Z] final height= 9
[2020-09-24T08:43:45.109Z] After 20s process did not stop
[Pipeline] sh
[2020-09-24T08:43:48.692Z] ++ uname
[2020-09-24T08:43:50.319Z] + '[' CYGWIN_NT-6.3 = AIX ']'
[2020-09-24T08:43:51.259Z] ++ uname
[2020-09-24T08:43:52.936Z] + '[' CYGWIN_NT-6.3 = SunOS ']'
[2020-09-24T08:43:52.936Z] + MAKE=make
[2020-09-24T08:43:52.936Z] + make -f ./openjdk-tests/TKG/testEnv.mk testEnvTeardown
[2020-09-24T08:43:53.508Z] make: Nothing to be done for 'testEnvTeardown'.

Example of passing output:
[2020-10-06T02:25:06.879Z] ====== akka-uct (actors), iteration 0 started ======
[2020-10-06T02:25:17.517Z] final size= 199991
[2020-10-06T02:25:17.518Z] final height= 9
[2020-10-06T02:25:26.583Z] final size= 199991
[2020-10-06T02:25:26.583Z] final height= 9
[2020-10-06T02:25:34.315Z] final size= 199991
[2020-10-06T02:25:34.315Z] final height= 9
[2020-10-06T02:25:41.835Z] final size= 199991
[2020-10-06T02:25:41.835Z] final height= 9
[2020-10-06T02:25:48.360Z] final size= 199991
[2020-10-06T02:25:48.360Z] final height= 9
[2020-10-06T02:25:56.355Z] final size= 199991
[2020-10-06T02:25:56.355Z] final height= 9
[2020-10-06T02:26:03.031Z] final size= 199991
[2020-10-06T02:26:03.031Z] final height= 9
[2020-10-06T02:26:08.767Z] final size= 199991
[2020-10-06T02:26:08.767Z] final height= 9
[2020-10-06T02:26:15.420Z] final size= 199991
[2020-10-06T02:26:15.420Z] final height= 9
[2020-10-06T02:26:22.054Z] final size= 199991
[2020-10-06T02:26:22.054Z] final height= 9
[2020-10-06T02:26:25.482Z] ====== akka-uct (actors), iteration 0 completed (78643.396 ms) ======

**Comment by smlambert** [comment]
auto test exclude akka-uct

**Comment by smlambert** [comment]
auto exclude test renaissance-akka-uct

**Comment by smlambert** [comment]
Updated to renaissance v0.11 (from v.9) and ran [Grinder_Perf jdk15 on windows](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Perf/4):

Fails in last 2 iterations of 24x run with this error:
```
11:45:27  ====== akka-uct (actors) [default], iteration 23 completed (26635.321 ms) ======
11:45:27  Oct 12, 2020 8:45:27 AM org.renaissance.core.Launcher launchHarnessClass
11:45:27  SEVERE: Harness failed with exception: scala.MatchError: com.sun.management.internal.OperatingSystemImpl@63b1d4fa (of class com.sun.management.internal.OperatingSystemImpl)
11:45:27  	at org.renaissance.harness.JsonWriter.getOsInfo(ResultWriter.scala:168)
```
[org.renaissance.core.Launcher:44](https://github.com/renaissance-benchmarks/renaissance/blob/master/renaissance-core/src/main/java/org/renaissance/core/Launcher.java#L44)
[ResultWriter.scala:168](https://github.com/renaissance-benchmarks/renaissance/blob/master/renaissance-harness/src/main/scala/org/renaissance/harness/ResultWriter.scala#L168)

**Comment by Amrutha-Kanhirathingal** [comment]
Hi @llxia /@smlambert 

Executed the test in x86-64_windows on jdk21 since i have no access to adoptium grinder to run the test on adoptium platforms
|Testname|Platform|JDK|Result|
|---|---|---|---|
|renaissance-akka-uct|x86-64_windows :https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50502/| jdk21 | Pass|

**Comment by llxia** [comment]
Please try x86-32_windows on JDK8. Thanks

**Comment by Amrutha-Kanhirathingal** [comment]
JDK8 on platform x86-32_windows
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50638/

**Comment by llxia** [comment]
Since the test is excluded on all platforms, we should test them all before re-enable.

https://github.com/adoptium/aqa-tests/blob/647469a070379125e22fc7ec21cc02bc628b2c78/perf/renaissance/playlist.xml#L19C3-L23C14
