### ISSUE TITLE
getFunctionalTestMaterial fails due to existing directory

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#2119]
getFunctionalTestMaterial() is failing, presumably because the functional folder contains directories from a previous build?

https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk11_hs_sanity.openjdk_x86-32_windows/414/console
```
01:26:08  get functional test material...
01:26:08  git clone --depth 1 -b master https://github.com/eclipse/openj9.git
01:26:30  mv: cannot move 'openj9/test/functional/CacheManagement' to 'functional/CacheManagement': Directory not empty
01:26:30  mv: cannot move 'openj9/test/functional/DDR_Test' to 'functional/DDR_Test': Directory not empty
```

**Comment by andrew-m-leonard** [comment]
Same problem on a Mac node: https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk8_j9_sanity.perf_x86-64_mac/99/console

**Comment by andrew-m-leonard** [comment]
Maybe the openjdk-tests gitSCM can use the "clean before checkout" option? https://github.com/AdoptOpenJDK/openjdk-tests/blob/aa62f38dc91acd861b75498ca8dac83c983f7f29/buildenv/jenkins/openjdk_tests#L268

**Comment by andrew-m-leonard** [comment]
@smlambert @llxia is CleanBeforeCheckout worth a try?

**Comment by andrew-m-leonard** [comment]
Checking the Jenkins log, it seems the end of job cleanup WS-CLEANUP can sometimes fail if the job fails/aborted, due to testcase processes still running. When I aborted a test job, the "PROCESSCATCH: Showing java processes" is not run... presumably it should do?
```
2020-12-16 12:57:31.832+0000 [id=1004872]	SEVERE	h.plugins.ws_cleanup.WsCleanup#perform
Also:   	Also:   java.nio.file.FileSystemException: C:\Users\jenkins\workspace\Test_openjdk11_hs_sanity.openjdk_x86-32_windows\jvmtest\openjdk\jtreg\lib\asmtools.jar: The process cannot access the file because it is being used by another process.

			at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
			at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
			at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
			at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
			at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
			at java.nio.file.Files.deleteIfExists(Files.java:1165)
			at jenkins.util.io.PathRemover.removeOrMakeRemovableThenRemove(PathRemover.java:237)
	Also:   java.nio.file.FileSystemException: C:\Users\jenkins\workspace\Test_openjdk11_hs_sanity.openjdk_x86-32_windows\jvmtest\openjdk\jtreg\lib\asmtools.jar: The process cannot access the file because it is being used by another process.

			at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
			at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
			at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
			at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
			at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
			at java.nio.file.Files.deleteIfExists(Files.java:1165)
			at jenkins.util.io.PathRemover.removeOrMakeRemovableThenRemove(PathRemover.java:241)
jenkins.util.io.CompositeIOException: Unable to remove file C:\Users\jenkins\workspace\Test_openjdk11_hs_sanity.openjdk_x86-32_windows\jvmtest\openjdk\jtreg\lib\asmtools.jar
		at jenkins.util.io.PathRemover.removeOrMakeRemovableThenRemove(PathRemover.java:252)
		at jenkins.util.io.PathRemover.tryRemoveFile(PathRemover.java:205)
		at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:216)
		at jenkins.util.io.PathRemover.forceRemoveRecursive(PathRemover.java:96)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ip-160-153-234-5.ip.secureserver.net/160.153.234.5:52601
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.FilePath.act(FilePath.java:1070)
		at hudson.FilePath.act(FilePath.java:1059)
		at hudson.plugins.ws_cleanup.Cleanup.perform(Cleanup.java:164)
		at hudson.plugins.ws_cleanup.WsCleanup.perform(WsCleanup.java:232)
		at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$541/000000000000000000.run(Unknown Source)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:823)
jenkins.util.io.CompositeIOException: Unable to delete 'C:\Users\jenkins\workspace\Test_openjdk11_hs_sanity.openjdk_x86-32_windows\jvmtest\openjdk\jtreg\lib\asmtools.jar'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at jenkins.util.io.PathRemover.forceRemoveRecursive(PathRemover.java:99)
	at hudson.Util.deleteRecursive(Util.java:296)
	at hudson.Util.deleteRecursive(Util.java:285)
	at hudson.plugins.ws_cleanup.Cleanup.invoke(Cleanup.java:101)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3122)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:118)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by andrew-m-leonard** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-tests/pull/2121

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/2121 is now merged, closing this now.
