### ISSUE TITLE
General Triage of extended.openjdk tests

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2137]
As we wish to enable extended.openjdk tests in weekly builds (and release builds), we must triage the various failures within them.  There are any where between 70 to nearly 300 test cases failures depending on the platform, but the number of core issues that cause this number of failures seems to be small.  This issue lists the set of core issues that account for most of the failures:

- non-Linux platforms require machine configuration (**x11 server installed**) to enable jdk_awt and jdk_swing tests (see https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1791 and https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/211)
- on Linux platforms where x11 server is installed, many jdk_awt tests are failing with '**Incorrect focus owner**' issues (see: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_extended.openjdk_ppc64le_linux/9/testReport/java_awt_Focus_8073453_AWTFocusTransitionTest/java/AWTFocusTransitionTest/)
- some **javax/print tests require a printer** to be installed (example: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_extended.openjdk_ppc64le_linux/9/testReport/javax_print_CheckDupFlavor/java/CheckDupFlavor/)
- **compiler/jvmci tests** are failing with Can't init module exports: module not found: jdk.internal.vm.ci (see: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_extended.openjdk_x86-64_mac/9/testReport/compiler_jvmci_meta_StableFieldTest/java/StableFieldTest/)
- some test targets contain native test lib and are failing because they need **nativepath configured** (Use -nativepath to specify the location of native code, see: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_extended.openjdk_x86-64_mac/9/testReport/tools_launcher_JliLaunchTest/java/JliLaunchTest/)
- **java/beans editor tests** are failing with 'java.lang.Error: could not find editor for class java.awt.Font' (see: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_extended.openjdk_x86-64_mac/9/testReport/java_beans_PropertyEditor_TestFontClassValue/java/TestFontClassValue/)

**Comment by smlambert** [comment]
Fresh run of extended.openjdk on aarch64 (https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-armv8-1/), has 364 test failures, most are java/awt test cases with 'not a focus owner' exceptions (`java.lang.RuntimeException: java.lang.RuntimeException: t1 is not a focus owner`), some javax/print tests that require a printer.

**Comment by smlambert** [comment]
In prep for upcoming Jan release, will exclude the sub-targets that are failing and not yet triaged:
<img width="1391" alt="Screen Shot 2021-01-11 at 9 53 45 AM" src="https://user-images.githubusercontent.com/2836948/104197456-0cb0be00-53f3-11eb-9b14-28eac12e8644.png">

**Comment by smlambert** [comment]
FYI, @llxia @renfeiw 
extended.openjdk targets on hotspot win32 all failing with 

```
[2021-01-09T18:15:51.856Z] Unrecognized VM option 'UseCompressedOops'
[2021-01-09T18:15:51.856Z] Did you mean '(+/-)CheckCompressedOops'? Error: Could not create the Java Virtual Machine.
[2021-01-09T18:15:51.856Z] Error: A fatal exception has occurred. Program will exit.
[2021-01-09T18:15:51.856Z] failed to get JDK properties for J:\jenkins\workspace\Test_openjdk11_hs_extended.openjdk_x86-32_windows\openjdkbinary\j2sdk-image\bin\java -ea -esa -Xmx512m -XX:-UseCompressedOops; exit code 1
[2021-01-09T18:15:51.856Z] Error: failed to get JDK properties for J:\jenkins\workspace\Test_openjdk11_hs_extended.openjdk_x86-32_windows\openjdkbinary\j2sdk-image\bin\java -ea -esa -Xmx512m -XX:-UseCompressedOops; exit code 1
```

See https://trss.adoptopenjdk.net/allTestsInfo?buildId=5ff9fa292bad785066074bd2&limit=5&hasChildren=false

Assume related to https://github.com/AdoptOpenJDK/TKG/pull/131 and https://github.com/AdoptOpenJDK/openjdk-tests/pull/2146

**Comment by llxia** [comment]
Mode150/Mode650 was set the same as Mode110/Mode610 in ottawa.csv. It appears that the behavior of Mode15 and Mode110 are different on win32. I suspect Mode150 cannot run on all 32-bit. I will update ottawa.csv.

**Comment by smlambert** [comment]
@llxia - all extended.openjdk targets are also failing against corretto trying to run Mode150 (see: https://trss.adoptopenjdk.net/allTestsInfo?buildId=5ffa04462bad7850660759cd)

**Comment by sophia-guo** [comment]
All openjdk tests with hotspot on 32 platform failed.  with 

```
13:17:21  Unrecognized VM option 'UseCompressedOops'
13:17:21  Did you mean '(+/-)CheckCompressedOops'? Error: Could not create the Java Virtual Machine.
13:17:21  Error: A fatal exception has occurred. Program will exit.
13:17:21  failed to get JDK properties for J:\jenkins\workspace\Test_openjdk11_hs_extended.openjdk_x86-32_windows\openjdkbinary\j2sdk-image\bin\java -ea -esa -Xmx512m -XX:-UseCompressedOops; exit code 1
13:17:21  Error: failed to get JDK properties for J:\jenkins\workspace\Test_openjdk11_hs_extended.openjdk_x86-32_windows\openjdkbinary\j2sdk-image\bin\java -ea -esa -Xmx512m -XX:-UseCompressedOops; exit code 1
```

-XX:-UseCompressedOops works only for 64-bit JVMs.
https://docs.oracle.com/en/java/javase/13/docs/specs/man/java.html

**Comment by sophia-guo** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/2146 why Openjdk test targets limited to impl = hotspot need to add both mode150 and Mode650 with mode150 skipped? By default +CheckCompressedOops option is enabled, and compressed pointers are used.

**Comment by llxia** [comment]
Re https://github.com/AdoptOpenJDK/openjdk-tests/issues/2137#issuecomment-758173596, For hotspot builds, Mode150 is skipped due to the platform `x86-64_windows`. If we use `x86-64_windows_mixed`, both modes will run. 
For example https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/397/

**Comment by smlambert** [comment]
Missing utilities on aarch64 machines, some tests seem to expect certain utility programs ("which" and "hostname" expected).

Example:

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux_xl/2/testReport/java_nio_file_attribute_BasicFileAttributeView_UnixSocketFile/java/UnixSocketFile/ - requires "which" to be present

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux_xl/2/testReport/sun_net_www_protocol_https_HttpsURLConnection_PostThruProxyWithAuth/java/PostThruProxyWithAuth/ and PostThruProxy.java- expects hostname to be present

**Comment by smlambert** [comment]
From **jdk_sanity_client** target (all 25 tests fail), output from xlinux jtr file for ColorChooserDemoTest:
----------System.err:(67/5230)----------
java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:249)
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:265)
	at java.desktop/sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1243)
	at java.desktop/javax.swing.JComponent.getFontMetrics(JComponent.java:1646)
	at java.desktop/javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:351)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.getPreferredSize(BasicButtonUI.java:474)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at java.desktop/java.awt.GridLayout.preferredLayoutSize(GridLayout.java:342)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1823)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1807)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1682)
	at java.desktop/java.awt.GridBagLayout.GetLayoutInfo(GridBagLayout.java:1127)
	at java.desktop/java.awt.GridBagLayout.getLayoutInfo(GridBagLayout.java:922)
	at java.desktop/java.awt.GridBagLayout.ArrangeGrid(GridBagLayout.java:2090)
	at java.desktop/java.awt.GridBagLayout.arrangeGrid(GridBagLayout.java:2050)
	at java.desktop/java.awt.GridBagLayout.layoutContainer(GridBagLayout.java:818)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2770)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
	... 46 more
Caused by: java.lang.NullPointerException
	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:379)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:324)
	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
	... 51 more
STATUS:Failed.`main' threw exception: java.lang.InternalError: java.lang.reflect.InvocationTargetException

**Comment by smlambert** [comment]
auto exclude test jdk_client_sanity

**Comment by smlambert** [comment]
jdk_security3 failures tracked and excluded under https://github.com/AdoptOpenJDK/openjdk-tests/issues/2123

**Comment by smlambert** [comment]
jdk_2d suffers from the same type of failure seen with the jdk_client_sanity target, example of output from that group of tests, from an xlinux jdk11 hs run:

```
00:21:59  java.lang.InternalError: java.lang.reflect.InvocationTargetException
00:21:59  	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
00:21:59  	at java.base/java.security.AccessController.doPrivileged(Native Method)
00:21:59  	at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
00:21:59  	at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:249)
00:21:59  	at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:265)
00:21:59  	at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:251)
00:21:59  	at java.desktop/sun.awt.X11.XComponentPeer.getFontMetrics(XComponentPeer.java:653)
00:21:59  	at java.desktop/sun.awt.X11.XLabelPeer.getFontMetrics(XLabelPeer.java:48)
00:21:59  	at java.desktop/sun.awt.X11.XLabelPeer.getMinimumSize(XLabelPeer.java:70)
00:21:59  	at java.desktop/sun.awt.X11.XComponentPeer.getPreferredSize(XComponentPeer.java:577)
00:21:59  	at java.desktop/java.awt.Component.preferredSize(Component.java:2718)
00:21:59  	at java.desktop/java.awt.Component.getPreferredSize(Component.java:2698)
00:21:59  	at java.desktop/java.awt.GridBagLayout.GetLayoutInfo(GridBagLayout.java:1127)
00:21:59  	at java.desktop/java.awt.GridBagLayout.getLayoutInfo(GridBagLayout.java:922)
00:21:59  	at java.desktop/java.awt.GridBagLayout.preferredLayoutSize(GridBagLayout.java:742)
00:21:59  	at java.desktop/java.awt.Container.preferredSize(Container.java:1823)
00:21:59  	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1807)
00:21:59  	at java.desktop/java.awt.Window.pack(Window.java:826)
00:21:59  	at com.sun.javatest.regtest.agent.AppletWrapper$AppletRunnable.run(AppletWrapper.java:142)
00:21:59  	at java.base/java.lang.Thread.run(Thread.java:834)
00:21:59  Caused by: java.lang.reflect.InvocationTargetException
00:21:59  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
00:21:59  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
00:21:59  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
00:21:59  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
00:21:59  	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
00:21:59  	... 19 more
00:21:59  Caused by: java.lang.NullPointerException
00:21:59  	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
00:21:59  	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
00:21:59  	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
00:21:59  	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
00:21:59  	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:379)
00:21:59  	at java.base/java.security.AccessController.doPrivileged(Native Method)
00:21:59  	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:324)
00:21:59  	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
00:21:59  	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
00:21:59  	... 24 more
```

**Comment by smlambert** [comment]
auto exclude test jdk_2d

**Comment by smlambert** [comment]
auto exclude test jdk_awt

**Comment by sxa** [comment]
> Missing utilities on aarch64 machines, some tests seem to expect certain utility commands ("which" and "hostname" expected).
> 
> Example:
> 
> https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux_xl/2/testReport/java_nio_file_attribute_BasicFileAttributeView_UnixSocketFile/java/UnixSocketFile/ - requires "which" to be present
> 
> https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux_xl/2/testReport/sun_net_www_protocol_https_HttpsURLConnection_PostThruProxyWithAuth/java/PostThruProxyWithAuth/ and PostThruProxy.java- expects hostname to be present

This is happening on the new Fedora installs in docker containers. Ubuntu seems to have them by default. Fixing now.

**Comment by sxa** [comment]
> Missing utilities on aarch64 machines, some tests seem to expect certain utility commands ("which" and "hostname" expected).
> 
> Example:
> 
> https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux_xl/2/testReport/java_nio_file_attribute_BasicFileAttributeView_UnixSocketFile/java/UnixSocketFile/ - requires "which" to be present
> 
> https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux_xl/2/testReport/sun_net_www_protocol_https_HttpsURLConnection_PostThruProxyWithAuth/java/PostThruProxyWithAuth/ and PostThruProxy.java- expects hostname to be present

This is happening on the new Fedora installs in docker containers. Ubuntu seems to have them by default. Fixing now.

**Comment by smlambert** [comment]
auto exclude test jdk_imageio

**Comment by smlambert** [comment]
auto exclude test jdk_imageio plat=.*mac.*
