### ISSUE TITLE
Identify which tests seem unstable in docker containers

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-tests#2138]
This is partially for my own notes, but need to be looked at, and may also be covered elsewhere:

- In [OpenJ9 extended.functional](https://ci.adoptopenjdk.net/view/sxa-arm64test/job/Test_openjdk11_j9_extended.functional_aarch64_linux/): `testDDR*` `cmdLineTester` and `jit_hw_2`
- Similar in [sanity.functional](https://ci.adoptopenjdk.net/view/sxa-arm64test/job/Test_openjdk15_j9_sanity.functional_aarch64_linux/) with `cmdLineTester` tests
- Intermittent failures in [JDK8/J9 sanity.openjdk](https://ci.adoptopenjdk.net/view/sxa-arm64test/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/)
- [JDK11/J9 extended.system](https://ci.adoptopenjdk.net/view/sxa-arm64test/job/Test_openjdk11_j9_extended.system_aarch64_linux/) possibly fails on packet host `-2` and not `-1` - unrelated to docker?
- [JDK11/J9 sanity.system](https://ci.adoptopenjdk.net/view/sxa-arm64test/job/Test_openjdk11_j9_sanity.system_aarch64_linux_xl/) TestIBMJlmFRemoteMemoryAuth_0 fails
- [JDK15/J9 extended.system](https://ci.adoptopenjdk.net/view/sxa-arm64test/job/Test_openjdk15_j9_extended.system_aarch64_linux_xl/) HCRLateAttachWorkload_previewEnabled_0 fails

Other's (on initial look - not too deep!) seem ok

**Comment by sxa** [comment]
[JDK11/J9 extended.functional](https://ci.adoptopenjdk.net/view/sxa-arm64test/job/Test_openjdk11_j9_extended.functional_aarch64_linux/82) is showing `04:58:17   [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_aarch64_linux/openjdkbinary/j2sdk-image/lib/libawt_xawt.so (libXrender.so.1: cannot open shared object file: No such file or directory)` despite libawt_xawt.so being present in `/usr/lib/jvm/jdk8/jre/lib/aarch64/libawt_xawt.so` on the Ubuntu 16.04 docker image. Retrying on same machine at https://ci.adoptopenjdk.net/view/sxa-arm64test/job/Test_openjdk11_j9_extended.functional_aarch64_linux/83/console

**Comment by sxa** [comment]
NOTE - runs on the Fedora docker image:
- [JDK11/J9 sanity.functional](https://ci.adoptopenjdk.net/view/sxa-arm64test/job/Test_openjdk11_j9_sanity.functional_aarch64_linux/91/) is running clean
- [JDK11/J9 extended.functional](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.functional_aarch64_linux/89/)
- [JDK15/J9 sanity.functional](https://ci.adoptopenjdk.net/view/sxa-arm64test/job/Test_openjdk15_j9_sanity.functional_aarch64_linux/45/)

**Comment by sxa** [comment]
Also trying on a couple of X64 docker images ([Fedora 33](https://ci.adoptopenjdk.net/computer/test-sxad-f33-x64-1/) and [Ubuntu 20.04](https://ci.adoptopenjdk.net/computer/test-sxad-ubuntu2004-x64-1/))
- [JDK8/J9 sanity.openjdk](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/446/console) **PASSED**
- [JDK11/HS sanity.functional](https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk11_hs_sanity.functional_x86-64_linux/62/console) **PASSED**
- [JDK8/J9xl extended.functional](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl)
- [JDK11/J9 sanity.funcational](https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk11_j9_sanity.functional_x86-64_linux/57/console)

**Comment by sxa** [comment]
[NUMA interrogation is failing in Docker](https://github.com/AdoptOpenJDK/openjdk-tests/issues/2143)

**Comment by sxa** [comment]
core dump generation is also failing (I've tried starting the container with various options that might help  but to no avail ... so far)

**Comment by sxa** [comment]
Also not specific to docker, but we have seen instances where `LANG` is not set to `en_US.UTF-8`
```
21:41:41  ACTION: main -- Failed. Execution failed: `main' threw exception: java.util.IllformedLocaleException: Ill-formed language: c.u [at index 0]
21:41:41  REASON: User specified action: run main/othervm -Duser.language.display=ja -Duser.language.format=zh LocaleCategory 
21:41:41  TIME:   8.802 seconds
21:41:41  messages:
```
This will be progressed via https://github.com/AdoptOpenJDK/run-aqa/issues/59

**Comment by sophia-guo** [comment]
Grinder on testc-packet-fedora33-amd-2 and got 

```
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://github.com/AdoptOpenJDK/openjdk-tests.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://github.com/AdoptOpenJDK/openjdk-tests.git/': OpenSSL SSL_connect: Connection reset by peer in connection to github.com:443 
```

https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/203/console

Suppose testc-packet-fedora33-amd-2 is docker containers?

**Comment by sxa** [comment]
> Suppose testc-packet-fedora33-amd-2 is one docker container?

Yes - it's a docker container.

Hmmm that's a bit odd ... It's also nothing to do with the test if it's failing that early in the process. I've re-run it as [205](https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/205/console) and it completed without any fatal failures so hopefully that won't occur, but if you see any further instances let me know so we can see if it happens regularly.

**Comment by smlambert** [comment]
From https://adoptopenjdk.slack.com/archives/C5219G28G/p1612761729068300, we should check whether the timeouthandler added to openj9 openjdk test runs is able to write a System dump in dockerized environment.

**Comment by knn-k** [comment]
I wonder if https://github.com/eclipse/openj9/issues/12038 is another example of failure in docker environments or not.
"AssertionError: Free Physical Memory size cannot be greater than total Physical Memory Size."

**Comment by sxa** [comment]
> I wonder if https://github.com/eclipse/openj9/issues/12038 is another example of failure in docker environments or not.
> "AssertionError: Free Physical Memory size cannot be greater than total Physical Memory Size."

Hmmm interesting thought. Certainly possibly but this is the first I've heard of it. Some of those containers we have are called in terms of CPU and RAM which could explain why you wouldn't necessarily be able to replicate locally without doing the same.

**Comment by jerboaa** [comment]
sanity.openjdk on JDK 8 (Hotspot) seems to randomly fail for these tests:
```
java/util/Arrays/TimSortStackSize2.java.TimSortStackSize2
java.lang.OutOfMemoryError: Java heap space
	at TimSortStackSize2.createArray(TimSortStackSize2.java:164)
	at TimSortStackSize2.doTest(TimSortStackSize2.java:59)
	at TimSortStackSize2.main(TimSortStackSize2.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:748)

java/util/ResourceBundle/Bug4168625Test.java.Bug4168625Test 
14:10:19  ACTION: main -- Error. Agent communication error: java.io.EOFException; check console log for any additional details

java/lang/invoke/LFCaching/LFSingleThreadCachingTest.java.LFSingleThreadCachingTest 
Unexpected exit from test [exit code: 137]
```

See:
https://ci.adoptopenjdk.net/view/Test_upstream/job/Test_openjdk8_hs_sanity.openjdk_x86-64_linux_upstream/75/

Especially LFSingleThreadCachingTest.java looks like an OOM kill. Would be nice to overlay that failure with the kernel OOM kill logs.

**Comment by sxa** [comment]
Above error was on test-docker-fedora33-x64-2 hosted on test-packet-ubuntu2004-amd-1. Those systems were all started with 4 cores and 6GB allocated to them. Re-testing at https://ci.adoptopenjdk.net/job/Grinder/7350

@smlambert In the log Severin referenced above it gives the Grinder re-run link for the individual test as https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=hotspot&JDK_VENDOR=oracle&BUILD_LIST=openjdk&PLATFORM=x86-64_linux_xl&TARGET=jdk_lang_1 which is clearly wrong as it doesn't reference upstream and  the `PLATFORM` has `_xl` in it - is that a bug?

**Comment by sxa** [comment]
Potential resource starvation reported by @lumpfish in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2002 - I see a "docker day" in my near future ...

**Comment by sxa** [comment]
At the moment at least some docker images hosted on build-packet-ubuntu1804-armv8-1 ([U1804b_2223](https://ci.adoptopenjdk.net/computer/build-docker-ubuntu1804-armv8-3/) in particular) [this job currently running](https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.openjdk_aarch64_linux/8/) and docker-packet-ubuntu2004-amd-1 ([U2004_2224](https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2004-x64-1/) ([this job currently running](https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_x86-64_linux/12/)) in particular) are using a lot of CPU so potentially need to be properly capped. The failures being seen above may well only be occurring on those systems.

When the systems are quiesced tomorrow (since we're running the weekend piplines for JDK16 again due to https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/87) I can look at adjusting the capping of the tests

**Comment by sxa** [comment]
OK I've brought the following offline for now while investigations occur as some of these have shown problems with `jdk_time_1`:
build-docker-*-armv8-* nodes:
- fedora33-2 fedora33-3 fedora33-4 fedora33-5 ubuntu1804-2 ubuntu1804-3 ubuntu1804-4 ubuntu1804-5 ubuntu1804-6 ubuntu1804-armv8l-1 (Hosted on `build-packet-ubuntu1804-armv8-1`)
- And test-docker-fedora33-x64-3 which has been showing issues too
- `jdk_time_1` has passed on the alibaba arm node and also test-docker-fedora-x64-1 (Verifying again at [7531](https://ci.adoptopenjdk.net/job/Grinder/7531) but this should at least demonstrate it's not a problem on all Fedora systems as it passed at [7506](https://ci.adoptopenjdk.net/job/Grinder/7506/)!)

**Comment by sxa** [comment]
> sanity.openjdk on JDK 8 (Hotspot) seems to randomly fail for these tests:
> 
> ```
> java/util/Arrays/TimSortStackSize2.java.TimSortStackSize2
> java.lang.OutOfMemoryError: Java heap space
> 	at TimSortStackSize2.createArray(TimSortStackSize2.java:164)
> 	at TimSortStackSize2.doTest(TimSortStackSize2.java:59)
> 	at TimSortStackSize2.main(TimSortStackSize2.java:43)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> java/util/ResourceBundle/Bug4168625Test.java.Bug4168625Test 
> 14:10:19  ACTION: main -- Error. Agent communication error: java.io.EOFException; check console log for any additional details
> 
> java/lang/invoke/LFCaching/LFSingleThreadCachingTest.java.LFSingleThreadCachingTest 
> Unexpected exit from test [exit code: 137]
> ```
> 
> See:
> https://ci.adoptopenjdk.net/view/Test_upstream/job/Test_openjdk8_hs_sanity.openjdk_x86-64_linux_upstream/75/
> 
> Especially LFSingleThreadCachingTest.java looks like an OOM kill. Would be nice to overlay that failure with the kernel OOM kill logs.

This looks to be the same issue that's covered in https://github.com/AdoptOpenJDK/openjdk-tests/issues/2310 and not specific to docker

**Comment by sxa** [comment]
With the merhing of https://github.com/AdoptOpenJDK/openjdk-tests/pull/2345 i've brought most systems back online - I've left
[build-docker-fedora33-armv8-5](https://ci.adoptopenjdk.net/computer/build-docker-fedora33-armv8-5/) [build-docker-ubuntu1804-5](https://ci.adoptopenjdk.net/computer/build-docker-ubuntu1804-armv8-5/) [build-docker-ubuntu1804-6](https://ci.adoptopenjdk.net/computer/build-docker-ubuntu1804-armv8-6/)

**Comment by sophia-guo** [comment]
Another one https://github.com/adoptium/adoptium/issues/63#issuecomment-894501202

**Comment by sxa** [comment]
@sophia-guo That looks like the tests have a dependency on the `fakeroot` tool which I wasn't aware we required. Can yuou supply a Grinder re-run link for that problem, as I'm not sure it'll be specific to docker - we do not have `fakeroot` available on all of our systems at present.

**Comment by smlambert** [comment]
Example run in Grinder: https://ci.adoptopenjdk.net/job/Grinder/1203

[Rerun in Grinder on same machine](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=nightly&TARGET=jdk_tools_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=test-skytap-ubuntu2004-ppc64le-1&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=16&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk16u&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-16.0.2%2B7_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=10&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) link

**Comment by sophia-guo** [comment]
@sxa if I login in test machine I can run `fakeroot`, which means it is installed by default in Linux probably. Though aarch64 has the same issue, which I will open an issue in infra. https://github.com/adoptium/infrastructure/issues/2291
