### ISSUE TITLE
jfc_demo_0 from extended.openjdk fails (do we build/include jfcdemo.jar)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2157]
**Test Info**
Test Name: jfc_demo_0
Test Duration: 17 sec
Machine: test-aws-rhel76-armv8-1
TRSS link for the test output: https://trss.adoptopenjdk.net/output/test?id=5ffa727e2bad7850660833ce

**Build Info**
Build Name: Test_openjdk11_hs_extended.openjdk_aarch64_linux
Jenkins Build start time: Jan 09 2021, 12:55 pm
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_aarch64_linux/7/
TRSS link for the build: https://trss.adoptopenjdk.net/allTestsInfo?buildId=5ffa71032bad785066082c16

Fails for all impls/versions:

```
[2021-01-10T03:09:49.361Z] STDOUT:
[2021-01-10T03:09:49.361Z] TEST_IMAGE_DIR=null
[2021-01-10T03:09:49.361Z] demo_path=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/demo/jfc/J2Ddemo/J2Ddemo.jar
[2021-01-10T03:09:49.361Z] Starting: /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java -ea -esa -Xmx512m -XX:+UseCompressedOops -jar /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/demo/jfc/J2Ddemo/J2Ddemo.jar -runs=1
[2021-01-10T03:09:49.361Z] Error: Unable to access jarfile /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/demo/jfc/J2Ddemo/J2Ddemo.jar
[2021-01-10T03:09:49.361Z] Exit code is 1
[2021-01-10T03:09:49.361Z] <beginning of Error Stream buffer>
[2021-01-10T03:09:49.361Z] Error: Unable to access jarfile /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/demo/jfc/J2Ddemo/J2Ddemo.jar
[2021-01-10T03:09:49.361Z] 
[2021-01-10T03:09:49.361Z] <end of buffer>
[2021-01-10T03:09:49.361Z] <beginning of Input Stream buffer>
[2021-01-10T03:09:49.361Z] 
[2021-01-10T03:09:49.361Z] <end of buffer>
[2021-01-10T03:09:49.361Z] STDERR:
[2021-01-10T03:09:49.361Z] java.lang.RuntimeException: Test failed - exit return code non-zero (exitStatus==1)
[2021-01-10T03:09:49.361Z] 	at J2DdemoTest$DemoRun.runit(J2DdemoTest.java:198)
[2021-01-10T03:09:49.361Z] 	at J2DdemoTest.main(J2DdemoTest.java:43)
[2021-01-10T03:09:49.361Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-01-10T03:09:49.361Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-01-10T03:09:49.361Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-01-10T03:09:49.361Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-01-10T03:09:49.361Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-01-10T03:09:49.361Z] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

Check what needs to happen in order to build and have present this J2Ddemo.jar artifact.  In the meantime this is likely not a high priority test target and can be temporarily excluded.

**Comment by smlambert** [comment]
auto exclude test jfc_demo

**Comment by smlambert** [comment]
Marking this issue as resolved, indicates that we are happy with the resolution being to permanently exclude this test target.  Is that true/correct?  If so, then we should conclusively state that we have no intent to ever run the set of tests in this target.

I had temporarily excluded this test target so we run 'green', and while we determine the correct 'fix' for this...  is it merely an additional build arg to create the needed jar file?  What value do these tests have, etc.
