### ISSUE TITLE
org.openjdk.tests.java.util.stream.SpliteratorTest.testSegmentSpliterator java.lang.IllegalStateException: Misaligned access at address: 12

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-tests#2196]
**Describe the bug**
[2021-01-18T12:17:58.496Z] test org.openjdk.tests.java.util.stream.SpliteratorTest.testSegmentSpliterator("longs", [1024:b64], org.openjdk.tests.java.util.stream.SegmentTestDataProvider$$Lambda$225/0x90f067f8@1a44285): failure
[2021-01-18T12:17:58.496Z] java.lang.IllegalStateException: Misaligned access at address: 12
[2021-01-18T12:17:58.496Z] 	at java.base/java.lang.invoke.MemoryAccessVarHandleBase.newIllegalStateExceptionForMisalignedAccess(MemoryAccessVarHandleBase.java:54)
[2021-01-18T12:17:58.496Z] 	at java.base/java.lang.invoke.MemoryAccessVarHandleLongHelper.offsetNoVMAlignCheck(MemoryAccessVarHandleLongHelper.java:69)
[2021-01-18T12:17:58.496Z] 	at java.base/java.lang.invoke.MemoryAccessVarHandleLongHelper.get0(MemoryAccessVarHandleLongHelper.java:80)
[2021-01-18T12:17:58.496Z] 	at java.base/java.lang.invoke.VarHandleGuards.guard_L_J(VarHandleGuards.java:169)
[2021-01-18T12:17:58.496Z] 	at org.openjdk.tests.java.util.stream.SegmentTestDataProvider.lambda$compareSegmentsLong$4(SegmentTestDataProvider.java:95)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
[2021-01-18T12:17:58.496Z] 	at org.openjdk.tests.java.util.stream.SegmentTestDataProvider.compareSegmentsLong(SegmentTestDataProvider.java:98)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.SpliteratorTestHelper.testForEach(SpliteratorTestHelper.java:274)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:160)
[2021-01-18T12:17:58.496Z] 	at org.openjdk.tests.java.util.stream.SpliteratorTest.testSegmentSpliterator(SpliteratorTest.java:69)
[2021-01-18T12:17:58.496Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-01-18T12:17:58.496Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[2021-01-18T12:17:58.496Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-01-18T12:17:58.496Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[2021-01-18T12:17:58.496Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2021-01-18T12:17:58.496Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2021-01-18T12:17:58.496Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2021-01-18T12:17:58.496Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2021-01-18T12:17:58.496Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-01-18T12:17:58.496Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2021-01-18T12:17:58.496Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2021-01-18T12:17:58.496Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2021-01-18T12:17:58.496Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2021-01-18T12:17:58.496Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2021-01-18T12:17:58.496Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2021-01-18T12:17:58.496Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2021-01-18T12:17:58.496Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-01-18T12:17:58.496Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2021-01-18T12:17:58.496Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2021-01-18T12:17:58.496Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2021-01-18T12:17:58.496Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2021-01-18T12:17:58.496Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-01-18T12:17:58.496Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-01-18T12:17:58.496Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-01-18T12:17:58.496Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[2021-01-18T12:17:58.496Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-01-18T12:17:58.496Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[2021-01-18T12:17:58.496Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-01-18T12:17:58.496Z] 	at java.base/java.lang.Thread.run(Thread.java:832)
[2021-01-18T12:17:58.496Z] test org.openjdk.tests.java.util.stream.SpliteratorTest.testSegmentSpliterator("floats", [1024:b32], org.openjdk.tests.java.util.stream.SegmentTestDataProvider$$Lambda$226/0x90f06b58@a523de): success
[2021-01-18T12:17:58.496Z] test org.openjdk.tests.java.util.stream.SpliteratorTest.testSegmentSpliterator("doubles", [1024:b64], org.openjdk.tests.java.util.stream.SegmentTestDataProvider$$Lambda$227/0x90f06eb8@14a3bdd): failure
[2021-01-18T12:17:58.496Z] java.lang.IllegalStateException: Misaligned access at address: 12
[2021-01-18T12:17:58.496Z] 	at java.base/java.lang.invoke.MemoryAccessVarHandleBase.newIllegalStateExceptionForMisalignedAccess(MemoryAccessVarHandleBase.java:54)
[2021-01-18T12:17:58.496Z] 	at java.base/java.lang.invoke.MemoryAccessVarHandleDoubleHelper.offsetNoVMAlignCheck(MemoryAccessVarHandleDoubleHelper.java:76)
[2021-01-18T12:17:58.496Z] 	at java.base/java.lang.invoke.MemoryAccessVarHandleDoubleHelper.get0(MemoryAccessVarHandleDoubleHelper.java:87)
[2021-01-18T12:17:58.496Z] 	at java.base/java.lang.invoke.VarHandleGuards.guard_L_D(VarHandleGuards.java:295)
[2021-01-18T12:17:58.496Z] 	at org.openjdk.tests.java.util.stream.SegmentTestDataProvider.lambda$compareSegmentsDouble$7(SegmentTestDataProvider.java:125)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[2021-01-18T12:17:58.496Z] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
[2021-01-18T12:17:58.496Z] 	at org.openjdk.tests.java.util.stream.SegmentTestDataProvider.compareSegmentsDouble(SegmentTestDataProvider.java:128)
[2021-01-18T12:17:58.497Z] 	at java.base/java.util.SpliteratorTestHelper.testForEach(SpliteratorTestHelper.java:274)
[2021-01-18T12:17:58.497Z] 	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:160)
[2021-01-18T12:17:58.497Z] 	at org.openjdk.tests.java.util.stream.SpliteratorTest.testSegmentSpliterator(SpliteratorTest.java:69)
[2021-01-18T12:17:58.497Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-01-18T12:17:58.497Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[2021-01-18T12:17:58.497Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-01-18T12:17:58.497Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[2021-01-18T12:17:58.497Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2021-01-18T12:17:58.497Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2021-01-18T12:17:58.497Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2021-01-18T12:17:58.497Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2021-01-18T12:17:58.497Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-01-18T12:17:58.497Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2021-01-18T12:17:58.497Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2021-01-18T12:17:58.497Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2021-01-18T12:17:58.497Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2021-01-18T12:17:58.497Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2021-01-18T12:17:58.497Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2021-01-18T12:17:58.497Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2021-01-18T12:17:58.497Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-01-18T12:17:58.497Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2021-01-18T12:17:58.497Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2021-01-18T12:17:58.497Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2021-01-18T12:17:58.497Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2021-01-18T12:17:58.497Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-01-18T12:17:58.497Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-01-18T12:17:58.497Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-01-18T12:17:58.497Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[2021-01-18T12:17:58.497Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-01-18T12:17:58.497Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[2021-01-18T12:17:58.497Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-01-18T12:17:58.497Z] 	at java.base/java.lang.Thread.run(Thread.java:832)

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by smlambert** [comment]
It runs as part of jdk_util target, so adding more details from TRSS on that target failure:

**Build Info**
Build Name: Test_openjdk15_hs_sanity.openjdk_arm_linux
Jenkins Build start time: Jan 21 2021, 08:25 am
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk15_hs_sanity.openjdk_arm_linux/99/
TRSS link for the build: https://trss.adoptopenjdk.net/allTestsInfo?buildId=6009ef752bad785066565682


**This test has been failed 3 times since Jan 14 2021, 08:13 pm**
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk15_hs_sanity.openjdk_arm_linux/97/

The test failed on machine build-scaleway-ubuntu1604-armv7-2 1 times 
The test failed on machine test-aahlenst-armv7-raspbian-pi4-2 1 times 
The test failed on machine test-sxamb-armv7l-raspbian-pi4 1 times
