### ISSUE TITLE
jdk16 extended.perf renaissance-db-shootout_0 java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#2254]
jdk16 extended.perf test target `renaissance-db-shootout_0` fails with `java.lang.IllegalAccessError`.

Looks like the benchmark is trying to access a module which is no longer available in jdk16.

The test fails in the same way on both hotspot and openj9 builds.

Test output:
```
07:19:42  ===============================================
07:19:43  Running test renaissance-db-shootout_0 ...
07:19:43  ===============================================
07:19:43  renaissance-db-shootout_0 Start Time: Sun Feb  7 07:19:42 2021 Epoch Time (ms): 1612682382382
07:19:43  Nothing to be done for setup.
07:19:43  variation: NoOptions
07:19:43  JVM_OPTIONS:  
07:19:44  { itercnt=1; \
07:19:44  mkdir -p "C:/Users/jenkins/workspace/Test_openjdk16_hs_extended.perf_x86-64_windows/openjdk-tests/\\TKG\\output_16126822706614\\renaissance-db-shootout_0"; \
07:19:44  cd "C:/Users/jenkins/workspace/Test_openjdk16_hs_extended.perf_x86-64_windows/openjdk-tests/\\TKG\\output_16126822706614\\renaissance-db-shootout_0"; \
07:19:44  "C:/Users/jenkins/workspace/Test_openjdk16_hs_extended.perf_x86-64_windows/openjdkbinary/j2sdk-image\\bin\\java" -jar "C:/Users/jenkins/workspace/Test_openjdk16_hs_extended.perf_x86-64_windows/openjdk-tests///..//jvmtest\\perf\\renaissance\\renaissance-mit.jar" --json ""C:/Users/jenkins/workspace/Test_openjdk16_hs_extended.perf_x86-64_windows/openjdk-tests/\\TKG\\output_16126822706614\\renaissance-db-shootout_0"\\db-shootout.json" db-shootout; \
07:19:44  	if [ $? -eq 0 ] ; then echo ""; echo "renaissance-db-shootout_0""_PASSED"; echo ""; cd C:/Users/jenkins/workspace/Test_openjdk16_hs_extended.perf_x86-64_windows/openjdk-tests/; rm -f -r "C:/Users/jenkins/workspace/Test_openjdk16_hs_extended.perf_x86-64_windows/openjdk-tests/\\TKG\\output_16126822706614\\renaissance-db-shootout_0"; else echo ""; echo "renaissance-db-shootout_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "C:/Users/jenkins/workspace/Test_openjdk16_hs_extended.perf_x86-64_windows/openjdk-tests/\\TKG\\output_16126822706614\\TestTargetResult";
07:20:10  SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
07:20:10  SLF4J: Defaulting to no-operation (NOP) logger implementation
07:20:10  SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
07:20:10  Error during tear-down: Cannot invoke "net.openhft.chronicle.map.ChronicleMap.close()" because "this.map" is null
07:20:10  java.lang.NullPointerException: Cannot invoke "net.openhft.chronicle.map.ChronicleMap.close()" because "this.map" is null
07:20:10  	at org.lmdbjava.bench.Chronicle$CommonChronicleMap.teardown(Chronicle.java:131)
07:20:10  	at org.lmdbjava.bench.Chronicle$Reader.teardown(Chronicle.java:210)
07:20:10  	at org.renaissance.database.DbShootout.tearDownAfterAll(DbShootout.scala:81)
07:20:10  	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:97)
07:20:10  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
07:20:10  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
07:20:10  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
07:20:10  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
07:20:10  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
07:20:10  	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
07:20:10  	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
07:20:10  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
07:20:10  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
07:20:10  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
07:20:10  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
07:20:10  	at org.renaissance.Launcher.main(Launcher.java:18)
07:20:10  Exception occurred in org.renaissance.database.DbShootout@7a1234bf: class net.openhft.chronicle.core.OS (in unnamed module @0x7fb95505) cannot access class sun.nio.ch.FileChannelImpl (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x7fb95505
07:20:10  java.lang.IllegalAccessError: class net.openhft.chronicle.core.OS (in unnamed module @0x7fb95505) cannot access class sun.nio.ch.FileChannelImpl (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x7fb95505
07:20:10  	at net.openhft.chronicle.core.OS.<clinit>(OS.java:78)
07:20:10  	at net.openhft.chronicle.map.ChronicleMapBuilder.<init>(ChronicleMapBuilder.java:206)
07:20:10  	at net.openhft.chronicle.map.ChronicleMapBuilder.of(ChronicleMapBuilder.java:280)
07:20:10  	at net.openhft.chronicle.map.ChronicleMap.of(ChronicleMap.java:71)
07:20:10  	at org.lmdbjava.bench.Chronicle$CommonChronicleMap.setup(Chronicle.java:118)
07:20:10  	at org.lmdbjava.bench.Chronicle$Reader.setup(Chronicle.java:204)
07:20:10  	at org.renaissance.database.DbShootout.setUpBeforeAll(DbShootout.scala:68)
07:20:10  	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:74)
07:20:10  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
07:20:10  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
07:20:10  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
07:20:10  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
07:20:10  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
07:20:10  	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
07:20:10  	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
07:20:10  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
07:20:10  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
07:20:10  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
07:20:10  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
07:20:10  	at org.renaissance.Launcher.main(Launcher.java:18)
07:20:10  The following benchmarks failed: db-shootout
07:20:10  
07:20:10  renaissance-db-shootout_0_FAILED
```
To rerun: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=hotspot&JDK_VENDOR=adoptopenjdk&BUILD_LIST=perf&PLATFORM=x86-64_windows&TARGET=renaissance-db-shootout_0

**Comment by smlambert** [comment]
Checking if the update to v0.11.0 addresses this issue (Grinder https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Perf/22), if it does not, it will have to be excluded in jdk16+ and likely reported upstream.

**Comment by smlambert** [comment]
Close in favour of https://github.com/AdoptOpenJDK/openjdk-tests/issues/2500
