### ISSUE TITLE
extended.openjdk failure: com/sun/jndi/ldap/DeadSSLLdapTimeoutTest.java.DeadSSLLdapTimeoutTest

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#2351]
com/sun/jndi/ldap/DeadSSLLdapTimeoutTest.java.DeadSSLLdapTimeoutTest
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_aarch64_linux/9/testReport/junit/com_sun_jndi_ldap_DeadSSLLdapTimeoutTest/java/DeadSSLLdapTimeoutTest/
Fails both Hotspot and OpenJ9
```
01:37:37  openjdk version "1.8.0_292"
01:37:37  OpenJDK Runtime Environment (build 1.8.0_292-202103091148-b05)
01:37:37  Eclipse OpenJ9 VM (build openj9-0.26.0-m1, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20210309_235 (JIT enabled, AOT enabled)
01:37:37  OpenJ9   - b227feba2
01:37:37  OMR      - 4665e2f72
01:37:37  JCL      - 1780cbc92b based on jdk8u292-b05)
```
```
java.lang.RuntimeException: Test failed
	at DeadServerTimeoutSSLTest.fail(DeadSSLLdapTimeoutTest.java:94)
	at DeadServerTimeoutSSLTest.handleNamingException(DeadSSLLdapTimeoutTest.java:81)
	at DeadServerTimeoutSSLTest.call(DeadSSLLdapTimeoutTest.java:127)
	at DeadSSLLdapTimeoutTest.main(DeadSSLLdapTimeoutTest.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:823)
Caused by: javax.naming.CommunicationException: localhost:35123 [Root exception is javax.net.ssl.SSLException: Read timed out]
	at com.sun.jndi.ldap.Connection.<init>(Connection.java:243)
	at com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
	at com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1615)
	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2849)
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:347)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:225)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:243)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<init>(InitialContext.java:216)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at DeadServerTimeoutSSLTest.call(DeadSSLLdapTimeoutTest.java:120)
```

**Comment by lumpfish** [comment]
The test only fails on jdk8.

The test expects a `SocketTimeoutException` or `SSLHandshakeException`, which is what is thrown on jdk11+, but on jdk8 `SSLException` is thrown.

jdk8 output (test fails):

13:57:22  STDERR:
13:57:22  java.lang.RuntimeException: Test failed
13:57:22  	at DeadServerTimeoutSSLTest.fail(DeadSSLLdapTimeoutTest.java:94)
13:57:22  	at DeadServerTimeoutSSLTest.handleNamingException(DeadSSLLdapTimeoutTest.java:81)
13:57:22  	at DeadServerTimeoutSSLTest.call(DeadSSLLdapTimeoutTest.java:127)
13:57:22  	at DeadSSLLdapTimeoutTest.main(DeadSSLLdapTimeoutTest.java:201)
13:57:22  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:57:22  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:57:22  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:57:22  	at java.lang.reflect.Method.invoke(Method.java:498)
13:57:22  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:57:22  	at java.lang.Thread.run(Thread.java:823)
13:57:22  Caused by: javax.naming.CommunicationException: localhost:39797 [Root exception is javax.net.ssl.SSLException: Read timed out]
13:57:22  	at com.sun.jndi.ldap.Connection.<init>(Connection.java:243)
13:57:22  	at com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
13:57:22  	at com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1615)
13:57:22  	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2849)
13:57:22  	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:347)
13:57:22  	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:225)
13:57:22  	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
13:57:22  	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:243)
13:57:22  	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
13:57:22  	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
13:57:22  	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
13:57:22  	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
13:57:22  	at javax.naming.InitialContext.init(InitialContext.java:244)
13:57:22  	at javax.naming.InitialContext.<init>(InitialContext.java:216)
13:57:22  	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
13:57:22  	at DeadServerTimeoutSSLTest.call(DeadSSLLdapTimeoutTest.java:120)
13:57:22  	... 7 more
13:57:22  Caused by: javax.net.ssl.SSLException: Read timed out
13:57:22  	at sun.security.ssl.Alert.createSSLException(Alert.java:127)
13:57:22  	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
13:57:22  	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
13:57:22  	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
13:57:22  	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:138)
13:57:22  	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1383)
13:57:22  	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1291)
13:57:22  	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
13:57:22  	at com.sun.jndi.ldap.Connection.createSocket(Connection.java:398)
13:57:22  	at com.sun.jndi.ldap.Connection.<init>(Connection.java:220)
13:57:22  	... 22 more
13:57:22  Caused by: java.net.SocketTimeoutException: Read timed out
13:57:22  	at java.net.SocketInputStream.socketRead0(Native Method)
13:57:22  	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
13:57:22  	at java.net.SocketInputStream.read(SocketInputStream.java:171)
13:57:22  	at java.net.SocketInputStream.read(SocketInputStream.java:141)
13:57:22  	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:457)
13:57:22  	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
13:57:22  	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
13:57:22  	... 27 more

jdk11 output (test passes)

----------System.err:(41/3190)----------
javax.naming.CommunicationException: localhost:36381 [Root exception is java.net.SocketTimeoutException: Read timed out]
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:244)
	at java.naming/com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
	at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1616)
	at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2847)
	at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:262)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:226)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:280)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:185)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:115)
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:719)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
	at java.naming/javax.naming.InitialContext.<init>(InitialContext.java:208)
	at java.naming/javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at DeadServerTimeoutSSLTest.call(DeadSSLLdapTimeoutTest.java:121)
	at DeadSSLLdapTimeoutTest.main(DeadSSLLdapTimeoutTest.java:202)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1408)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1314)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at java.naming/com.sun.jndi.ldap.Connection.createSocket(Connection.java:355)
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:223)
	... 22 more
STATUS:Passed.
