### ISSUE TITLE
extended.openjdk failure: com/sun/jndi/dns/ConfigTests/Timeout.java.Timeout : SocketException: No route to host

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#2360]
Hotspot and OpenJ9, consistent failure
Possibly machine setup?
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.openjdk_s390x_linux/14/testReport/com_sun_jndi_dns_ConfigTests_Timeout/java/Timeout_2/
```
17:01:10  openjdk version "11.0.11" 2021-04-20
17:01:10  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.11+5)
17:01:10  Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.26.0-m1, JRE 11 Linux s390x-64-Bit Compressed References 20210309_909 (JIT enabled, AOT enabled)
17:01:10  OpenJ9   - b227feba2
17:01:10  OMR      - 4665e2f72
17:01:10  JCL      - 73ab98c885 based on jdk-11.0.11+5)
```
```
17:07:08  STDERR:
17:07:08  javax.naming.CommunicationException: DNS error [Root exception is java.net.SocketException: No route to host (Receive failed)]; remaining name ''
17:07:08  	at jdk.naming.dns/com.sun.jndi.dns.DnsClient.query(DnsClient.java:313)
17:07:08  	at jdk.naming.dns/com.sun.jndi.dns.Resolver.query(Resolver.java:81)
17:07:08  	at jdk.naming.dns/com.sun.jndi.dns.DnsContext.c_getAttributes(DnsContext.java:434)
17:07:08  	at java.naming/com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(ComponentDirContext.java:235)
17:07:08  	at java.naming/com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:141)
17:07:08  	at java.naming/com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:129)
17:07:08  	at java.naming/javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:142)
17:07:08  	at java.naming/javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:137)
17:07:08  	at Timeout.runTest(Timeout.java:78)
17:07:08  	at TestBase.launch(TestBase.java:82)
17:07:08  	at TestBase.run(TestBase.java:50)
17:07:08  	at Timeout.main(Timeout.java:61)
17:07:08  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:07:08  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:07:08  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:07:08  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
17:07:08  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
17:07:08  	at java.base/java.lang.Thread.run(Thread.java:836)
17:07:08  Caused by: java.net.SocketException: No route to host (Receive failed)
17:07:08  	at java.base/java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:181)
17:07:08  	at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:814)
17:07:08  	at jdk.naming.dns/com.sun.jndi.dns.DnsClient.doUdpQuery(DnsClient.java:423)
17:07:08  	at jdk.naming.dns/com.sun.jndi.dns.DnsClient.query(DnsClient.java:212)
17:07:08  	... 17 more
17:07:08  
17:07:08  JavaTest Message: Test threw exception: javax.naming.CommunicationException
```

**Comment by lumpfish** [comment]
Dup of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1992
