### ISSUE TITLE
jdk16 aarch64 extended.openjdk: NPE "sun.awt.FontConfiguration.head" is null

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#2373]
Failing testcases:
- javax/imageio/plugins/gif/AnimationTest.java.AnimationTest
- javax/imageio/plugins/shared/ImageWriterCompressionTest.java.ImageWriterCompressionTest
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_aarch64_linux/12/consoleFull
```
19:02:36  java.lang.InternalError: java.lang.reflect.InvocationTargetException
19:02:36  	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
19:02:36  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:682)
19:02:36  	at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
19:02:36  	at java.desktop/java.awt.Font.getFont2D(Font.java:524)
19:02:36  	at java.desktop/java.awt.Font$FontAccessImpl.getFont2D(Font.java:264)
19:02:36  	at java.desktop/sun.font.FontUtilities.getFont2D(FontUtilities.java:147)
19:02:36  	at java.desktop/sun.java2d.SunGraphics2D.checkFontInfo(SunGraphics2D.java:672)
19:02:36  	at java.desktop/sun.java2d.SunGraphics2D.getFontInfo(SunGraphics2D.java:838)
19:02:36  	at java.desktop/sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:46)
19:02:36  	at java.desktop/sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2936)
19:02:36  	at ImageWriterCompressionTest.main(ImageWriterCompressionTest.java:82)
19:02:36  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:02:36  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
19:02:36  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:02:36  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
19:02:36  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
19:02:36  	at java.base/java.lang.Thread.run(Thread.java:853)
19:02:36  Caused by: java.lang.reflect.InvocationTargetException
19:02:36  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
19:02:36  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
19:02:36  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
19:02:36  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
19:02:36  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
19:02:36  	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
19:02:36  	... 16 more
19:02:36  Caused by: java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null
19:02:36  	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1260)
19:02:36  	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:223)
19:02:36  	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:106)
19:02:36  	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:711)
19:02:36  	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:352)
19:02:36  	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:309)
19:02:36  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:682)
19:02:36  	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:309)
19:02:36  	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
19:02:36  	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
```
Node: build-docker-ubuntu1804-armv8-2

Same issue as seen here: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2137#issuecomment-759938090
@smlambert exclude maybe?

**Comment by smlambert** [comment]
Yes @andrew-m-leonard, excluding makes sense until it can be addressed.

**Comment by andrew-m-leonard** [comment]
Possibly now fixed, just tried a new grinder on the same node and passes: https://ci.adoptopenjdk.net/job/Grinder/7789/console

**Comment by karianna** [comment]
@andrew-m-leonard safe to close?
