### ISSUE TITLE
jdk-16 Hotspot extended.openjdk Unrecognized VM options

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#2382]
https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.openjdk_x86-32_windows/9/consoleFull
```
12:03:11  Unrecognized VM option 'ReduceBulkZeroing'
12:03:11  Unrecognized VM option 'StressGCM'
12:03:37  Unrecognized VM option 'MaxVectorSize=8'
12:06:36  Unrecognized VM option 'SplitIfBlocks'
12:09:06  Unrecognized VM option 'SuperWordLoopUnrollAnalysis'
12:23:32  Unrecognized VM option 'LoopUnrollLimit=250'
12:24:24  Unrecognized VM option 'PartialPeelLoop'
12:24:24  Unrecognized VM option 'LoopMaxUnroll=0'
12:24:51  Unrecognized VM option 'UseLoopPredicate'
12:29:07  Unrecognized VM option 'DoEscapeAnalysis'
12:29:54  Unrecognized VM option 'UseCountedLoopSafepoints'
```

**Comment by sophia-guo** [comment]
https://bugs.openjdk.java.net/browse/JDK-8252473

**Comment by smlambert** [comment]
If this is the case, we should disable the affected tests referencing the upstream issue (and closing this one).

**Comment by smlambert** [comment]
As a general rule, I do NOT want to hold open duplicate issues in this repo for things that are raised in other repos (including openjdk-infrastructure and JBS).  

I recognize we are currently doing that right now, and we are holding a handful of issues open in openjdk-tests that are actually reported elsewhere.  Where possible, we should fix this in Problemlist and playlists to reference the actual issue and remove the placeholder.  

In this way we can reduce the quickly growing backlog in this repo.  Also, in the case where @andrew-m-leonard is raising all of these unique issues for each failure causing a big bloating surge of issues, we should likely reference the earlier duplicate reports that are sitting in more general issues (example: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2137).

**Comment by smlambert** [comment]
Failing targets on this platform:
jvm_compiler, jdk_io, jdk_management, jdk_tools
that contain 64 failing testcases out of 4806 extended.openjdk testcases (as reported [here](https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.openjdk_x86-32_windows/9/testReport/)).

Before excluding all 4 targets completely, we should see if there are ways to fix some of the issues that are not related to Unrecognized VM options.  Then check if some only have a few testcases failing (if so, exclude via problemlist, to keep as many other test cases running).



For jdk_tools:

```
10:27:15  STDERR:
10:27:15  java.lang.AssertionError: HelpFlagsTest failed:
10:27:15  Tool jaccessinspector-32.exe not covered by this test. Add specification to jdkTools array!
10:27:15  Tool jaccesswalker-32.exe not covered by this test. Add specification to jdkTools array!
10:27:15  
10:27:15  	at HelpFlagsTest.main(HelpFlagsTest.java:374)
10:27:15  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:27:15  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
10:27:15  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:27:15  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
10:27:15  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
10:27:15  	at java.base/java.lang.Thread.run(Thread.java:831)
10:27:15  
10:27:15  JavaTest Message: Test threw exception: java.lang.AssertionError
10:27:15  JavaTest Message: shutting down test
10:27:15  
```

**Comment by lumpfish** [comment]
These failures appear to be Win32 specific and across all releases.
Presumably the options are only recognised by a GC implementation which is not built on win32?
I'll create a PR to exclude the tests pending a more thorough investigation.

**Comment by lumpfish** [comment]
From the different releases:

jdk8 win32 hotspot extended.openjdk:
```
Running test hotspot_jre_2 ...
TEST: compiler/rangechecks/RangeCheckEliminationScaleNotOne.java
Unrecognized VM option 'UseLoopPredicate'
TEST: compiler/c2/cr6340864/TestByteVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestDoubleVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestFloatVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestIntVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestLongVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestShortVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/codegen/TestCharVect2.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/EscapeAnalysis/TestGetClass.java
Unrecognized VM option 'DisableIntrinsic=_getClass'
```
jdk11 win32 hotspot extended.openjdk:
```
Running test jvm_compiler_2 ...
TEST: compiler/arraycopy/TestCloneAccess.java
Unrecognized VM option 'ReduceBulkZeroing'
TEST: compiler/arraycopy/TestCloneAccessStressGCM.java
Unrecognized VM option 'StressGCM'
TEST: compiler/c2/cr6340864/TestByteVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestDoubleVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestFloatVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestIntVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestLongVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestShortVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/TestReplaceEquivPhis.java
Unrecognized VM option 'SplitIfBlocks'
TEST: compiler/codegen/TestCharVect2.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/loopopts/TestUnswitchCloneSkeletonPredicates.java
Unrecognized VM option 'PartialPeelLoop'
TEST: compiler/loopstripmining/AntiDependentLoadInOuterStripMinedLoop.java
Unrecognized VM option 'LoopMaxUnroll=0'
TEST: compiler/loopstripmining/LoadDependsOnIfIdenticalToLoopExit.java
Unrecognized VM option 'LoopMaxUnroll=0'
TEST: compiler/loopstripmining/TestConservativeAntiDep.java
Unrecognized VM option 'LoopMaxUnroll=0'
TEST: compiler/loopstripmining/TestEliminatedLoadPinnedOnBackedge.java
Unrecognized VM option 'LoopUnrollLimit=0'
TEST: compiler/rangechecks/RangeCheckEliminationScaleNotOne.java
Unrecognized VM option 'UseLoopPredicate'
TEST: compiler/vectorization/TestVectorsNotSavedAtSafepoint.java
Unrecognized VM option 'UseCountedLoopSafepoints'
```
jdk16 win32 hotspot extended.openjdk:
```
Running test jvm_compiler_2 ...
TEST: compiler/arraycopy/TestCloneAccess.java
Unrecognized VM option 'ReduceBulkZeroing'
TEST: compiler/arraycopy/TestCloneAccessStressGCM.java
Unrecognized VM option 'StressGCM'
TEST: compiler/c2/cr6340864/TestByteVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestDoubleVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestFloatVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestIntVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestIntVectRotate.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestLongVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestLongVectRotate.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/cr6340864/TestShortVect.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/c2/TestReplaceEquivPhis.java
Unrecognized VM option 'SplitIfBlocks'
TEST: compiler/c2/TestShiftRightAndAccumulate.java
Unrecognized VM option 'SuperWordLoopUnrollAnalysis'
TEST: compiler/codegen/TestCharVect2.java
Unrecognized VM option 'MaxVectorSize=8'
TEST: compiler/loopopts/superword/Vec_MulAddS2I.java
Unrecognized VM option 'LoopUnrollLimit=250'
TEST: compiler/loopopts/TestUnswitchCloneSkeletonPredicates.java
Unrecognized VM option 'PartialPeelLoop'
TEST: compiler/loopstripmining/AntiDependentLoadInOuterStripMinedLoop.java
Unrecognized VM option 'LoopMaxUnroll=0'
TEST: compiler/loopstripmining/LoadDependsOnIfIdenticalToLoopExit.java
Unrecognized VM option 'LoopMaxUnroll=0'
TEST: compiler/loopstripmining/TestConservativeAntiDep.java
Unrecognized VM option 'LoopMaxUnroll=0'
TEST: compiler/loopstripmining/TestEliminatedLoadPinnedOnBackedge.java
Unrecognized VM option 'LoopUnrollLimit=0'
TEST: compiler/rangechecks/RangeCheckEliminationScaleNotOne.java
Unrecognized VM option 'UseLoopPredicate'
TEST: compiler/types/TestSubTypeCheckMacroNodeWrongMem.java
Unrecognized VM option 'DoEscapeAnalysis'
TEST: compiler/vectorization/TestVectorsNotSavedAtSafepoint.java
Unrecognized VM option 'UseCountedLoopSafepoints'
```
jdk17 may also have similar failures, but the test jobs are not running successfully at the moment.

**Comment by sophia-guo** [comment]
[compiler/c2/TestDeadDataLoopCmoveIdentity.java.TestDeadDataLoopCmoveIdentity](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0/27/testReport/junit/compiler_c2_TestDeadDataLoopCmoveIdentity/java/TestDeadDataLoopCmoveIdentity/)
[compiler/c2/cr6340864/TestByteVect.java.TestByteVect](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0/27/testReport/junit/compiler_c2_cr6340864_TestByteVect/java/TestByteVect/)
[compiler/c2/cr6340864/TestDoubleVect.java.TestDoubleVect](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0/27/testReport/junit/compiler_c2_cr6340864_TestDoubleVect/java/TestDoubleVect/)
[compiler/c2/cr6340864/TestFloatVect.java.TestFloatVect](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0/27/testReport/junit/compiler_c2_cr6340864_TestFloatVect/java/TestFloatVect/)
[compiler/c2/cr6340864/TestIntVect.java.TestIntVect](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0/27/testReport/junit/compiler_c2_cr6340864_TestIntVect/java/TestIntVect/)
[compiler/c2/cr6340864/TestLongVect.java.TestLongVect](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0/27/testReport/junit/compiler_c2_cr6340864_TestLongVect/java/TestLongVect/)
[compiler/c2/cr6340864/TestShortVect.java.TestShortVect](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0/27/testReport/junit/compiler_c2_cr6340864_TestShortVect/java/TestShortVect/)
[compiler/loopstripmining/AntiDependentLoadInOuterStripMinedLoop.java.AntiDependentLoadInOuterStripMinedLoop](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0/27/testReport/junit/compiler_loopstripmining_AntiDependentLoadInOuterStripMinedLoop/java/AntiDependentLoadInOuterStripMinedLoop/)
[compiler/loopstripmining/LoadDependsOnIfIdenticalToLoopExit.java.LoadDependsOnIfIdenticalToLoopExit](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0/27/testReport/junit/compiler_loopstripmining_LoadDependsOnIfIdenticalToLoopExit/java/LoadDependsOnIfIdenticalToLoopExit/)
[compiler/loopstripmining/TestConservativeAntiDep.java.TestConservativeAntiDep](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0/27/testReport/junit/compiler_loopstripmining_TestConservativeAntiDep/java/TestConservativeAntiDep/)
[compiler/loopstripmining/TestEliminatedLoadPinnedOnBackedge.java.TestEliminatedLoadPinnedOnBackedge](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0/27/testReport/junit/compiler_loopstripmining_TestEliminatedLoadPinnedOnBackedge/java/TestEliminatedLoadPinnedOnBackedge/)
[compiler/rangechecks/RangeCheckEliminationScaleNotOne.java.RangeCheckEliminationScaleNotOne](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0/27/testReport/junit/compiler_rangechecks_RangeCheckEliminationScaleNotOne/java/RangeCheckEliminationScaleNotOne/)

Some of them are not listed in https://bugs.openjdk.java.net/browse/JDK-8252473, but has the same issue

**Comment by sophia-guo** [comment]
jdk8 win32: compiler/EscapeAnalysis/TestGetClass.java
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-32_windows_testList_1/55/testReport/compiler_EscapeAnalysis_TestGetClass/java/TestGetClass/

**Comment by smlambert** [comment]
Additionally compiler/loopopts/TestRemoveEmptyLoop.java (see https://github.com/adoptium/aqa-tests/issues/4517#issuecomment-1515047978)

**Comment by andrew-m-leonard** [comment]
Failures seen for jdk-17.0.9+9 release: https://github.com/adoptium/aqa-tests/issues/4826#issuecomment-1782555544
```
TEST: compiler/loopopts/TestBackedgeLoadArrayFillMain.java
        Unrecognized VM option 'OptimizeFill'
TEST: compiler/loopopts/TestInfiniteLoopWithUnmergedBackedgesMain.java
        Unrecognized VM option 'LoopUnswitching'
TEST: compiler/loopopts/TestRemoveEmptyCountedLoop.java
        Unrecognized VM option 'StressGCM'
TEST: compiler/rangechecks/TestRangeCheckCmpUOverflowVsSub.java
        Unrecognized VM option 'StressCCP'
TEST: compiler/splitif/TestCrashAtIGVNSplitIfSubType.java
        Unrecognized VM option 'StressIGVN'
```
