### ISSUE TITLE
Request system test jobs for jdk8u on arm32

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#2393]
**Problem**

We don't run system tests on the jdk8u arm32 (hotspot) nightlies, despite system tests being part of the core AQA test set.

**Proposed solution**

I request the creation of Test_openjdk8_hs_sanity.system_arm_linux and Test_openjdk8_hs_extended.system_arm_linux

**Other Details**

Grinders for [sanity.system](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7830/) (51 mins) and [extended.system](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7831/) (2 hrs, 9 mins) have been run, and both finished green.

[This Slack chat](https://adoptopenjdk.slack.com/archives/C5219G28G/p1616074895023100) tells me that we have enough machine time available to run these tests alongside the others on the arm32 jdk8u nightlies.

**Comment by smlambert** [comment]
Since arm32 should run the '[default](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/master/pipelines/jobs/configurations/jdk8u_pipeline_config.groovy#L106)' set of tests, and changes to build pipelines to support auto-generating test jobs (see https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/75 and https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/90), these jobs should get auto-generated on next time jdk8 pipelines run.  

Let's leave this issue open until we can confirm the auto-generation does actually succeed.

**Comment by smlambert** [comment]
Issue in autogeneration, example output [here](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-arm-hotspot/594/execution/node/171/)

```
org.jenkinsci.plugins.workflow.steps.MissingContextVariableException: Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
	at org.jenkinsci.plugins.workflow.steps.StepDescriptor.checkContextAvailability(StepDescriptor.java:266)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:296)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:193)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor486.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:142)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at Build.runTests(Script2.groovy:275)
```

FYI @sophia-guo

**Comment by sophia-guo** [comment]
Jobs are correctly generated and runs good 
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-arm-hotspot/605/console
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extend.system_arm_linux/1/
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.system_arm_linux/1/

close this.

**Comment by adamfarley** [comment]
Thanks @sophia-guo !
