### ISSUE TITLE
jdk8 hotspot zLinux JDI test failures: UnsupportedOperationException: target does not support popping frames

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#2408]
Since 17th March these have started failing:
https://trss.adoptopenjdk.net/deepHistory?testId=605bd5605730424dbcb6e571
eg.https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_s390x_linux/464/testReport/junit/com_sun_jdi_PopSynchronousTest/java/PopSynchronousTest/
```
run args: [PopSynchronousTarg]
TEST pop from 'a' to 'a'
java.lang.UnsupportedOperationException: target does not support popping frames
	at com.sun.tools.jdi.ThreadReferenceImpl.popFrames(ThreadReferenceImpl.java:539)
	at PopSynchronousTest.pop(PopSynchronousTest.java:216)
	at PopSynchronousTest.reenter(PopSynchronousTest.java:223)
	at PopSynchronousTest.runTests(PopSynchronousTest.java:252)
	at TestScaffold.startTests(TestScaffold.java:429)
	at PopSynchronousTest.main(PopSynchronousTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
	at java.lang.Thread.run(Thread.java:748)

JavaTest Message: Test threw exception: java.lang.UnsupportedOperationException
```

**Comment by andrew-m-leonard** [comment]
These failing tests don't look as though they were run prior to 17th Mar: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_s390x_linux/461/testReport/

**Comment by andrew-m-leonard** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/commit/af6c98f26a0bea29e610519420b297a3e545a21a#diff-9e2b6489dae12580d3f0543dea5e3457a060f3327902b5b31edf187b133a1110
@M-Davies I will re-exclude for Windows and s390xLinux

**Comment by andrew-m-leonard** [comment]
jdk8 zLinux is a "zero" (no-jit) impl which does not support pop-frames see:
https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/a1d853a5d797f38f7be8c260f4a83c1b3fe48adc/hotspot/src/share/vm/prims/jvmtiManageCapabilities.cpp#L121

**Comment by andrew-m-leonard** [comment]
Windows failure is a different reason, not popFrame:
```
19:20:38  STDERR:
19:20:38  ShellScaffold.sh: Version
19:20:38  E:/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/ShellScaffold.sh: line 277: C:\Windows/tmp.6622: Permission denied
19:20:38  cat: 'C:\Windows/tmp.6622': No such file or directory
19:20:38  mkdir: cannot create directory '/aa6622': Permission denied
19:20:38  touch: cannot touch '/aa6622/jxdbOutput.txt': No such file or directory
19:20:38  E:/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/ShellScaffold.sh: line 380: cd: /aa6622: No such file or directory
19:20:38  tail: cannot open '/aa6622/jxdbOutput.txt' for reading: No such file or directory
19:20:38  tee: /aa6622/jxdbOutput.txt: No such file or directory
19:20:38  tail: cannot open '/aa6622/jxdbOutput.txt' for reading: No such file or directory
19:20:38  --Top process (6622) is dead.  We better die too
19:20:38  --Top process (6622) is dead.  We better die too
```

**Comment by andrew-m-leonard** [comment]
I've created a separate issue for Windows which is a different problem: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2415

**Comment by andrew-m-leonard** [comment]
Permanent exclude due to jdk8 hs zero vm limitation: https://github.com/AdoptOpenJDK/openjdk-tests/pull/2416
