### ISSUE TITLE
openj9 jdk8 x86_64_linux sanity.openjdk java/util/concurrent/Executors/AutoShutdown.java 

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#2469]
java/util/concurrent/Executors/AutoShutdown.java failed with ` 2 not equal to 3` message.

Not seen before or on other platforms.

Failing job: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/497/console

Failure output:
```
10:12:17  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Some tests failed
10:12:17  REASON: User specified action: run main/othervm AutoShutdown 
10:12:17  TIME:   0.146 seconds
10:12:17  messages:
10:12:17  command: main AutoShutdown
10:12:17  reason: User specified action: run main/othervm AutoShutdown 
10:12:17  Mode: othervm [/othervm specified]
10:12:17  elapsed time (seconds): 0.146
10:12:17  configuration:
10:12:17  STDOUT:
10:12:17  2 not equal to 3
10:12:17  
10:12:17  Passed = 0, failed = 1
```
Full output of failing test
```
10:12:17  TEST: java/util/concurrent/Executors/AutoShutdown.java
10:12:17  TEST JDK: /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image
10:12:17  
10:12:17  ACTION: build -- Passed. Build successful
10:12:17  REASON: Named class compiled on demand
10:12:17  TIME:   0.071 seconds
10:12:17  messages:
10:12:17  command: build AutoShutdown
10:12:17  reason: Named class compiled on demand
10:12:17  Test directory:
10:12:17    compile: AutoShutdown
10:12:17  elapsed time (seconds): 0.071
10:12:17  
10:12:17  ACTION: compile -- Passed. Compilation successful
10:12:17  REASON: .class file out of date or does not exist
10:12:17  TIME:   0.071 seconds
10:12:17  messages:
10:12:17  command: compile -XDignore.symbol.file=true /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors/AutoShutdown.java
10:12:17  reason: .class file out of date or does not exist
10:12:17  Mode: agentvm
10:12:17  Agent id: 1
10:12:17  elapsed time (seconds): 0.071
10:12:17  configuration:
10:12:17  Boot Layer (javac runtime environment)
10:12:17    class path: /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/lib/tools.jar
10:12:17                /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/javatest.jar
10:12:17                /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/jtreg.jar
10:12:17  
10:12:17  javac compilation environment
10:12:17    source path: /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors
10:12:17    class path:  /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors
10:12:17                 /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/output_16176132565542/jdk_util_0/work/classes/0/java/util/concurrent/Executors
10:12:17                 /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/lib/tools.jar
10:12:17  
10:12:17  rerun:
10:12:17  cd /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/output_16176132565542/jdk_util_0/work/scratch/1 && \
10:12:17  DISPLAY=:0 \
10:12:17  HOME=/home/jenkins \
10:12:17  LANG=en_US.UTF-8 \
10:12:17  PATH=/bin:/usr/bin:/usr/sbin \
10:12:17      /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/javac \
10:12:17          -J-ea \
10:12:17          -J-esa \
10:12:17          -J-Xmx1540m \
10:12:17          -J-Xdump:system:none \
10:12:17          -J-Xdump:heap:none \
10:12:17          -J-Xdump:system:events=gpf+abort+traceassert+corruptcache \
10:12:17          -J-XX:+UseCompressedOops \
10:12:17          -J-Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops' \
10:12:17          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:+UseCompressedOops' \
10:12:17          -J-Dtest.compiler.opts= \
10:12:17          -J-Dtest.java.opts= \
10:12:17          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image \
10:12:17          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image \
10:12:17          -J-Dtest.timeout.factor=8.0 \
10:12:17          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test \
10:12:17          -J-Dtest.name=java/util/concurrent/Executors/AutoShutdown.java \
10:12:17          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors/AutoShutdown.java \
10:12:17          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors \
10:12:17          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors \
10:12:17          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/output_16176132565542/jdk_util_0/work/classes/0/java/util/concurrent/Executors \
10:12:17          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/output_16176132565542/jdk_util_0/work/classes/0/java/util/concurrent/Executors \
10:12:17          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/output_16176132565542/jdk_util_0/work/classes/0/java/util/concurrent/Executors:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors \
10:12:17          -d /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/output_16176132565542/jdk_util_0/work/classes/0/java/util/concurrent/Executors \
10:12:17          -sourcepath /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors \
10:12:17          -classpath /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/output_16176132565542/jdk_util_0/work/classes/0/java/util/concurrent/Executors:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/lib/tools.jar \
10:12:17          -XDignore.symbol.file=true /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors/AutoShutdown.java
10:12:17  
10:12:17  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Some tests failed
10:12:17  REASON: User specified action: run main/othervm AutoShutdown 
10:12:17  TIME:   0.146 seconds
10:12:17  messages:
10:12:17  command: main AutoShutdown
10:12:17  reason: User specified action: run main/othervm AutoShutdown 
10:12:17  Mode: othervm [/othervm specified]
10:12:17  elapsed time (seconds): 0.146
10:12:17  configuration:
10:12:17  STDOUT:
10:12:17  2 not equal to 3
10:12:17  
10:12:17  Passed = 0, failed = 1
10:12:17  
10:12:17  STDERR:
10:12:17  java.lang.Throwable
10:12:17  	at java.lang.Thread.dumpStack(Thread.java:498)
10:12:17  	at AutoShutdown.fail(AutoShutdown.java:81)
10:12:17  	at AutoShutdown.fail(AutoShutdown.java:82)
10:12:17  	at AutoShutdown.equal(AutoShutdown.java:86)
10:12:17  	at AutoShutdown.realMain(AutoShutdown.java:66)
10:12:17  	at AutoShutdown.main(AutoShutdown.java:88)
10:12:17  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:12:17  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:12:17  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:12:17  	at java.lang.reflect.Method.invoke(Method.java:498)
10:12:17  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
10:12:17  	at java.lang.Thread.run(Thread.java:823)
10:12:17  java.lang.AssertionError: Some tests failed
10:12:17  	at AutoShutdown.main(AutoShutdown.java:90)
10:12:17  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:12:17  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:12:17  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:12:17  	at java.lang.reflect.Method.invoke(Method.java:498)
10:12:17  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
10:12:17  	at java.lang.Thread.run(Thread.java:823)
10:12:17  
10:12:17  JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed
10:12:17  JavaTest Message: shutting down test
10:12:17  
10:12:17  STATUS:Failed.`main' threw exception: java.lang.AssertionError: Some tests failed
10:12:17  rerun:
10:12:17  cd /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/output_16176132565542/jdk_util_0/work/scratch/1 && \
10:12:17  DISPLAY=:0 \
10:12:17  HOME=/home/jenkins \
10:12:17  LANG=en_US.UTF-8 \
10:12:17  PATH=/bin:/usr/bin:/usr/sbin \
10:12:17  CLASSPATH=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/output_16176132565542/jdk_util_0/work/classes/0/java/util/concurrent/Executors:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/lib/tools.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/jtreg.jar \
10:12:17      /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java \
10:12:17          -Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops' \
10:12:17          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:+UseCompressedOops' \
10:12:17          -Dtest.compiler.opts= \
10:12:17          -Dtest.java.opts= \
10:12:17          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image \
10:12:17          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image \
10:12:17          -Dtest.timeout.factor=8.0 \
10:12:17          -Dtest.root=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test \
10:12:17          -Dtest.name=java/util/concurrent/Executors/AutoShutdown.java \
10:12:17          -Dtest.file=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors/AutoShutdown.java \
10:12:17          -Dtest.src=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors \
10:12:17          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors \
10:12:17          -Dtest.classes=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/output_16176132565542/jdk_util_0/work/classes/0/java/util/concurrent/Executors \
10:12:17          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/output_16176132565542/jdk_util_0/work/classes/0/java/util/concurrent/Executors \
10:12:17          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/output_16176132565542/jdk_util_0/work/classes/0/java/util/concurrent/Executors:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors \
10:12:17          -ea \
10:12:17          -esa \
10:12:17          -Xmx1540m \
10:12:17          -Xdump:system:none \
10:12:17          -Xdump:heap:none \
10:12:17          -Xdump:system:events=gpf+abort+traceassert+corruptcache \
10:12:17          -XX:+UseCompressedOops \
10:12:17          com.sun.javatest.regtest.agent.MainWrapper /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/output_16176132565542/jdk_util_0/work/java/util/concurrent/Executors/AutoShutdown.d/main.0.jta
10:12:17  
10:12:17  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Some tests failed
10:12:17  --------------------------------------------------
10:16:22  Test results: passed: 649; failed: 1
```

**Comment by lumpfish** [comment]
Also seen on AIX:
```
openjdk version "1.8.0_292-internal"
OpenJDK Runtime Environment (build 1.8.0_292-internal-202104061156-b09)
Eclipse OpenJ9 VM (build openj9-0.26.0-m2, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20210406_1008 (JIT enabled, AOT enabled)
OpenJ9   - 4ce9ec8a1
OMR      - b8996ac2c
JCL      - e21e76d905 based on jdk8u292-b09)
```
```
15:06:13  TEST: java/util/concurrent/Executors/AutoShutdown.java
15:06:13  TEST JDK: /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image
15:06:13  
15:06:13  ACTION: build -- Passed. Build successful
15:06:13  REASON: Named class compiled on demand
15:06:13  TIME:   0.183 seconds
15:06:13  messages:
15:06:13  command: build AutoShutdown
15:06:13  reason: Named class compiled on demand
15:06:13  Test directory:
15:06:13    compile: AutoShutdown
15:06:13  elapsed time (seconds): 0.183
15:06:13  
15:06:13  ACTION: compile -- Passed. Compilation successful
15:06:13  REASON: .class file out of date or does not exist
15:06:13  TIME:   0.183 seconds
15:06:13  messages:
15:06:13  command: compile -XDignore.symbol.file=true /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors/AutoShutdown.java
15:06:13  reason: .class file out of date or does not exist
15:06:13  Mode: agentvm
15:06:13  Agent id: 1
15:06:13  elapsed time (seconds): 0.183
15:06:13  configuration:
15:06:13  Boot Layer (javac runtime environment)
15:06:13    class path: /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/tools.jar
15:06:13                /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/javatest.jar
15:06:13                /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/jtreg.jar
15:06:13  
15:06:13  javac compilation environment
15:06:13    source path: /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors
15:06:13    class path:  /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors
15:06:13                 /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/TKG/output_1617715964296/jdk_util_0/work/classes/java/util/concurrent/Executors
15:06:13                 /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/tools.jar
15:06:13  
15:06:13  rerun:
15:06:13  cd /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/TKG/output_1617715964296/jdk_util_0/work/scratch && \
15:06:13  DISPLAY=:0 \
15:06:13  HOME=/home/jenkins \
15:06:13  LANG=en_US \
15:06:13  PATH=/bin:/usr/bin:/usr/sbin \
15:06:13  TZ=CST6CDT \
15:06:13      /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/bin/javac \
15:06:13          -J-ea \
15:06:13          -J-esa \
15:06:13          -J-Xmx1540m \
15:06:13          -J-Xdump:system:none \
15:06:13          -J-Xdump:heap:none \
15:06:13          -J-Xdump:system:events=gpf+abort+traceassert+corruptcache \
15:06:13          -J-XX:+UseCompressedOops \
15:06:13          -J-Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops' \
15:06:13          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:+UseCompressedOops' \
15:06:13          -J-Dtest.compiler.opts= \
15:06:13          -J-Dtest.java.opts= \
15:06:13          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image \
15:06:13          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image \
15:06:13          -J-Dtest.timeout.factor=8.0 \
15:06:13          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test \
15:06:13          -J-Dtest.name=java/util/concurrent/Executors/AutoShutdown.java \
15:06:13          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors/AutoShutdown.java \
15:06:13          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors \
15:06:13          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors \
15:06:13          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/TKG/output_1617715964296/jdk_util_0/work/classes/java/util/concurrent/Executors \
15:06:13          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/TKG/output_1617715964296/jdk_util_0/work/classes/java/util/concurrent/Executors \
15:06:13          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/TKG/output_1617715964296/jdk_util_0/work/classes/java/util/concurrent/Executors:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors \
15:06:13          -d /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/TKG/output_1617715964296/jdk_util_0/work/classes/java/util/concurrent/Executors \
15:06:13          -sourcepath /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors \
15:06:13          -classpath /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/TKG/output_1617715964296/jdk_util_0/work/classes/java/util/concurrent/Executors:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/tools.jar \
15:06:13          -XDignore.symbol.file=true /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/util/concurrent/Executors/AutoShutdown.java
15:06:13  
15:06:13  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Some tests failed
15:06:13  REASON: User specified action: run main/othervm AutoShutdown 
15:06:13  TIME:   0.525 seconds
15:06:13  messages:
15:06:13  command: main AutoShutdown
15:06:13  reason: User specified action: run main/othervm AutoShutdown 
15:06:13  Mode: othervm [/othervm specified]
15:06:13  elapsed time (seconds): 0.525
15:06:13  configuration:
15:06:13  STDOUT:
15:06:13  1 not equal to 3
15:06:13  
15:06:13  Passed = 0, failed = 1
15:06:13  
15:06:13  STDERR:
15:06:13  java.lang.Throwable
15:06:13  	at java.lang.Thread.dumpStack(Thread.java:498)
15:06:13  	at AutoShutdown.fail(AutoShutdown.java:81)
15:06:13  	at AutoShutdown.fail(AutoShutdown.java:82)
15:06:13  	at AutoShutdown.equal(AutoShutdown.java:86)
15:06:13  	at AutoShutdown.realMain(AutoShutdown.java:66)
15:06:13  	at AutoShutdown.main(AutoShutdown.java:88)
15:06:13  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:06:13  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:06:13  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:06:13  	at java.lang.reflect.Method.invoke(Method.java:498)
15:06:13  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
15:06:13  	at java.lang.Thread.run(Thread.java:823)
15:06:13  java.lang.AssertionError: Some tests failed
15:06:13  	at AutoShutdown.main(AutoShutdown.java:90)
15:06:13  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:06:13  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:06:13  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:06:13  	at java.lang.reflect.Method.invoke(Method.java:498)
15:06:13  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
15:06:13  	at java.lang.Thread.run(Thread.java:823)
15:06:13  
15:06:13  JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed
15:06:13  JavaTest Message: shutting down test
```

**Comment by sophia-guo** [comment]
If it only happened to openj9 and it used to succeed probably open the issue in eclipse/openj9?
