### ISSUE TITLE
All regression tests fail with latest jtreg from adopt

### ISSUE THREAD

**Issue by akolarkunnu** [AdoptOpenJDK/openjdk-tests#300]
Test category: Any
Testsuite name: Any
Test name(s): Any
Product(s) tested: JDK8, JDK10
OS/architecture: Any
Platform specific: [yes|no] : No

Reproducibility: always
Regression: yes

jtreg version details:
jtreg, version 4.2 dev b12
Built with 1.8.0_121 on 02/23/2018 08:12 PM.
JTHarness: version 5.0
JCov 3.0-2
TestNG (testng.jar): version unknown
TestNG (jcommander.jar): version 1.48.0
AsmTools: version 7.0

Steps to reproduce:
1) Download or clone test base from https://github.com/AdoptOpenJDK/openjdk-jdk8u
2) Download latest JDK(Any version, have corresponding test base)
3) Download latest jtreg from https://ci.adoptopenjdk.net/view/Dependencies/job/jtreg/
4) Execute any jtreg test case:
Eg: ./jtreg-adopt/bin/jtreg -verbose:all -jdk:./jdk8u172-b03-adopt/ -dir:./adopt-jdk8u/jdk/test java/math/BigDecimal/AddTests.java

Exception/Error from Log:
#-----testresult-----
end=Wed Mar 07 13\:17\:55 MSK 2018
execStatus=Error. Unexpected error caught from test java/math/BigDecimal/AddTests.java\: java.lang.NoSuchMethodError\: com.sun.javatest.regtest.agent.JDK_Version.compareTo(Lcom/sun/javatest/regtest/agent/JDK_Version;)I
sections=script_messages Details

#section:script_messages
----------messages:(0/0)----------

#section:Details
----------messages:(0/0)----------
----------Stack trace:(7/555)----------
java.lang.NoSuchMethodError: com.sun.javatest.regtest.agent.JDK_Version.compareTo(Lcom/sun/javatest/regtest/agent/JDK_Version;)I
	at com.sun.javatest.regtest.config.JDK.getSystemModules(JDK.java:405)
	at com.sun.javatest.regtest.exec.RegressionScript.run(RegressionScript.java:108)
	at com.sun.javatest.Script.run(Script.java:241)
	at com.sun.javatest.DefaultTestRunner.runTest(DefaultTestRunner.java:174)
	at com.sun.javatest.DefaultTestRunner.access$100(DefaultTestRunner.java:43)
	at com.sun.javatest.DefaultTestRunner$1.run(DefaultTestRunner.java:66)
result: Not run. Test running...

test result: Error. Unexpected error caught from test java/math/BigDecimal/AddTests.java: java.lang.NoSuchMethodError: com.sun.javatest.regtest.agent.JDK_Version.compareTo(Lcom/sun/javatest/regtest/agent/JDK_Version;)I

**Comment by akolarkunnu** [comment]
It is working fine with a bit old jtreg, version details:
jtreg, version 4.2 dev b00
Built with Java(TM) 2 SDK, Version 1.8.0_121-b13 on December 21, 2017.
JTHarness: version 5.0
JCov 3.0-2
TestNG (testng.jar): version unknown
TestNG (jcommander.jar): version 1.72
AsmTools: version 6.0

**Comment by akolarkunnu** [comment]
Raised openjdk-build issue for this: https://github.com/AdoptOpenJDK/openjdk-build/issues/249.
So closing this from openjdk-tests.
