### ISSUE TITLE
Add open liberty under thirdparty container tests

### ISSUE THREAD

**Issue by chandrams** [AdoptOpenJDK/openjdk-tests#367]
Evaluate and include open liberty tests under third party container tests
https://github.com/OpenLiberty/open-liberty

https://github.com/AdoptOpenJDK/openjdk-tests/issues/172

**Comment by chandrams** [comment]
Installed ant version  1.10.3 and the ran the below FAT test, it worked fine now. Need to figure out how to run all FAT tests

./gradlew build.example_fat:buildandrun

generateReports:
 [startAnt] Buildfile: /home/chandrams/AdoptOpenJDK/git/open-liberty/dev/build.example_fat/build/libs/autoFVT/src/ant/launch.xml
 [startAnt]
 [startAnt] reallyGenerateReports:
 [startAnt]      [echo] Generating an HTML report based on the existing XML report
 [startAnt]     [mkdir] Created dir: /home/chandrams/AdoptOpenJDK/git/open-liberty/dev/build.example_fat/build/libs/autoFVT/results/junit.html
 [startAnt] [junitreport] Processing /home/chandrams/AdoptOpenJDK/git/open-liberty/dev/build.example_fat/build/libs/autoFVT/results/junit/TESTS-TestSuites.xml to /tmp/null128732985
 [startAnt] [junitreport] Loading stylesheet jar:file:/home/chandrams/apache-ant-1.10.3/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
 [startAnt] [junitreport] Transform time: 574ms
 [startAnt] [junitreport] Deleting: /tmp/null128732985
 [startAnt]      [echo] HTML report is available at /home/chandrams/AdoptOpenJDK/git/open-liberty/dev/build.example_fat/build/libs/autoFVT/results/junit.html/index.html
 [startAnt]
 [startAnt] BUILD SUCCESSFUL
 [startAnt] Total time: 1 second

archiveReports:

execute:

BUILD SUCCESSFUL
Total time: 13 seconds


BUILD SUCCESSFUL in 24s
63 actionable tasks: 33 executed, 30 up-to-date

**Comment by chandrams** [comment]
Got a list of FAT testsuites using ls command, there were 75 tests out of which 42 tests passed and rest failed.  The tests take a long time to run around 20 hrs or so.  

Checked with Andrew Guibert from the WAS team, he suggested that we could just run only the unit tests as the WAS org has extensive infra to run all 90k+ FAT tests for OpenLiberty and WAS Liberty on hundreds of combinations of OSes and JDKs on a weekly basis, and they would report issues on Openj9 if any.

**Comment by chandrams** [comment]
Found few intermittent issues while initializing and building the liberty test material. Fetching some of the artifacts fail:

./gradlew cnf:initialize
```
error  : dev :Exception: java.io.IOException: Could not fetch com.ibm.ws.org.eclipse.equinox:coordinator:1.3.200.v20160325-1323       
at aQute.maven.provider.MavenRepository.getFile(MavenRepository.java:173)    
at aQute.maven.provider.MavenRepository.lambda$get$0(MavenRepository.java:130)
at aQute.maven.provider.MavenRepository$$Lambda$60.000000006D079580.call(Unknown Source)
at org.osgi.util.promise.DeferredPromiseImpl$Submit.run(DeferredPromiseImpl.java:658)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:812)error  : dev :Failed to sync com.ibm.ws.org.eclipse.equinox:coordinator:1.3.200.v20160325-1323
```

./gradlew assemble :com.ibm.websphere.appserver.features:releaseNeeded
Fails with the above issue and the artifacts it tries to sync aren't same, I see the same issue with the below as well:
```
error  : dev :Failed to sync net.sf.jtidy:jtidy:9.3.8
error  : dev :Failed to sync com.ibm.ws.org.eclipse.equinox:region:1.3.2.v20170118-1930
```

**Comment by chandrams** [comment]
When the initialization and build is successful, unit tests failed with the below issue:
./gradlew test

```
com.ibm.ws.logging.internal.hpel.HpelLogProviderImplTest > testWritingMessages FAILED
    org.junit.ComparisonFailure at HpelLogProviderImplTest.java:112

com.ibm.ws.logging.internal.hpel.HpelBaseTraceServiceTest > testWritingMessages FAILED
    org.junit.ComparisonFailure at HpelBaseTraceServiceTest.java:143

19 tests completed, 2 failed, 1 skipped
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':com.ibm.ws.logging.hpel:test'.
> There were failing tests. See the report at: file:///home/muchandr/git/open-liberty/dev/com.ibm.ws.logging.hpel/build/libs/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 33s
1037 actionable tasks: 211 executed, 826 up-to-date
```

Exception details from the logs:

```
<a name="testWritingMessages"></a>
<h3 class="failures">testWritingMessages</h3>
<span class="code">
<pre>org.junit.ComparisonFailure: Record has incorrect formatted message expected:&lt;[debug message]&gt; but was:&lt;[TRAS3004E: Failed to write messages to the <user home>/git/open-liberty/dev/com.ibm.ws.logging.hpel/../com.ibm.ws.logging.hpel/build/unittest-logs/messages.log file.]&gt;
        at org.junit.Assert.assertEquals(Assert.java:125)
        at com.ibm.ws.logging.internal.hpel.HpelBaseTraceServiceTest.testWritingMessages(HpelBaseTraceServiceTest.java:143)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
        at test.common.SharedOutputManager$1.evaluate(SharedOutputManager.java:614)
        at org.junit.rules.RunRules.evaluate(RunRules.java:18)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
```

Will submit multiple runs to check if they are intermittent or machine specific.

**Comment by chandrams** [comment]
Link to the run - https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/581/console

**Comment by sophia-guo** [comment]
Close it in favor of #552
