### ISSUE TITLE
openjddk_test_x86-64_windows build broke

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#40]
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_windows/5/console 
exception:
Caused by: java.io.IOException: Cannot run program "git" (in directory "C:\Users\jenkins\workspace\openjdk_test_x86-64_windows\openjdk-test"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at hudson.Proc$LocalProc.<init>(Proc.java:245)
	at hudson.Proc$LocalProc.<init>(Proc.java:214)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:846)
	at hudson.Launcher$ProcStarter.start(Launcher.java:384)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1873)

**Comment by sophia-guo** [comment]
@gdams @bblondin

**Comment by bblondin** [comment]
Looks good now: https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_windows/9/console

After updating the %PATH%, restarting the jenkins slave service was required for Jenkins to pick up the path change.
