### ISSUE TITLE
tomcat app tests fail for openjdk8_hs

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#416]
Tests run and pass on openjdk8_j9, but not openjdk8_hs.

Test output from [recent external tests job](https://ci.adoptopenjdk.net/view/External%20tests/job/openjdk8_hs_externaltest_x86-64_linux/103/consoleFull)

...
20:39:35 validate:
20:39:35 Unable to obtain resource from /root/tomcat-build-libs/checkstyle-6.17/checkstyle-6.17-all.jar: java.util.zip.ZipException: error in opening zip file
20:39:35   [taskdef] Unable to obtain resource from /root/tomcat-build-libs/checkstyle-6.17/checkstyle-6.17-all.jar: 
20:39:35   [taskdef] java.util.zip.ZipException: error in opening zip file
20:39:35   [taskdef] 	at java.util.zip.ZipFile.open(Native Method)
20:39:35   [taskdef] 	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
20:39:35   [taskdef] 	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
20:39:35   [taskdef] 	at java.util.jar.JarFile.<init>(JarFile.java:166)
20:39:35   [taskdef] 	at java.util.jar.JarFile.<init>(JarFile.java:130)
20:39:35   [taskdef] 	at org.apache.tools.ant.AntClassLoader.getResourceURL(AntClassLoader.java:1026)
20:39:35   [taskdef] 	at org.apache.tools.ant.AntClassLoader$ResourceEnumeration.findNextResource(AntClassLoader.java:151)
20:39:35   [taskdef] 	at org.apache.tools.ant.AntClassLoader$ResourceEnumeration.<init>(AntClassLoader.java:112)
20:39:35   [taskdef] 	at org.apache.tools.ant.AntClassLoader.findResources(AntClassLoader.java:966)
20:39:35   [taskdef] 	at org.apache.tools.ant.AntClassLoader.getNamedResources(AntClassLoader.java:934)
20:39:35   [taskdef] 	at org.apache.tools.ant.loader.AntClassLoader5.getResources(AntClassLoader5.java:58)
20:39:35   [taskdef] 	at org.apache.tools.ant.taskdefs.Definer.resourceToURLs(Definer.java:360)
20:39:35   [taskdef] 	at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:246)
20:39:35   [taskdef] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
20:39:35   [taskdef] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
20:39:35   [taskdef] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:39:35   [taskdef] 	at java.lang.reflect.Method.invoke(Method.java:498)
20:39:35   [taskdef] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
20:39:35   [taskdef] 	at org.apache.tools.ant.Task.perform(Task.java:348)
20:39:35   [taskdef] 	at org.apache.tools.ant.Target.execute(Target.java:435)
20:39:35   [taskdef] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
20:39:35   [taskdef] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
20:39:35   [taskdef] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
20:39:35   [taskdef] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
20:39:35   [taskdef] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
20:39:35   [taskdef] 	at org.apache.tools.ant.Main.runBuild(Main.java:853)
20:39:35   [taskdef] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
20:39:35   [taskdef] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
20:39:35   [taskdef] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
20:39:35   [taskdef] Could not load definitions from resource ${checkstyletask.properties}. It could not be found.
20:39:35 
20:39:35 BUILD FAILED
20:39:35 /tomcat85/build.xml:549: Problem: failed to create task or type checkstyle
20:39:35 Cause: The name is undefined.
20:39:35 Action: Check the spelling.
20:39:35 Action: Check that any custom tasks/types have been declared.
20:39:35 Action: Check that any <presetdef>/<macrodef> declarations have taken place.
20:39:35 
20:39:35 
20:39:35 Total time: 1 second
20:39:35 
20:39:35 tomcat_test_0_FAILED

**Comment by smlambert** [comment]
Last successful test run:
https://ci.adoptopenjdk.net/view/External%20tests/job/openjdk8_hs_externaltest_x86-64_linux/99/tapTestReport/

**Comment by smlambert** [comment]
Seems to have been a 1x anomaly, only occurred in job 103, and not reproducible, so will close for now.
