### ISSUE TITLE
Enable jcov for openjdk9 and up

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#494]
Using JCov2.0 with jtreg  we can get code-coverage for OpenJDK8. As Modularity for OpenJDK9 and up there is no rt.jar available we need to build the image and keep the classes under modules folder to do the instrument. And running the tests with -javaagent:jcov.jar=grabber.

**Comment by sophia-guo** [comment]
With JCov3.0-b05 we got lots of  errors which I believe jcov3.0 are still under development to work with Openjdk9 onward, like some other tools.

Mainly two kinds of errors:
```java.lang.AssertionError
	at com.sun.tdk.jcov.instrument.BranchCodeMethodAdapter.computeEndBCIsAndFoldInExits(BranchCodeMethodAdapter.java:423)
	at com.sun.tdk.jcov.instrument.BranchCodeMethodAdapter.visitEnd(BranchCodeMethodAdapter.java:498)
	at org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:783)
	at org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:783)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1278)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
	at com.sun.tdk.jcov.instrument.ClassMorph.morph(ClassMorph.java:256)
	at com.sun.tdk.jcov.Agent$Tr.transform(Agent.java:180)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:550)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:157)
	at com.sun.tdk.jcov.Agent.premainV50(Agent.java:469)
	at com.sun.tdk.jcov.Agent.premain(Agent.java:416)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:500)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:512)

```

```[2018-07-27 14:44:09,013] Agent[0]: stderr: 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:512)
[2018-07-27 14:44:10,195] Agent[0]: stdout: Method [java.lang.reflect.Array.$$generated$$_getLength(Ljava/lang/Object;)I] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,195] Agent[0]: stdout: Method [java.lang.reflect.Array.$$generated$$_newArray(Ljava/lang/Class;I)Ljava/lang/Object;] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,195] Agent[0]: stdout: Method [java.lang.reflect.Array.getLength(Ljava/lang/Object;)I] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,196] Agent[0]: stdout: Method [java.lang.reflect.Array.newArray(Ljava/lang/Class;I)Ljava/lang/Object;] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,578] Agent[0]: stdout: Method [java.lang.Double.$$generated$$_doubleToRawLongBits(D)J] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,578] Agent[0]: stdout: Method [java.lang.Double.$$generated$$_longBitsToDouble(J)D] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,580] Agent[0]: stdout: Method [java.lang.Float.$$generated$$_floatToRawIntBits(F)I] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,580] Agent[0]: stdout: Method [java.lang.Float.$$generated$$_intBitsToFloat(I)F] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,659] Agent[0]: stdout: Method [jdk.internal.misc.Unsafe.$$generated$$_getBoolean(Ljava/lang/Object;J)Z] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,659] Agent[0]: stdout: Method [jdk.internal.misc.Unsafe.$$generated$$_getByte(Ljava/lang/Object;J)B] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,659] Agent[0]: stdout: Method [jdk.internal.misc.Unsafe.$$generated$$_getShort(Ljava/lang/Object;J)S] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,660] Agent[0]: stdout: Method [jdk.internal.misc.Unsafe.$$generated$$_getChar(Ljava/lang/Object;J)C] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,660] Agent[0]: stdout: Method [jdk.internal.misc.Unsafe.$$generated$$_getInt(Ljava/lang/Object;J)I] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,660] Agent[0]: stdout: Method [jdk.internal.misc.Unsafe.$$generated$$_getLong(Ljava/lang/Object;J)J] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,660] Agent[0]: stdout: Method [jdk.internal.misc.Unsafe.$$generated$$_getFloat(Ljava/lang/Object;J)F] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,660] Agent[0]: stdout: Method [jdk.internal.misc.Unsafe.$$generated$$_getDouble(Ljava/lang/Object;J)D] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,660] Agent[0]: stdout: Method [jdk.internal.misc.Unsafe.$$generated$$_allocateInstance(Ljava/lang/Class;)Ljava/lang/Object;] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,660] Agent[0]: stdout: Method [jdk.internal.misc.Unsafe.$$generated$$_copyMemory0(Ljava/lang/Object;JLjava/lang/Object;JJ)V] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
[2018-07-27 14:44:10,660] Agent[0]: stdout: Method [jdk.internal.misc.Unsafe.$$generated$$_loadFence()V] is annotated with @HotSpotIntrinsicCandidate, but no compiler intrinsic is defined for the method.
```

**Comment by smlambert** [comment]
May be worth revisiting this now, in case some of the development work for JCov3.0 has now been completed, also, I keep wanting to close this as a dup of https://github.com/AdoptOpenJDK/openjdk-tests/issues/428
