### ISSUE TITLE
jdk_management: DcmdMBeanPermissionsTest error (java.lang.SecurityException)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#55]
Output from https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/34/consoleFull:

20:14:46 Note: /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/com/sun/management/DiagnosticCommandMBean/DcmdMBeanPermissionsTest.java uses unchecked or unsafe operations.
20:14:46 Note: Recompile with -Xlint:unchecked for details.
20:14:46 
20:14:46 ACTION: main -- Failed. Unexpected exit from test [exit code: 1]
20:14:46 REASON: User specified action: run main/othervm DcmdMBeanPermissionsTest 
20:14:46 TIME:   1.25 seconds
20:14:46 messages:
20:14:46 command: main DcmdMBeanPermissionsTest
20:14:46 reason: User specified action: run main/othervm DcmdMBeanPermissionsTest 
20:14:46 Mode: othervm [/othervm specified]
20:14:46 elapsed time (seconds): 1.25
20:14:46 configuration:
20:14:46 STDOUT:
20:14:46 Testing gcClassHistogram
20:14:46 Testing gcClassStats
20:14:46 Testing gcRotateLog
20:14:46 Testing gcRun
20:14:46 Testing gcRunFinalization
20:14:46 Testing help
20:14:46 Testing threadPrint
20:14:46 Testing vmCommandLine
20:14:46 Testing vmFlags
20:14:46 Testing vmNativeMemory
20:14:46 Testing vmSystemProperties
20:14:46 Testing vmUptime
20:14:46 Testing vmVersion
20:14:46 TEST PASSED
20:14:46 STDERR:
20:14:46 Exception in thread "main" java.lang.SecurityException: ("java.io.FilePermission" "/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar" "read")
20:14:46 	at DcmdMBeanPermissionsTest$CustomSecurityManager.checkPermission(DcmdMBeanPermissionsTest.java:90)
20:14:46 	at java.net.URLClassLoader$4.run(URLClassLoader.java:709)
20:14:46 	at java.net.URLClassLoader$4.run(URLClassLoader.java:707)
20:14:46 	at java.security.AccessController.doPrivileged(Native Method)
20:14:46 	at java.net.URLClassLoader.getPermissions(URLClassLoader.java:707)
20:14:46 	at sun.misc.Launcher$AppClassLoader.getPermissions(Launcher.java:343)
20:14:46 	at java.security.SecureClassLoader.getProtectionDomain(SecureClassLoader.java:206)
20:14:46 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
20:14:46 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
20:14:46 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
20:14:46 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
20:14:46 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
20:14:46 	at java.security.AccessController.doPrivileged(Native Method)
20:14:46 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
20:14:46 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
20:14:46 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
20:14:46 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
20:14:46 	at com.sun.javatest.regtest.agent.RStatus.passed(RStatus.java:36)
20:14:46 	at com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:83)

**Comment by smlambert** [comment]
A more direct link to the failure:
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux_experimental/108/testReport/com_sun_management_DiagnosticCommandMBean_DcmdMBeanPermissionsTest/java_id0/DcmdMBeanPermissionsTest_id0/

**Comment by smlambert** [comment]
Closing this as stale, will open fresh issue if persists.
