### ISSUE TITLE
OpenJDK 11 jdk_nio, jdk_net failures

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#602]
Linux:
java/nio/file/attribute/BasicFileAttributeView/UnixSocketFile.java 
java/nio/channels/AsyncCloseAndInterrupt.java	
java/nio/charset/spi/CharsetProviderBasicTest.java	
java/nio/channels/DatagramChannel/ConnectExceptions.java	
java/nio/channels/DatagramChannel/SendExceptions.java	
java/nio/channels/SocketChannel/ExceptionTranslation.java	
java/net/InetAddress/BadDottedIPAddress.java	
java/net/InetAddress/CachedUnknownHostName.java	
java/net/InetAddress/IPv4Formats.java	
java/net/SocketPermission/SocketPermissionCollection.java	
java/net/SocketPermission/Wildcard.java	
java/net/Socks/SocksV4Test.java	
java/net/URL/OpenStream.java	
java/net/httpclient/ConnectExceptionTest.java	

PPCLE:
java/nio/file/Files/InterruptCopy.java

**Comment by sophia-guo** [comment]
PPCLE:
java/nio/file/Files/InterruptCopy.java `Error while cleaning up threads after test`
[InterruptCopy.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/2428496/InterruptCopy.jtr.txt)

**Comment by sophia-guo** [comment]
all other nio failure;
[channels.zip](https://github.com/AdoptOpenJDK/openjdk-tests/files/2428576/channels.zip)

all other jdk_net failrue:
[net.zip](https://github.com/AdoptOpenJDK/openjdk-tests/files/2428580/net.zip)

**Comment by sophia-guo** [comment]
Following tests intermittently fails on HS with unexpected errors. Looks like only happens on test-packet-ubuntu1604-x64-2 or with specific two sdk builds? The failures is:

```
21:06:26 # A fatal error has been detected by the Java Runtime Environment:
21:06:26 #
21:06:26 #  SIGSEGV (0xb) at pc=0x00007fb8245387ca, pid=28972, tid=29819
21:06:26 #
21:06:26 # JRE version: OpenJDK Runtime Environment (11.0.2+9) (build 11.0.2+9-201902021908)
21:06:26 # Java VM: OpenJDK 64-Bit Server VM (11.0.2+9-201902021908, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
21:06:26 # Problematic frame:
21:06:26 # J 3174 c2 java.security.MessageDigest$Delegate.engineUpdate([BII)V java.base@11.0.2 (11 bytes) @ 0x00007fb8245387ca [0x00007fb8245382e0+0x00000000000004ea]
21:06:26 #
21:06:26 # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
21:06:26 #
21:06:26 # An error report file with more information is saved as:
21:06:26 # /home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/jvmtest/openjdk_regression/work/scratch/2/hs_err_pid28972.log
21:06:26 Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
21:06:26 #
21:06:26 # If you would like to submit a bug report, please visit:
21:06:26 #   https://github.com/AdoptOpenJDK/openjdk-build/issues
21:06:26 #856 
```

java/net/httpclient/AsFileDownloadTest.java
java/net/httpclient/InvalidInputStreamSubscriptionRequest.java
java/net/httpclient/StreamingBody.java
java/net/httpclient/http2/ContinuationFrameTest.java

Issue also opened in https://github.com/AdoptOpenJDK/openjdk-build/issues/893

**Comment by sophia-guo** [comment]
Intermittent test failures on Win
java/nio/channels/AsynchronousFileChannel/Basic.java 
java/nio/channels/AsynchronousSocketChannel/Basic.java

JBS reported and open :https://bugs.openjdk.java.net/browse/JDK-7052549

**Comment by sophia-guo** [comment]
java/io/Serializable/concurrentClassDescLookup/ConcurrentClassDescLookup.java intermittent timeout on Win HS

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_x86-64_windows/128/testReport/junit/java_io_Serializable_concurrentClassDescLookup_ConcurrentClassDescLookup/java/ConcurrentClassDescLookup/

**Comment by sophia-guo** [comment]
jdk/nio/zipfs/ZipFSTester.java intermittently failed on Mac

```
Standard Error

java.nio.file.FileSystemException: /xyz95/efg9 -> is a directory
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:565)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.newInputStream(ZipPath.java:708)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:273)
	at java.base/java.nio.file.Files.newInputStream(Files.java:155)
	at ZipFSTester.test1(ZipFSTester.java:230)
	at ZipFSTester.main(ZipFSTester.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:834)

JavaTest Message: Test complete.

```

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_x86-64_macos/122/testReport/junit/jdk_nio_zipfs_ZipFSTester/java/ZipFSTester/

**Comment by sophia-guo** [comment]
java/net/httpclient/UnknownBodyLengthTest.java intermittently failed on Win
same failure reported in JBS: https://bugs.openjdk.java.net/browse/JDK-8210130 as resolved.

**Comment by smlambert** [comment]
So for issues that have been marked as resolved, we need to check if we have the fix in the openjdk source we use (and if we do, why we still see a failure), and if not, we need to encourage someone to port the fix to the branch we take our source from.

**Comment by sophia-guo** [comment]
java/nio/channels/DatagramChannel/Promiscuous.java fails with 'java.net.SocketException: Exec format error'

```
Standard Error

java.net.SocketException: Exec format error
	at java.base/sun.nio.ch.Net.joinOrDrop4(Native Method)
	at java.base/sun.nio.ch.Net.join4(Net.java:542)
	at java.base/sun.nio.ch.DatagramChannelImpl.innerJoin(DatagramChannelImpl.java:999)
	at java.base/sun.nio.ch.DatagramChannelImpl.join(DatagramChannelImpl.java:1017)
	at Promiscuous.test(Promiscuous.java:175)
	at Promiscuous.main(Promiscuous.java:220)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:834)

JavaTest Message: Test threw exception: java.net.SocketException
JavaTest Message: shutting down test

    
```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_x86-64_macos/132/consoleFull

**Comment by sophia-guo** [comment]
Close this one as issue has been addressed by https://github.com/AdoptOpenJDK/openjdk-build/issues/893
