### ISSUE TITLE
Perf tests post stage failed when running odm tests

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#617]
Perf tests post stage failed when running odm tests
https://ci.adoptopenjdk.net/view/Test_perf/job/openjdk8_hs_perftest_x86-64_linux
```/168/console[Pipeline] End of Pipeline
groovy.lang.MissingPropertyException: No such property: testTarName for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:264)
```
Seems benchmark_test_output_dir is hard coded, while testTarname is a passing in parameter.

```
	def benchmark_test_output_dir = 'jvmtest/performance/odm/ilog_wodm881/leftoverResults';
			if (fileExists(benchmark_test_output_dir)) {
				sh "tar -zcf ${testTarName} benchmark_test_output.tar.gz"
```

**Comment by sophia-guo** [comment]
Close in favor of https://github.com/AdoptOpenJDK/openjdk-tests/pull/737
