### ISSUE TITLE
All tests build on mac failed for connection issue

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#674]
All test builds failed on both macs(test-macincloud-macos1010-2, test-macincloud-macos1010-1).

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_x86-64_macos/47/console

Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to test-macincloud-macos1010-1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
		at com.sun.proxy.$Proxy102.withRepository(Unknown Source)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl.withRepository(RemoteGitImpl.java:235)
		at hudson.plugins.git.GitSCM.printCommitMessageToLog(GitSCM.java:1271)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1244)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:90)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:77)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at

**Comment by sophia-guo** [comment]
@sxa555 should we open an issue in infras?

**Comment by karianna** [comment]
@sophia-guo I have restarted the main Jenkins which may have cleared this if you'd like to run the test again (I notice that it's auto-triggered by upstream builds..)?

**Comment by sophia-guo** [comment]
@karianna yes, it's auto-triggered. However I will trigger a grinder to see if the issue stays or just wait for the next trigger.

**Comment by sophia-guo** [comment]
Grider works fine https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/371/console. Thanks @karianna  close this.
