### ISSUE TITLE
All external test builds failed for "No such property: LABEL for class: groovy.lang.Binding""

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#742]
All external tests builds failed for "No such property: LABEL for class: groovy.lang.Binding"

https://ci.adoptopenjdk.net/view/Test_external/
groovy.lang.MissingPropertyException: No such property: LABEL for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:264)
	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:288)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:292)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at Script1.addJobDescription(Script1.groovy:395)
	at Script1.testBuild(Script1.groovy:313)
	at ___cps.transform___(Native Method)

This is due to recent update [additional information job description](https://github.com/AdoptOpenJDK/openjdk-tests/pull/733) need to access ${LABEL}. However openjdk_x86-64_linux_docker do not set variable "LABEL" as other jenkins file. @Mesbah-Alam

**Comment by smlambert** [comment]
So I believe we can use the openjdk_x86-64_linux and DOCKER_REQUIRED param now.  I will update.

**Comment by smlambert** [comment]
All job configs were already updated with DOCKER_REQUIRED, and I have now updated to use openjdk_x86-64_linux, so LABEL should be present.  Will leave this open, until we see tomorrow's test results.

**Comment by smlambert** [comment]
apologies, I actually thought this was already merged:
https://github.com/AdoptOpenJDK/openjdk-tests/pull/725

**Comment by smlambert** [comment]
Now the #725 is merged, we should see these jobs passing.

**Comment by sophia-guo** [comment]
Looks good, close it.
