### ISSUE TITLE
Intermittent failures on Windows

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#821]
**No issues on JBS: report to openj9?**
Test java/rmi/server/RemoteServer/AddrInUse.java.AddrInUse failed with 'TEST FAILED: export on already-bound port succeeded' on all platforms with openj9 java8
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_windows/178/testReport/junit/java_rmi_server_RemoteServer_AddrInUse/java/AddrInUse/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_linux_linuxXL/92/testReport/junit/java_rmi_server_RemoteServer_AddrInUse/java/AddrInUse/
java/io/File/DeleteOnExitNPE.java failed intermittently with ' No output should have been received from the process' on win64 with openj9 java8
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_windows/177/testReport/junit/java_io_File_DeleteOnExitNPE/java/DeleteOnExitNPE/

java/util/zip/ZipFile/DeleteTempJar.java intermittently failed on Win32 with openj9 java8
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-32_windows/115/consoleFull

**Others has issues in JBS, however status is resolved or closed. Asking for reopen?**
java/nio/channels/ServerSocketChannel/Basic.java : intermittent timeout failure on win32|64 with hotspot&openj9 java8

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_x86-32_windows/110/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_x86-64_windows/182/testReport/java_nio_channels_ServerSocketChannel_Basic/java/Basic/
 
Exactly same issue reported and resolved in JBS. May need to re-open? 
https://bugs.openjdk.java.net/browse/JDK-8143100

Test java/nio/channels/ServerSocketChannel/AdaptServerSocket.java failed with Accept did not time out on win64 with hotspot java8. 
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_x86-64_windows/182/testReport/junit/java_nio_channels_ServerSocketChannel_AdaptServerSocket/java/AdaptServerSocket/
Exactly same issue reported in JBS, however, the status is fixed.
https://bugs.openjdk.java.net/browse/JDK-8133093, doubt it should be re-opened.

**Comment by sophia-guo** [comment]
Test java/rmi/server/RemoteServer/AddrInUse.java.AddrInUse failed with 'TEST FAILED: export on already-bound port succeeded' on win64 with openj9 java8
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_windows/178/testReport/junit/java_rmi_server_RemoteServer_AddrInUse/java/AddrInUse/

**Comment by sophia-guo** [comment]
Test java/util/Timer/NameConstructors.java fails intermittently on win64 with openj9 java8.

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_windows/178/testReport/junit/java_util_Timer_NameConstructors/java/NameConstructors/

java.lang.RuntimeException: false : false
	at NameConstructors.test(NameConstructors.java:56)
	at NameConstructors.main(NameConstructors.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:813)

JBS https://bugs.openjdk.java.net/browse/JDK-8056313, which was closed. Need to reopen

**Comment by sophia-guo** [comment]
java/io/File/DeleteOnExitNPE.java failed intermittently with ' No output should have been received from the process' on win64 with openj9 java8 
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_windows/177/testReport/junit/java_io_File_DeleteOnExitNPE/java/DeleteOnExitNPE/

```
FAILED TO LOAD OPENSSL CRYPTO LIBRARY
java.lang.RuntimeException: Failed: No output should have been received from the process
	at DeleteOnExitNPE.runTest(DeleteOnExitNPE.java:68)
	at DeleteOnExitNPE.main(DeleteOnExitNPE.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:813)


```

**Comment by sophia-guo** [comment]
sun/rmi/runtime/Log/6409194/NoConsoleOutput.java fails Intermittently: unexpected subprocess output on win64 with openj9 java8:
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_windows/177/testReport/junit/sun_rmi_runtime_Log_6409194_NoConsoleOutput/java/NoConsoleOutput/

```
JAVAVM: command = [C:\Users\jenkins\workspace\openjdk8_j9_openjdktest_x86-64_windows\openjdkbinary\j2sdk-image\jre\bin\java, -Djava.util.logging.config.file=C:\Users\jenkins\workspace\openjdk8_j9_openjdktest_x86-64_windows\openjdk-tests\openjdk_regression\openjdk-jdk\jdk\test\sun\rmi\runtime\Log\6409194\logging.properties, NoConsoleOutput$DoRMIStuff]
-------- subprocess standard output: --------
-------- subprocess standard error:  --------
FAILED TO LOAD OPENSSL CRYPTO LIBRARY
---------------------------------------------
java.lang.Error: TEST FAILED: unexpected subprocess output
	at NoConsoleOutput.main(NoConsoleOutput.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:813)

```

Same issue reported and resolved in JBS:  https://bugs.openjdk.java.net/browse/JDK-8037278, need to reopen?

**Comment by sophia-guo** [comment]
08:23:16 STDOUT:
08:23:16 Unexpected failure with exit status 1
08:23:16 STDERR:
java/util/zip/ZipFile/DeleteTempJar.java failed on Win32 with openj9 java8
```

08:23:16     301 [main] sh 25120 fork: child -1 - forked process 23516 died unexpectedly, retry 0, exit code 0xC000012D, errno 11
08:23:16 C:\Users\jenkins\workspace\openjdk8_j9_openjdktest_x86-32_windows\openjdk-tests\openjdk_regression\openjdk-jdk\jdk\test\java\util\zip\ZipFile\deletetempjar.sh: fork: retry: Resource temporarily unavailable
08:23:16 JVMJ9VM015W Initialization error for library j9gc29(5): Failed to allocate default memory space
08:23:16 Error: Could not create the Java Virtual Machine.
08:23:16 Error: A fatal exception has occurred. Program will exit.
```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-32_windows/115/consoleFull

**Comment by sophia-guo** [comment]
java/util/concurrent/ThreadPoolExecutor/CoreThreadTimeOut.java intermittently failed on Win32 with openj9 java8
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-32_windows/114/testReport/junit/java_util_concurrent_ThreadPoolExecutor_CoreThreadTimeOut/java/CoreThreadTimeOut/

```
10 not equal to 0
java.lang.Throwable
	at java.lang.Thread.dumpStack(Thread.java:490)
	at CoreThreadTimeOut.fail(CoreThreadTimeOut.java:96)
	at CoreThreadTimeOut.fail(CoreThreadTimeOut.java:97)
	at CoreThreadTimeOut.equal(CoreThreadTimeOut.java:102)
	at CoreThreadTimeOut.test(CoreThreadTimeOut.java:84)
	at CoreThreadTimeOut.instanceMain(CoreThreadTimeOut.java:106)
	at CoreThreadTimeOut.main(CoreThreadTimeOut.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:813)
java.lang.Exception: Some tests failed
	at CoreThreadTimeOut.test(CoreThreadTimeOut.java:90)
	at CoreThreadTimeOut.instanceMain(CoreThreadTimeOut.java:106)
	at CoreThreadTimeOut.main(CoreThreadTimeOut.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:813)
java.lang.AssertionError: Some tests failed
	at CoreThreadTimeOut.instanceMain(CoreThreadTimeOut.java:108)
	at CoreThreadTimeOut.main(CoreThreadTimeOut.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:813)

```

Reported and resolved in JBS
https://bugs.openjdk.java.net/browse/JDK-6933803

**Comment by sophia-guo** [comment]
Close as listed in #1511
