### ISSUE TITLE
Openjdk s390 test build is running on build-marist-s390x-sles-12

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#826]
Openjdk s390 test build is running on [build-marist-ubuntu1604-s390x-2](https://ci.adoptopenjdk.net/computer/build-marist-ubuntu1604-s390x-2/), which caused around 150 tests failures.
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_s390x_linux/189/

build running on [test-marist-ubuntu1604-s390x-1](https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-1/), only have around 7 test failures.
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_s390x_linux/188/

Both [build-marist-s390x-sles-12](https://ci.adoptopenjdk.net/computer/build-marist-s390x-sles-12/) and [build-marist-ubuntu1604-s390x-2](https://ci.adoptopenjdk.net/computer/build-marist-ubuntu1604-s390x-2/) are under test label:  https://ci.adoptopenjdk.net/label/ci.role.test&&hw.arch.s390x&&sw.os.linux/.

Need to remove label 'ci.role.test' from two machines if they are only for build purpose. @ShelleyLambert

**Comment by sophia-guo** [comment]
Copy Shelley's comment from  https://github.com/AdoptOpenJDK/openjdk-tests/pull/825

"I have removed the label for now. I think I know why they have that label. Docker got installed on them, and so they would be available for application tests, but they may be missing something else for running other testing.

We should look at what is missing and have it added, since when I remove these 2 machines from testing, it leaves us only 1 for this platform"

**Comment by sophia-guo** [comment]
Looking at failures ( jdk_net, jdk_nio) failures are either `Unexpected exception:java.net.NoRouteToHostException: No route to host (Host unreachable)`  or  'java.net.SocketTimeoutException: Receive timed out'. All related with network testing.

**Comment by smlambert** [comment]
I will close this as any additional work will happen via openjdk-infrastructure issue

**Comment by sxa** [comment]
Hitting this on the SLES12 machiane again as a result of trying to resolve https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1655 (not sure which infra issue Shelley already had on this but I couldn't easily find it - that issue was initially to resolve other issues like the lack of Xvfb which is now required)

@lumpfish Any idea why I'm getting these `No route to host` issues. My initial feeling that it was related to the hostname on the machine but that is definitely resolving ok and I've tried adjusting various options today in case that is what's causing it. Open to ideas on this as I'd like to enable this machine to get our capacity up.

**Comment by lumpfish** [comment]
> @lumpfish Any idea why I'm getting these `No route to host` issues.

I'm afraid not.  If we knew exactly which tests were failing we could look at what they're doing.  I think we've had issues before due to some erroneous data in /etc/xxx somewhere if that's any help.

**Comment by sxa** [comment]
It's happening in the [DirectByteBufferLoadTest_0](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.system_s390x_linux/376/consoleFull) too by the look of it. I tried a few obvious tweaks to some of the host entries under `/etc` but that didn't seem to be helping for this issue. Very surprised at seeing routing-related errors.

**Comment by lumpfish** [comment]
DirectByteBufferLoadTest_0 allocates DirectByyteBuffers alongside a java.nio workload (nio also uses native memory).  So any networking errors would likely be because of those tests.

**Comment by sxa** [comment]
Makes sense - but do you know what the problem that it's showing up might be? i.e. what in the configuration might be needed in order to help them pass. It's not obvious what route it's failing to find based on the error message.

**Comment by lumpfish** [comment]
No idea - I'll try to find a test case which pinpoints it.

**Comment by lumpfish** [comment]
An openjdk jdk_net test which fails (on test-marist-sles12-s390x-1 - see https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1655):

`java/net/CookieHandler/CookieManagerTest.java`(https://github.com/AdoptOpenJDK/openjdk-jdk/blob/master/test/jdk/java/net/CookieHandler/CookieManagerTest.java) fails with
```
17:41:18  TEST: java/net/CookieHandler/CookieManagerTest.java
17:41:18  TEST JDK: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image
17:41:18  
17:41:18  ACTION: build -- Passed. Build successful
17:41:18  REASON: Named class compiled on demand
17:41:18  TIME:   0.616 seconds
17:41:18  messages:
17:41:18  command: build CookieManagerTest
17:41:18  reason: Named class compiled on demand
17:41:18  Test directory:
17:41:18    compile: CookieManagerTest
17:41:18  elapsed time (seconds): 0.616
17:41:18  
17:41:18  ACTION: compile -- Passed. Compilation successful
17:41:18  REASON: .class file out of date or does not exist
17:41:18  TIME:   0.616 seconds
17:41:18  messages:
17:41:18  command: compile -XDignore.symbol.file=true /home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler/CookieManagerTest.java
17:41:18  reason: .class file out of date or does not exist
17:41:18  Mode: agentvm
17:41:18  Agent id: 2
17:41:18  elapsed time (seconds): 0.616
17:41:18  configuration:
17:41:18  Boot Layer (javac runtime environment)
17:41:18    class path: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/tools.jar
17:41:18                /home/jenkins/workspace/Grinder/jvmtest/openjdk/jtreg/lib/javatest.jar
17:41:18                /home/jenkins/workspace/Grinder/jvmtest/openjdk/jtreg/lib/jtreg.jar
17:41:18  
17:41:18  javac compilation environment
17:41:18    source path: /home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler
17:41:18    class path:  /home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler
17:41:18                 /home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16050298618377/jdk_net_0/work/classes/0/java/net/CookieHandler
17:41:18                 /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/tools.jar
17:41:18  
17:41:18  rerun:
17:41:18  cd /home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16050298618377/jdk_net_0/work/scratch/1 && \
17:41:18  DISPLAY=:0 \
17:41:18  HOME=/home/jenkins \
17:41:18  LANG=en_US.UTF-8 \
17:41:18  PATH=/bin:/usr/bin:/usr/sbin \
17:41:18      /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/javac \
17:41:18          -J-ea \
17:41:18          -J-esa \
17:41:18          -J-Xmx512m \
17:41:18          -J-Dtest.vm.opts='-ea -esa -Xmx512m' \
17:41:18          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
17:41:18          -J-Dtest.compiler.opts= \
17:41:18          -J-Dtest.java.opts= \
17:41:18          -J-Dtest.jdk=/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image \
17:41:18          -J-Dcompile.jdk=/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image \
17:41:18          -J-Dtest.timeout.factor=8.0 \
17:41:18          -J-Dtest.root=/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test \
17:41:18          -J-Dtest.name=java/net/CookieHandler/CookieManagerTest.java \
17:41:18          -J-Dtest.file=/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler/CookieManagerTest.java \
17:41:18          -J-Dtest.src=/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler \
17:41:18          -J-Dtest.src.path=/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler \
17:41:18          -J-Dtest.classes=/home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16050298618377/jdk_net_0/work/classes/0/java/net/CookieHandler \
17:41:18          -J-Dtest.class.path=/home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16050298618377/jdk_net_0/work/classes/0/java/net/CookieHandler \
17:41:18          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16050298618377/jdk_net_0/work/classes/0/java/net/CookieHandler:/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler \
17:41:18          -d /home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16050298618377/jdk_net_0/work/classes/0/java/net/CookieHandler \
17:41:18          -sourcepath /home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler \
17:41:18          -classpath /home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler:/home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16050298618377/jdk_net_0/work/classes/0/java/net/CookieHandler:/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/tools.jar \
17:41:18          -XDignore.symbol.file=true /home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler/CookieManagerTest.java
17:41:18  
17:41:18  ACTION: main -- Failed. Execution failed: `main' threw exception: java.net.NoRouteToHostException: No route to host (Host unreachable)
17:41:18  REASON: User specified action: run main/othervm -ea CookieManagerTest 
17:41:18  TIME:   1.172 seconds
17:41:18  messages:
17:41:18  command: main -ea CookieManagerTest
17:41:18  reason: User specified action: run main/othervm -ea CookieManagerTest 
17:41:18  Mode: othervm [/othervm specified]
17:41:18  elapsed time (seconds): 1.172
17:41:18  configuration:
17:41:18  STDOUT:
17:41:18  http server listenining on: 37840
17:41:18  ====== CookieManager test 1 ======
17:41:18  STDERR:
17:41:18  java.net.NoRouteToHostException: No route to host (Host unreachable)
17:41:18  	at java.net.PlainSocketImpl.socketConnect(Native Method)
17:41:18  	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
17:41:18  	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
17:41:18  	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
17:41:18  	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
17:41:18  	at java.net.Socket.connect(Socket.java:607)
17:41:18  	at java.net.Socket.connect(Socket.java:556)
17:41:18  	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
17:41:18  	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
17:41:18  	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
17:41:18  	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
17:41:18  	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
17:41:18  	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
17:41:18  	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
17:41:18  	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
17:41:18  	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
17:41:18  	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
17:41:18  	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
17:41:18  	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
17:41:18  	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
17:41:18  	at CookieManagerTest.makeHttpCall(CookieManagerTest.java:100)
17:41:18  	at CookieManagerTest.main(CookieManagerTest.java:43)
17:41:18  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:41:18  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:41:18  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:41:18  	at java.lang.reflect.Method.invoke(Method.java:498)
17:41:18  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
17:41:18  	at java.lang.Thread.run(Thread.java:748)
17:41:18  
17:41:18  JavaTest Message: Test threw exception: java.net.NoRouteToHostException: No route to host (Host unreachable)
17:41:18  JavaTest Message: shutting down test
17:41:18  
17:41:18  STATUS:Failed.`main' threw exception: java.net.NoRouteToHostException: No route to host (Host unreachable)
17:41:18  rerun:
17:41:18  cd /home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16050298618377/jdk_net_0/work/scratch/1 && \
17:41:18  DISPLAY=:0 \
17:41:18  HOME=/home/jenkins \
17:41:18  LANG=en_US.UTF-8 \
17:41:18  PATH=/bin:/usr/bin:/usr/sbin \
17:41:18  CLASSPATH=/home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16050298618377/jdk_net_0/work/classes/0/java/net/CookieHandler:/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler:/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/tools.jar:/home/jenkins/workspace/Grinder/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Grinder/jvmtest/openjdk/jtreg/lib/jtreg.jar \
17:41:18      /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java \
17:41:18          -Dtest.vm.opts='-ea -esa -Xmx512m' \
17:41:18          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
17:41:18          -Dtest.compiler.opts= \
17:41:18          -Dtest.java.opts= \
17:41:18          -Dtest.jdk=/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image \
17:41:18          -Dcompile.jdk=/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image \
17:41:18          -Dtest.timeout.factor=8.0 \
17:41:18          -Dtest.root=/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test \
17:41:18          -Dtest.name=java/net/CookieHandler/CookieManagerTest.java \
17:41:18          -Dtest.file=/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler/CookieManagerTest.java \
17:41:18          -Dtest.src=/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler \
17:41:18          -Dtest.src.path=/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler \
17:41:18          -Dtest.classes=/home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16050298618377/jdk_net_0/work/classes/0/java/net/CookieHandler \
17:41:18          -Dtest.class.path=/home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16050298618377/jdk_net_0/work/classes/0/java/net/CookieHandler \
17:41:18          -Dtest.class.path.prefix=/home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16050298618377/jdk_net_0/work/classes/0/java/net/CookieHandler:/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/net/CookieHandler \
17:41:18          -ea \
17:41:18          -esa \
17:41:18          -Xmx512m \
17:41:18          -ea \
17:41:18          com.sun.javatest.regtest.agent.MainWrapper /home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16050298618377/jdk_net_0/work/java/net/CookieHandler/CookieManagerTest.d/main.0.jta
17:41:18  
17:41:18  TEST RESULT: Failed. Execution failed: `main' threw exception: java.net.NoRouteToHostException: No route to host (Host unreachable)
```

**Comment by smlambert** [comment]
<img width="251" alt="Screen Shot 2020-12-16 at 10 27 37 PM" src="https://user-images.githubusercontent.com/2836948/102440265-f0855100-3fed-11eb-9a41-1dd897bf8167.png">

Closing this (again) as I do not even find this machine online anymore.
