### ISSUE TITLE
sun/rmi/runtime/Log/6409194/NoConsoleOutput.java fails intermittently

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#913]
The test sun/rmi/runtime/Log/6409194/NoConsoleOutput.java failed intermittently on different platforms with following error message:

```
JAVAVM: command = [C:\Users\jenkins\workspace\openjdk8_hs_openjdktest_x86-32_windows\openjdkbinary\j2sdk-image\jre\bin\java, -Djava.util.logging.config.file=C:\Users\jenkins\workspace\openjdk8_hs_openjdktest_x86-32_windows\openjdk-tests\openjdk_regression\openjdk-jdk\jdk\test\sun\rmi\runtime\Log\6409194\logging.properties, NoConsoleOutput$DoRMIStuff]
-------- subprocess standard output: --------
INFO: On try # 1, ServerSocket(0) returned the reserved port 60001 in TestLibrary.getUnusedRandomPort() 
INFO: On try # 2, ServerSocket(0) returned the reserved port 60002 in TestLibrary.getUnusedRandomPort() 
INFO: On try # 3, ServerSocket(0) returned the reserved port 60003 in TestLibrary.getUnusedRandomPort() 
INFO: On try # 4, ServerSocket(0) returned the reserved port 60004 in TestLibrary.getUnusedRandomPort() 
INFO: On try # 5, ServerSocket(0) returned the reserved port 60005 in TestLibrary.getUnusedRandomPort() 
INFO: On try # 6, ServerSocket(0) returned the reserved port 60006 in TestLibrary.getUnusedRandomPort() 
INFO: On try # 7, ServerSocket(0) returned the reserved port 60007 in TestLibrary.getUnusedRandomPort() 
INFO: On try # 8, ServerSocket(0) returned the reserved port 60008 in TestLibrary.getUnusedRandomPort() 
INFO: On try # 9, ServerSocket(0) returned the reserved port 60009 in TestLibrary.getUnusedRandomPort() 
INFO: On try # 10, ServerSocket(0) returned the reserved port 60010 in TestLibrary.getUnusedRandomPort() 
-------- subprocess standard error:  --------
---------------------------------------------
java.lang.Error: TEST FAILED: unexpected subprocess output
	at NoConsoleOutput.main(NoConsoleOutput.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:748)
```

Issue was reported in JBS as closed: https://bugs.openjdk.java.net/browse/JDK-8156798. Need to reopen it.

**Comment by sophia-guo** [comment]
Close it as listed in #1511
