### ISSUE TITLE
openjdk11_j9_openjdktest_x86-64_windows test build failed with checkout scm step on slave

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#928]
openjdk11_j9_openjdktest_x86-64_windows test build failed with checkout scm step on slave

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_windows/

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_windows/143/console

```
Running on test-azure-win2012r2-x64-1 in C:\Users\jenkins\workspace\openjdk11_j9_openjdktest_x86-64_windows
[Pipeline] {
[Pipeline] checkout
No credentials specified
Wiping out workspace first.
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 13.68.134.204/13.68.134.204:62850
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1072)
		at hudson.FilePath.act(FilePath.java:1061)
		at hudson.FilePath.deleteContents(FilePath.java:1283)
		at hudson.plugins.git.extensions.impl.WipeWorkspace.beforeCheckout(WipeWorkspace.java:30)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1172)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:90)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:77)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\openjdk11_j9_openjdktest_x86-64_windows\openjdk-tests\TestConfig\test_output_1550607686587\jdk_rmi_0
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.nio.file.Files.readAttributes(Unknown Source)
	at hudson.Util.isSymlink(Util.java:531)
	at hudson.FilePath.deleteRecursive(FilePath.java:1295)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1314)
	at hudson.FilePath.deleteRecursive(FilePath.java:1296)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1314)
	at hudson.FilePath.deleteRecursive(FilePath.java:1296)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1314)
	at hudson.FilePath.access$1800(FilePath.java:213)
	at hudson.FilePath$DeleteContents.invoke(FilePath.java:1289)
	at hudson.FilePath$DeleteContents.invoke(FilePath.java:1285)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3086)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Unknown Source)
Finished: FAILURE
```

The failure happened when two rmi tests failed
![screen shot 2019-02-27 at 3 53 55 pm](https://user-images.githubusercontent.com/18030625/53522260-fa9c2f80-3aa7-11e9-8c68-bfd5ce0b37f9.png)
![screen shot 2019-02-27 at 3 56 56 pm](https://user-images.githubusercontent.com/18030625/53522450-641c3e00-3aa8-11e9-9e39-30b7a7454a28.png)

which has been excluded with tagged issue https. https://github.com/eclipse/openj9/issues/4772

https://github.com/eclipse/openj9/issues/4778

**Comment by sophia-guo** [comment]
Failure happened when doing `checkout scm`, which is by default wipeout workspace, and then hit the permission issue `java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\openjdk11_j9_openjdktest_x86-64_windows\openjdk-tests\TestConfig\test_output_1550607686587\jdk_rmi_0`. Similar to the former disabled windows machine with msg 'ava.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\openjdk_test_x86-64_windows\openjdk-test\OpenJDK_Playlist\openjdk-jdk8u\jdk\test\sun\management\windows\revokeall.exe`
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/23

**Comment by sophia-guo** [comment]
Deleting the workspace with root permission to manually delete the workspace probably could solve the problem as a workaround.

**Comment by smlambert** [comment]
Please create an infra issue to request someone with root access to try deleting workspace to clear this.

**Comment by sophia-guo** [comment]
Yes, done https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/706. May need help to figure out why some rmi tests failure could cause this on Windows or windows with cgi.

**Comment by sophia-guo** [comment]
As @karianna mentioned in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/706#issuecomment-468477150 the problematic directory were set to `Unknown+User Unknown+Group`, it might be worth checking why/how rmi tests do those setting change. Apparently it cause a common issue on windows.

**Comment by gdams** [comment]
okay I've wiped the workspace, let me know if you still see this issue.

**Comment by karianna** [comment]
@gdams managed to clear this.
